package com.apimarketplace.agent.domain;

import lombok.Builder;

import java.util.Map;

/**
 * A tool call requested by the LLM.
 */
@Builder
public record ToolCall(
    /**
     * Unique identifier for this tool call (generated by LLM)
     */
    String id,

    /**
     * Name of the tool to call (matches ToolDefinition.name)
     */
    String toolName,

    /**
     * Arguments to pass to the tool
     */
    Map<String, Object> arguments,

    /**
     * Index in the response (for parallel tool calls)
     */
    Integer index
) {}
