// Security response headers for every route the Next server answers (LC-027).
//
// Imported by next.config.mjs (headers()) for the STATIC document/API/embeddable rules, and by
// proxy.ts (middleware) for the DYNAMIC nonce-CSP rule applied to the app shell. Kept in its own
// module so the rules can be unit-tested against Next's own route compiler
// (lib/security/__tests__/securityHeaders.test.ts) instead of being read off a config file.
//
// WHY HERE and not only at the edge: the frame policy differs per PATH. `/w/embed/{token}` is
// the chat widget customers put on THEIR site: the embed snippet (AgentController
// generateEmbedCode, CreateAgentModal) is a <script src=".../widget.js">, and WidgetController's
// loader creates an iframe pointing at /w/embed/{token}. `frame-ancestors 'self'` there would
// break every widget already deployed. The public form and application links (`/f/{token}`,
// `/s/{token}`) have NO embed snippet anywhere in the product (no generator, no doc): they are
// shared as links, so they stay first-party (frame-ancestors 'self' + SAMEORIGIN), which also
// closes clickjacking of a form submit. Next is the only layer that knows the path, and the
// only one a self-hosted CE install has (no Traefik there).
//
// SCRIPT-SRC (CASA E3): a strict, ENFORCED script-src is now sent everywhere. Two different
// techniques close two different gaps that used to force 'unsafe-inline' on everything:
//
//   1. Interface HTML (publisher/agent-authored, needs real inline JS) no longer renders via
//      `<iframe srcDoc=...>`. An `about:srcdoc` document INHERITS the embedder's CSP, so any
//      strict script-src on the app page would have blanked every interface. InterfaceIframe.tsx
//      now navigates a SANDBOXED iframe (still no `allow-same-origin` - opaque origin either way)
//      to the dedicated `/interface-frame` shell route and hands it the rendered HTML over
//      postMessage. A real navigation response does NOT inherit the parent's CSP, so the shell
//      gets its OWN response headers (see interfaceFrameHeaders below): maximally permissive for
//      script/style/media (matching what interfaces could already do), but base-uri/object-src/
//      form-action stay at the SAME values the app's enforced CSP already gave them (no
//      behaviour change there - those three were already restricted for interface content).
//      Surfaces that strip publisher JS (`removeScripts=true`: marketplace/showcase previews,
//      thumbnails) keep using `srcDoc` - they contain no script at all by construction, so
//      inheriting the strict app CSP restricts nothing they need.
//
//   2. Every route that renders behind a real session or a one-shot token - `/app/*`,
//      `/ce-setup/*` (CE first-run wizard), the auth/onboarding flows (`/login`, `/register`,
//      `/onboarding`, `/forgot-password`, `/reset-password`, `/invitations`, `/auth`) and the
//      public share/form links (`/s/{token}`, `/f/{token}`: user content, opened by signed-in
//      users, CASA round 2; their layouts read the locale cookie, so they were already rendered
//      per request, and they now say so with their own `force-dynamic`) - gets a
//      per-request NONCE + 'strict-dynamic' script-src, generated by proxy.ts (middleware) and
//      NOT by this static rule table (a nonce must be fresh per request; next.config's
//      headers() is evaluated once, not per request). Every one of these areas now has its OWN
//      `export const dynamic = 'force-dynamic'` layout (app/[locale]/app/layout.tsx - a thin
//      Server Component wrapping the pre-existing client layout, now `AppLayoutClient.tsx` - and
//      one `layout.tsx` per auth/onboarding area, all delegating to
//      components/security/NonceLocaleLayoutBody.tsx), because a nonce is only meaningful on a
//      per-request render (see proxy.ts and Next's own CSP guide). `/app`'s previous layout WAS a
//      Client Component and could not itself opt a route into dynamic rendering - forcing it
//      dynamic was evaluated in round 1 and deliberately deferred pending exactly this split (the
//      alternative, a sibling `template.tsx`, remounts everything BELOW it on every navigation -
//      Next.js semantics - dropping state persisted across an in-app navigation, e.g. an open
//      settings tab; nesting a Server layout around the unchanged Client one avoids that entirely,
//      since a layout never remounts its children on navigation).
//
//      Every OTHER document route - marketing, docs, models, the 404 page and the widget embed
//      (`/w/embed`, framable by design) - keeps the static, non-nonce script-src of
//      `'self' 'unsafe-inline' https:` (residual, accepted: the contact page loads reCAPTCHA from
//      www.google.com and analytics may pull PostHog assets, so the bare `https:` stays there): Next's own per-page hydration/flight data is
//      emitted as an inline <script> whose content is NOT knowable at build time, so a strict,
//      non-'unsafe-inline' policy is only achievable together with a per-request nonce, which in
//      turn requires dynamic rendering. These pages are statically generated for the CDN (see
//      proxy.ts's ISR notes), and `[locale]/layout.tsx` is their common ancestor WITH the
//      nonce-class areas above - the moment any component that ancestor renders calls a dynamic
//      API (headers(), cookies()), Next opts EVERY route under it, marketing included, out of
//      static rendering, since the bailout is evaluated per compiled route and `[locale]/layout`
//      is part of every one of their render trees. So `[locale]/layout.tsx` itself stays exactly
//      as it was: no headers() call, unconditionally static-eligible, and its own
//      `document.documentElement.lang` inline script keeps rendering WITHOUT a nonce for every
//      route (documentLanguage.test.ts pins that literal at the source level). Each nonce-class
//      layout ALSO renders a second, nonced copy of the identical script via HtmlLangSync, which
//      is guaranteed correct under the strict script-src independent of how the DOM ends up
//      creating either copy (these routes are heavily Client-Component-driven, so in practice
//      both copies are reconstructed during hydration from the RSC payload rather than parsed as
//      literal markup, and `'strict-dynamic'` would trust even the unnonced one there - see
//      HtmlLangSync's own comment for why that is an artifact of this rendering path, not
//      something to rely on).
//      'unsafe-inline' still blocks the two things a DAST "no script-src" finding cares about
//      most on the routes that keep it: third-party script HOSTS (script-src has no wildcard/`*`,
//      only 'self' and https:) and non-HTML sinks (object-src stays 'none' everywhere, nonce
//      class included).
//
// style-src keeps 'unsafe-inline' EVERYWHERE, including the nonce class: Tailwind/Next inject
// inline `style=` attributes and <style> tags all over the app, and nonce-ing every one of them
// is a much larger, higher-risk change for a directive CASA/ASVS treats as low severity (no code
// execution). connect-src/img-src/media-src/font-src/frame-src stay scheme-based (`https:`,
// `data:`, `blob:`) rather than naming hosts, so CE (a different origin, sometimes plain http on
// a LAN) is not hardcoded out - see connectSrc() for the one place CE needs `http:`/`ws:` too.
//
// The fuller policy ships as Content-Security-Policy-Report-Only and reports to the same-origin
// /api/csp-report handler (report-uri for Firefox/Safari, report-to + Reporting-Endpoints for
// Chromium), which logs a sanitized, rate-limited directive + host summary. It intentionally
// stays broader than the enforced policy (unconditional 'unsafe-eval', wider hosts): it is the
// forward-looking measurement channel for the NEXT tightening pass, not a mirror of what is
// enforced today.
//
// API routes (`/api/*`, served here only for /api/proxy, /api/status, /api/pricing-event) get
// the transport headers (HSTS, nosniff) but no document policy: the proxy forwards the backend's
// own per-file headers (a sandboxed CSP on stored files, `Referrer-Policy: no-referrer` on
// token-bearing pages), and a second, weaker value set here must not compete with them.

/** HSTS. Ignored by browsers over plain http and over a TLS connection with certificate errors,
 * so a CE install on a LAN IP is unaffected. `includeSubDomains` only for the cloud edition: a
 * self-hoster serving CE from an apex domain must not have the header pin their other hosts. */
export function strictTransportSecurity(edition) {
  return edition === 'ce' ? 'max-age=31536000' : 'max-age=31536000; includeSubDomains';
}

/** Features the app never uses are denied to itself and every frame. `microphone=(self)`: the
 * chat composer's voice input uses SpeechRecognition. Features the app DELEGATES to embeds are
 * deliberately not listed (autoplay, encrypted-media, fullscreen, picture-in-picture,
 * clipboard-write, accelerometer, gyroscope, web-share: FilmPlayer's YouTube iframe asks for
 * them), since a header value of `()` would override the iframe's `allow` attribute. */
export const PERMISSIONS_POLICY =
  'camera=(), microphone=(self), geolocation=(), payment=(), usb=(), serial=(), hid=(), browsing-topics=()';

/** base-uri/object-src/form-action: unchanged by CASA E3 (already enforced pre-E3, and reused
 * verbatim by the `/interface-frame` shell so interface content keeps the exact same behaviour
 * on those three directives it already had). */
export const CSP_ENFORCED_BASE = "base-uri 'self'; object-src 'none'; form-action 'self' https:";

export const CSP_REPORT_ONLY_BASE = [
  "default-src 'self'",
  // 'unsafe-inline' + 'unsafe-eval': this is the forward-looking/exploratory channel, not a
  // mirror of the enforced policy (see module header).
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: https:",
  "style-src 'self' 'unsafe-inline' https:",
  "img-src 'self' data: blob: https:",
  "media-src 'self' data: blob: https:",
  "font-src 'self' data: https:",
  "connect-src 'self' https: wss: ws:",
  "frame-src 'self' data: blob: https:",
  "worker-src 'self' blob:",
  "base-uri 'self'",
  "object-src 'none'",
  "form-action 'self' https:",
].join('; ');

/** Same-origin endpoint receiving Report-Only violations (app/api/csp-report/route.ts). */
export const CSP_REPORT_PATH = '/api/csp-report';
const CSP_REPORT_GROUP = 'csp-endpoint';

/** Public runtimes a third-party page is expected to frame (path prefixes, no slashes). */
export const EMBEDDABLE_PREFIXES = ['w/embed'];

/** The dedicated interface-rendering shell (see module header, point 1). Never embeddable by a
 * third party (frame-ancestors 'self' - only this app ever frames it) and never locale-prefixed. */
export const INTERFACE_FRAME_PATH = 'interface-frame';

/** Path prefixes whose document gets the per-request NONCE script-src instead of the static
 * 'unsafe-inline' one (see module header, point 2). Every entry has its own
 * `export const dynamic = 'force-dynamic'` layout, which is what guarantees the nonce is fresh
 * per request (Next requires dynamic rendering for a nonce to mean anything - a statically built
 * page cannot know a per-request value): `app` (app/[locale]/app/layout.tsx, wrapping the
 * pre-existing client layout as AppLayoutClient.tsx), `ce-setup`
 * (app/[locale]/ce-setup/layout.tsx) and the auth/onboarding areas, each delegating to
 * components/security/NonceLocaleLayoutBody.tsx. Marketing/docs/blog stay OFF this list
 * deliberately (see module header). Adding a prefix here is safe ONLY once its route is
 * verifiably dynamic; `isNonceCspPath` below is the single place both proxy.ts and this module's
 * own exclusion regex read this list from, so they can never drift apart (two CSP headers on one
 * response intersect - see securityHeaderRules). */
export const NONCE_CSP_PREFIXES = [
  'app',
  'ce-setup',
  'auth',
  'onboarding',
  'login',
  'register',
  'invitations',
  'forgot-password',
  'reset-password',
  // Public share and form links (app/s/[token], app/f/[token], each with its own force-dynamic
  // layout). Exact first segments: `/support` or `/faq` are NOT matched.
  's',
  'f',
];

const LOCALES = ['en', 'fr', 'es', 'de', 'pt', 'zh'];

/** True for `/app`, `/fr/app/...`, `/ce-setup`, `/en/ce-setup/...`, `/login`, `/register`,
 * `/onboarding`, `/forgot-password`, `/reset-password`, `/invitations`, `/auth`, and their
 * locale-prefixed forms. Shared by proxy.ts
 * (decides whether to emit the nonce CSP) and this module's own exclusion regex (keeps the
 * static next.config rule from ALSO matching the same path - two CSP headers on one response
 * intersect, so whichever is stricter silently wins over the other, which is not a decision
 * either side means to make). */
export function isNonceCspPath(pathname) {
  const segments = pathname.split('/').filter(Boolean);
  if (segments.length === 0) return false;
  const first = segments[0];
  const candidate = LOCALES.includes(first) ? segments[1] : first;
  return NONCE_CSP_PREFIXES.includes(candidate);
}

/** The plain-http LOOPBACK origins among the build-time service URLs the BROWSER calls
 * directly: the identity provider (NEXT_PUBLIC_KEYCLOAK_URL: oidc-client fetches its discovery
 * document, token and logout endpoints itself) and the realtime gateway
 * (NEXT_PUBLIC_GATEWAY_WS_URL; an `http://` source also matches `ws://` on the same host and
 * port, CSP3 scheme matching). A deployed cloud build uses https URLs, or none, which `https:`
 * and `wss:` already cover, so this returns [] there and the header stays byte-identical. Only
 * a local cloud build (`next dev`, the cloud e2e stack: Keycloak on http://localhost:8180, the
 * gateway on http://localhost:8080) needs them. Never widened to a non-loopback http host:
 * cloud stays https-only on the network. */
export function loopbackServiceOrigins(serviceUrls = []) {
  const origins = [];
  for (const raw of serviceUrls) {
    if (!raw) continue;
    let url;
    try {
      url = new URL(raw);
    } catch {
      continue;
    }
    if (url.protocol !== 'http:') continue;
    // No IPv6 literal: the CSP host-source grammar has none, so `http://[::1]` would be ignored.
    const loopback = url.hostname === 'localhost' || url.hostname === '127.0.0.1';
    if (loopback && !origins.includes(url.origin)) origins.push(url.origin);
  }
  return origins;
}

/** CE runs on a LAN, sometimes over plain http, and its Keycloak/gateway host is whatever the
 * operator configured - never hardcode a hostname here (that would be cloud-only and break CE).
 * Cloud stays https/wss only, plus the configured local plain-http services (see
 * loopbackServiceOrigins); CE additionally allows http/ws so a LAN deployment still works. */
function connectSrc(edition, serviceUrls) {
  if (edition === 'ce') return "'self' http: https: ws: wss:";
  return ["'self' https: wss:", ...loopbackServiceOrigins(serviceUrls)].join(' ');
}

/** `'unsafe-eval'` only in dev: React's dev build uses it to reconstruct server error stacks in
 * the browser; Next/React never call it in production. Matches Next's own CSP guide. */
function scriptSrc({ nonce, isDev }) {
  const evalToken = isDev ? " 'unsafe-eval'" : '';
  if (nonce) {
    // 'unsafe-inline' is harmless here for CSP2+ browsers (a nonce present makes them ignore
    // it) and is a graceful degrade for anything that only understands CSP1.
    return `'self' 'nonce-${nonce}' 'strict-dynamic' 'unsafe-inline'${evalToken}`;
  }
  return `'self' 'unsafe-inline' https:${evalToken}`;
}

/** The directives shared by every document route (nonce class and static class alike); only
 * script-src and connect-src vary. */
function fullCspDirectives({ nonce, edition, isDev, serviceUrls }) {
  return [
    "default-src 'self'",
    `script-src ${scriptSrc({ nonce, isDev })}`,
    // Low severity, high blast radius to close (see module header) - stays permissive everywhere.
    "style-src 'self' 'unsafe-inline' https:",
    "img-src 'self' data: blob: https:",
    "media-src 'self' data: blob: https:",
    "font-src 'self' data: https:",
    `connect-src ${connectSrc(edition, serviceUrls)}`,
    "frame-src 'self' data: blob: https:",
    "worker-src 'self' blob:",
    "base-uri 'self'",
    "object-src 'none'",
    "form-action 'self' https:",
  ];
}

function documentHeaders(frameAncestors, { edition, isDev = false, nonce, serviceUrls } = {}) {
  const enforced = `${fullCspDirectives({ nonce, edition, isDev, serviceUrls }).join('; ')}; frame-ancestors ${frameAncestors}`;
  return [
    { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
    { key: 'Permissions-Policy', value: PERMISSIONS_POLICY },
    // Keeps window.opener for popups this page opens (checkout, OAuth consent in a new tab)
    // while cutting the link from pages that open us. The app never reads window.opener.
    { key: 'Cross-Origin-Opener-Policy', value: 'same-origin-allow-popups' },
    { key: 'X-Permitted-Cross-Domain-Policies', value: 'none' },
    { key: 'Content-Security-Policy', value: enforced },
    {
      key: 'Content-Security-Policy-Report-Only',
      value: `${CSP_REPORT_ONLY_BASE}; frame-ancestors ${frameAncestors}; report-uri ${CSP_REPORT_PATH}; report-to ${CSP_REPORT_GROUP}`,
    },
    { key: 'Reporting-Endpoints', value: `${CSP_REPORT_GROUP}="${CSP_REPORT_PATH}"` },
  ];
}

/**
 * Builds the full document header set for the NONCE class (`/app/*`, `/ce-setup/*`, the
 * auth/onboarding areas - see NONCE_CSP_PREFIXES for the full list), for proxy.ts to send per
 * request. `nonce` must be freshly random per call (proxy.ts generates it
 * with `crypto.randomUUID()`); this function is pure so it can be unit-tested without a request.
 *
 * @param {{ nonce: string, edition?: string, isDev?: boolean, serviceUrls?: string[] }} options
 *   serviceUrls = the browser-called service URLs (see loopbackServiceOrigins)
 */
export function nonceDocumentHeaders({ nonce, edition, isDev = false, serviceUrls }) {
  if (!nonce) throw new Error('nonceDocumentHeaders requires a non-empty nonce');
  return [
    ...documentHeaders("'self'", { edition, isDev, nonce, serviceUrls }),
    { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
  ];
}

/**
 * The `/interface-frame` shell's own response headers (see module header, point 1). Permissive
 * for script/style/media (interface content could already run any inline script it wanted, via
 * srcdoc inheritance) but base-uri/object-src/form-action are the SAME already-enforced values
 * as every other document (CSP_ENFORCED_BASE, reused verbatim - no behaviour change there).
 * Never nonce'd: the shell is a static, edition-agnostic string with nothing dynamic in it.
 */
export function interfaceFrameHeaders() {
  const csp = [
    "script-src * data: blob: 'unsafe-inline' 'unsafe-eval'",
    "style-src * data: blob: 'unsafe-inline'",
    'img-src * data: blob:',
    'media-src * data: blob:',
    'font-src * data:',
    'connect-src *',
    'frame-src * data: blob:',
    'worker-src * blob:',
    CSP_ENFORCED_BASE,
    "frame-ancestors 'self'",
  ].join('; ');
  return [
    { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
    { key: 'X-Permitted-Cross-Domain-Policies', value: 'none' },
    { key: 'Content-Security-Policy', value: csp },
    { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
  ];
}

/**
 * The header rules for next.config.mjs `headers()`. Covers every document route EXCEPT the
 * nonce class (`/app/*`, `/ce-setup/*`, the auth/onboarding areas - see NONCE_CSP_PREFIXES -
 * proxy.ts sends their CSP per request, see module header) and gives the interface shell its own
 * dedicated, permissive rule.
 *
 * Next applies EVERY matching rule, and two rules setting the same header on one response emit
 * it twice (browsers intersect two CSPs, so the strict one would win and the widget - or the
 * nonce class, or the interface shell - would be blocked anyway). The embeddable prefixes,
 * nonce-class prefixes, interface shell and /api are therefore EXCLUDED from the default
 * document rule by a negative lookahead rather than relying on rule order.
 *
 * @param {{ edition?: string, isDev?: boolean, serviceUrls?: string[] }} options edition =
 *   NEXT_PUBLIC_APP_EDITION at build time, serviceUrls = see loopbackServiceOrigins
 */
export function securityHeaderRules({ edition, isDev = process.env.NODE_ENV !== 'production', serviceUrls } = {}) {
  const localeAlt = `(?:${LOCALES.join('|')})/`;
  const nonceExclusions = NONCE_CSP_PREFIXES.flatMap((prefix) => [
    `${prefix}(?:/|$)`,
    `${localeAlt}${prefix}(?:/|$)`,
  ]);
  const excluded = [
    'api/',
    'api$',
    `${INTERFACE_FRAME_PATH}(?:/|$)`,
    ...EMBEDDABLE_PREFIXES.map((prefix) => `${prefix}(?:/|$)`),
    ...nonceExclusions,
  ];
  return [
    {
      source: '/:path*',
      headers: [
        { key: 'Strict-Transport-Security', value: strictTransportSecurity(edition) },
        { key: 'X-Content-Type-Options', value: 'nosniff' },
      ],
    },
    {
      source: `/:path((?!${excluded.join('|')}).*)`,
      headers: [...documentHeaders("'self'", { edition, isDev, serviceUrls }), { key: 'X-Frame-Options', value: 'SAMEORIGIN' }],
    },
    // No X-Frame-Options here: its only values are DENY/SAMEORIGIN, and browsers that still
    // honour it over frame-ancestors would refuse the customer's frame.
    ...EMBEDDABLE_PREFIXES.map((prefix) => ({
      source: `/${prefix}/:path*`,
      headers: documentHeaders('*', { edition, isDev, serviceUrls }),
    })),
    {
      source: `/${INTERFACE_FRAME_PATH}`,
      headers: interfaceFrameHeaders(),
    },
  ];
}
