import type { BlogTranslation } from '../i18n';
import theNicheDataAdvantage from '../content/de/the-niche-data-advantage';
import chatToWorkflowNoCode from '../content/de/chat-to-workflow-no-code';
import fromDatasetToLiveWorkflow from '../content/de/from-dataset-to-live-workflow';
import workflowBeatsDoEverythingAgent from '../content/de/workflow-beats-do-everything-agent';
import capAiAgentCostBudgets from '../content/de/cap-ai-agent-cost-budgets';
import sizeAnAiAgentBudget from '../content/de/size-an-ai-agent-budget';
import aiAgentAuditTrail from '../content/de/ai-agent-audit-trail';
import aiAgentAuditLogRetention from '../content/de/ai-agent-audit-log-retention';

export const deBlog: BlogTranslation = {
  ui: {
    eyebrow: "Notizen aus der Praxis", blogTitle: "Blog", lead: "Notizen zu Nischendaten und den Automatisierungen, die darauf aufbauen. Warum schmale Datensätze breite schlagen und wie man eine Quelle in einen Workflow verwandelt, der sich selbst betreibt.", latest: "Neueste", readThePost: "Beitrag lesen", readMore: "Weiterlesen", allPosts: "Alle Beiträge", minRead: "Min. Lesezeit", by: "Von", and: "und", ctaTitle: "Verwandle deine Nischendaten in eine funktionierende Automatisierung", ctaText: "Beschreibe die Aufgabe im Chat, und LiveContext baut den Workflow vor deinen Augen.", startFree: "Kostenlos starten", metaTitle: "Blog - LiveContext", metaDescription: "Notizen aus der Praxis zu Nischendaten und den Automatisierungen, die darauf aufbauen: warum schmale Datensätze breite schlagen und wie man eine Quelle in einen Workflow verwandelt, der sich selbst betreibt.",
  },
  posts: {
    "the-niche-data-advantage": { title: "Der Vorteil von Nischendaten, mit Preis", excerpt: "Die Belege gegen den Datengraben sind stärker als die dafür. Also bepreist dieser Text die Nischendaten-These, statt sie zu loben: zuerst das stärkste Gegenargument, dann ein einziger zu messender Parameter, eine Scorecard mit sieben Zeilen, und ein Break-even zwischen bauen, kaufen oder nichts tun.", coverAlt: "Ein Laptop zeigt ein Analyse-Dashboard mit Diagrammen, einer Karte und Kennzahlen", content: theNicheDataAdvantage },
    "chat-to-workflow-no-code": { title: "Vom Chat zum Workflow: No-Code-KI-Automatisierung", excerpt: "Beschreibe die Aufgabe in klarer Sprache und erhalte einen Workflow, den du sehen, ausführen und verändern kannst. Keine Knoten von Hand zu verdrahten, keine Blackbox.", coverAlt: "Eine Hand tippt eine Nachricht auf einem Telefon, das eine Chat-Unterhaltung zeigt", content: chatToWorkflowNoCode },
    "from-dataset-to-live-workflow": { title: "Vom Datensatz zum laufenden Workflow, Knoten für Knoten", excerpt: "Ein echter Graph auf einer Produktions-Engine: eine geplante Preisüberwachung, die auffrischt, entscheidet und einen Schreibvorgang absichert. Mit den exakten Template-Strings, die auflösen, denen, die stumm scheitern, und dem idempotenten Wächter, der doppelte Zeilen verhindert.", coverAlt: "Eine Hand zeichnet ein Workflow-Diagramm aus verbundenen Kästen und Pfeilen auf einem Whiteboard", content: fromDatasetToLiveWorkflow },
    "workflow-beats-do-everything-agent": { title: "Was ein eng gefasster Workflow wirklich kostet, verglichen mit einem Alleskönner-Agenten", excerpt: "Wir haben unsere eigene Behauptung „10x günstiger“ gestrichen, weil sie keine Herleitung hatte. Stattdessen hier das Kostenmodell: zwei Funktionen, eine davon quadratisch, ein durchgerechnetes Triage-Ledger, und die Bedingungen, unter denen das Verhältnis auf 1,3x fällt oder sich umkehrt.", coverAlt: "Ein einzelner Roboterarm auf einem Ständer, der einen autonomen Agenten darstellt", content: workflowBeatsDoEverythingAgent },
    "cap-ai-agent-cost-budgets": { title: "Das Budget, das den Agenten wirklich stoppt", excerpt: "Die meisten Agent-Budgets sind eine Zahl, die noch nie einen einzigen Aufruf verweigert hat. Woraus eine echte Obergrenze besteht, warum sie immer nur den nächsten Aufruf stoppen kann, und was jeder Stack tatsächlich durchsetzt.", coverAlt: "Münzen verstreut auf einem Schreibtisch neben einem Notizbuch und Stift für die Budgetplanung", content: capAiAgentCostBudgets },
    "size-an-ai-agent-budget": { title: "Wie man ein Agent-Budget bemisst, das sich wirklich durchsetzen lässt", excerpt: "Die Bemessungshälfte: ein reproduzierbares Erzeugungsmodell, ein hergeleiteter Sicherheitsfaktor, die Untergrenze, unterhalb derer eine Geldobergrenze gar nicht mehr durchsetzbar ist, und wie viele Läufe nötig sind, bevor man ein p99 nennen darf.", coverAlt: "Hände nutzen einen Taschenrechner neben gedruckten Diagrammen bei der Datenanalyse", content: sizeAnAiAgentBudget },
    "ai-agent-audit-trail": { title: "Die Prüfspur eines Agenten: ein Feldschema zum Kopieren", excerpt: "Eine Prüfspur ist kein längeres Log, sie ist ein anderes Artefakt mit einem anderen Leser. Ein kopierbares Schema auf Run- und Schritt-Ebene, in dem jedes Feld seinen Typ, seine Kardinalität, sein Personendaten-Flag und seinen Existenzgrund trägt.", coverAlt: "Eine Lupe und ein Taschenrechner liegen auf gedruckten Dokumenten", content: aiAgentAuditTrail },
    "ai-agent-audit-log-retention": { title: "Wie lange man die Prüfspur eines Agenten aufbewahrt, und was du wirklich schuldest", excerpt: "Die Speicher-Arithmetik, die Aufbewahrung zu einer hergeleiteten Entscheidung macht, die daraus folgende Staffelung, und eine ehrliche Karte der Protokollpflichten des EU AI Act, samt dem Teil, in dem die meisten Agenten gar nicht in den Anwendungsbereich fallen.", coverAlt: "Eine Hand zeichnet ein Workflow-Diagramm aus verbundenen Kästen und Pfeilen auf einem Whiteboard", content: aiAgentAuditLogRetention },
  },
};
