import type { BlogTranslation } from '../i18n';
import theNicheDataAdvantage from '../content/es/the-niche-data-advantage';
import chatToWorkflowNoCode from '../content/es/chat-to-workflow-no-code';
import fromDatasetToLiveWorkflow from '../content/es/from-dataset-to-live-workflow';
import workflowBeatsDoEverythingAgent from '../content/es/workflow-beats-do-everything-agent';
import capAiAgentCostBudgets from '../content/es/cap-ai-agent-cost-budgets';
import sizeAnAiAgentBudget from '../content/es/size-an-ai-agent-budget';
import aiAgentAuditTrail from '../content/es/ai-agent-audit-trail';
import aiAgentAuditLogRetention from '../content/es/ai-agent-audit-log-retention';

export const esBlog: BlogTranslation = {
  ui: {
    eyebrow: "Notas de campo", blogTitle: "Blog", lead: "Notas sobre datos de nicho y las automatizaciones que se construyen sobre ellos. Por qué los conjuntos de datos estrechos le ganan a los amplios, y cómo convertir una fuente en un flujo de trabajo que corre por sí solo.", latest: "Lo último", readThePost: "Leer el artículo", readMore: "Leer más", allPosts: "Todos los artículos", minRead: "min de lectura", by: "Por", and: "y", ctaTitle: "Convierte tus datos de nicho en una automatización que funciona", ctaText: "Describe la tarea en el chat y LiveContext construye el flujo de trabajo ante tus ojos.", startFree: "Empieza gratis", metaTitle: "Blog - LiveContext", metaDescription: "Notas de campo sobre datos de nicho y las automatizaciones que se construyen sobre ellos: por qué los conjuntos de datos estrechos le ganan a los amplios, y cómo convertir una fuente en un flujo de trabajo que corre por sí solo.",
  },
  posts: {
    "the-niche-data-advantage": { title: "La ventaja de los datos de nicho, con precio", excerpt: "La evidencia contra el foso es más fuerte que la que lo apoya. Así que esto pone precio a la tesis de los datos de nicho en vez de alabarla: primero el mejor argumento en contra, luego un parámetro que medir, una tarjeta de siete filas, y un punto de equilibrio entre construir, comprar o no hacer nada.", coverAlt: "Un portátil que muestra un panel de análisis con gráficos, un mapa y métricas", content: theNicheDataAdvantage },
    "chat-to-workflow-no-code": { title: "Del chat al flujo de trabajo: automatización con IA sin código", excerpt: "Describe la tarea en lenguaje sencillo y obtén un flujo de trabajo que puedes ver, ejecutar y cambiar. Sin nodos que conectar a mano, sin caja negra.", coverAlt: "Una mano escribiendo un mensaje en un teléfono que muestra una conversación de chat", content: chatToWorkflowNoCode },
    "from-dataset-to-live-workflow": { title: "Del conjunto de datos al flujo de trabajo en vivo, nodo a nodo", excerpt: "Un grafo real sobre un motor de producción: una vigilancia de precios programada que refresca, decide y protege una escritura. Con las cadenas de plantilla exactas que se resuelven, las que fallan en silencio, y el guardián idempotente que evita duplicar filas.", coverAlt: "Una mano dibujando en una pizarra un diagrama de flujo de trabajo con cajas conectadas y flechas", content: fromDatasetToLiveWorkflow },
    "workflow-beats-do-everything-agent": { title: "Lo que cuesta de verdad un flujo de trabajo acotado frente a un agente que lo hace todo", excerpt: "Hemos eliminado nuestra propia afirmación de «10x más barato» porque no tenía ninguna derivación. En su lugar, aquí está el modelo de coste: dos funciones, una cuadrática, un libro mayor de triaje calculado, y las condiciones en las que la proporción cae a 1,3x o se invierte.", coverAlt: "Un único brazo robótico sobre un soporte, que representa un agente autónomo", content: workflowBeatsDoEverythingAgent },
    "cap-ai-agent-cost-budgets": { title: "El presupuesto que de verdad detiene al agente", excerpt: "La mayoría de los presupuestos de agente son un número que nunca ha rechazado una sola llamada. De qué está hecho un techo real, por qué solo puede detener la llamada siguiente, y qué aplica realmente cada stack.", coverAlt: "Monedas esparcidas sobre un escritorio junto a un cuaderno y un bolígrafo para hacer presupuestos", content: capAiAgentCostBudgets },
    "size-an-ai-agent-budget": { title: "Cómo dimensionar un presupuesto de agente que se pueda aplicar de verdad", excerpt: "La mitad de dimensionamiento: un modelo generador reproducible, un factor de seguridad derivado, el suelo por debajo del cual un tope monetario ya no se puede aplicar, y cuántas ejecuciones hacen falta antes de poder citar un p99.", coverAlt: "Manos usando una calculadora junto a gráficos impresos mientras analizan datos", content: sizeAnAiAgentBudget },
    "ai-agent-audit-trail": { title: "El registro de auditoría de un agente: un esquema de campos que puedes copiar", excerpt: "Un registro de auditoría no es un log más largo, es un artefacto distinto con otro lector. Un esquema copiable a nivel de run y de paso, donde cada campo lleva su tipo, su cardinalidad, su marca de dato personal y la razón de existir.", coverAlt: "Una lupa y una calculadora apoyadas sobre documentos impresos", content: aiAgentAuditTrail },
    "ai-agent-audit-log-retention": { title: "Cuánto tiempo guardar el registro de auditoría de un agente, y qué debes de verdad", excerpt: "La aritmética de almacenamiento que convierte la retención en una decisión derivada, la escala por niveles que se sigue, y un mapa honesto de las obligaciones de registro de la EU AI Act, incluida la parte en que la mayoría de los agentes quedan fuera de alcance.", coverAlt: "Una mano dibujando en una pizarra un diagrama de flujo de trabajo con cajas conectadas y flechas", content: aiAgentAuditLogRetention },
  },
};
