import type { BlogTranslation } from '../i18n';
import theNicheDataAdvantage from '../content/pt/the-niche-data-advantage';
import chatToWorkflowNoCode from '../content/pt/chat-to-workflow-no-code';
import fromDatasetToLiveWorkflow from '../content/pt/from-dataset-to-live-workflow';
import workflowBeatsDoEverythingAgent from '../content/pt/workflow-beats-do-everything-agent';
import capAiAgentCostBudgets from '../content/pt/cap-ai-agent-cost-budgets';
import sizeAnAiAgentBudget from '../content/pt/size-an-ai-agent-budget';
import aiAgentAuditTrail from '../content/pt/ai-agent-audit-trail';
import aiAgentAuditLogRetention from '../content/pt/ai-agent-audit-log-retention';

export const ptBlog: BlogTranslation = {
  ui: {
    eyebrow: "Notas de terreno", blogTitle: "Blog", lead: "Notas sobre dados de nicho e as automatizações construídas sobre eles. Porque é que os conjuntos de dados estreitos vencem os amplos, e como transformar uma fonte num workflow que se executa a si próprio.", latest: "Mais recente", readThePost: "Ler o artigo", readMore: "Ler mais", allPosts: "Todos os artigos", minRead: "min de leitura", by: "Por", and: "e", ctaTitle: "Transforme os seus dados de nicho numa automatização a funcionar", ctaText: "Descreva a tarefa no chat e o LiveContext constrói o workflow à sua frente.", startFree: "Comece grátis", metaTitle: "Blog - LiveContext", metaDescription: "Notas de terreno sobre dados de nicho e as automatizações construídas sobre eles: porque é que os conjuntos de dados estreitos vencem os amplos, e como transformar uma fonte num workflow que se executa a si próprio.",
  },
  posts: {
    "the-niche-data-advantage": { title: "A vantagem dos dados de nicho, com preço", excerpt: "As provas contra o fosso são mais fortes do que as a favor. Por isso este texto põe preço à tese dos dados de nicho em vez de a elogiar: primeiro o argumento mais forte contra, depois um parâmetro a medir, um scorecard de sete linhas, e um ponto de equilíbrio entre construir, comprar ou não fazer nada.", coverAlt: "Um portátil a mostrar um painel de análise com gráficos, um mapa e métricas", content: theNicheDataAdvantage },
    "chat-to-workflow-no-code": { title: "Do chat ao workflow: automatização de IA no-code", excerpt: "Descreva a tarefa em linguagem simples e obtenha um workflow que consegue ver, executar e alterar. Sem nós para ligar à mão, sem caixa preta.", coverAlt: "Uma mão a escrever uma mensagem num telemóvel que mostra uma conversa de chat", content: chatToWorkflowNoCode },
    "from-dataset-to-live-workflow": { title: "Do conjunto de dados ao workflow vivo, nó a nó", excerpt: "Um grafo real numa engine de produção: uma vigilância de preços agendada que atualiza, decide e protege uma escrita. Com as strings de template exatas que resolvem, as que falham em silêncio, e a guarda idempotente que o impede de duplicar linhas.", coverAlt: "Uma mão a desenhar num quadro branco um diagrama de workflow com caixas ligadas e setas", content: fromDatasetToLiveWorkflow },
    "workflow-beats-do-everything-agent": { title: "Quanto custa mesmo um workflow delimitado face a um agente que faz tudo", excerpt: "Eliminámos a nossa própria afirmação de «10x mais barato» porque não tinha qualquer derivação. Em vez dela, eis o modelo de custo: duas funções, uma quadrática, um livro-razão de triagem calculado, e as condições em que o rácio cai para 1,3x ou se inverte.", coverAlt: "Um único braço robótico num suporte, a representar um agente autónomo", content: workflowBeatsDoEverythingAgent },
    "cap-ai-agent-cost-budgets": { title: "O orçamento que para mesmo o agente", excerpt: "A maioria dos orçamentos de agente é um número que nunca recusou uma única chamada. De que é feito um tecto real, porque é que só consegue parar a chamada seguinte, e o que cada stack aplica de facto.", coverAlt: "Moedas espalhadas numa secretária ao lado de um caderno e uma caneta para orçamentar", content: capAiAgentCostBudgets },
    "size-an-ai-agent-budget": { title: "Como dimensionar um orçamento de agente que se consiga mesmo aplicar", excerpt: "A metade do dimensionamento: um modelo gerador reproduzível, um factor de segurança derivado, o piso abaixo do qual um tecto monetário deixa de ser aplicável, e quantas execuções são precisas antes de se poder citar um p99.", coverAlt: "Mãos a usar uma calculadora ao lado de gráficos impressos enquanto analisam dados", content: sizeAnAiAgentBudget },
    "ai-agent-audit-trail": { title: "A trilha de auditoria de um agente: um esquema de campos para copiar", excerpt: "Uma trilha de auditoria não é um log mais longo, é um artefacto diferente com outro leitor. Um esquema copiável ao nível do run e do passo, onde cada campo carrega o seu tipo, a sua cardinalidade, a sua marca de dado pessoal e a razão de existir.", coverAlt: "Uma lupa e uma calculadora pousadas sobre documentos impressos", content: aiAgentAuditTrail },
    "ai-agent-audit-log-retention": { title: "Quanto tempo guardar a trilha de auditoria de um agente, e o que deve mesmo", excerpt: "A aritmética de armazenamento que torna a retenção uma decisão derivada, o escalonamento que daí resulta, e um mapa honesto das obrigações de registo do EU AI Act, incluindo a parte em que a maioria dos agentes fica fora de âmbito.", coverAlt: "Uma mão a desenhar num quadro branco um diagrama de workflow com caixas ligadas e setas", content: aiAgentAuditLogRetention },
  },
};
