package com.apimarketplace.conversation.service.ai;

import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Conditionally creates BridgeClient bean when bridge is enabled.
 * Feature flag: conversation.bridge.enabled=true
 */
@Configuration
public class BridgeClientConfig {

    /**
     * @param gatewaySecretKey {@code conversation.bridge.shared-secret} when set (the CE monolith: a per-install
     *        secret generated by ce-entrypoint.sh and shared with the bridge container), else the raw
     *        {@code GATEWAY_SECRET_KEY} env var (cloud: the value the bridge process also holds). Never
     *        {@code gateway.filter.secret-key}: the CE monolith pins that to a placeholder.
     * @param hostToolsEnabled LC-022: whether a PLATFORM ADMIN caller may get an unrestricted run;
     *        default false. Non-admin runs are always restricted.
     */
    @Bean
    @ConditionalOnProperty(name = "conversation.bridge.enabled", havingValue = "true")
    public BridgeClient bridgeClient(
            @Value("${conversation.bridge.url:http://localhost:8093}") String bridgeUrl,
            @Value("${conversation.bridge.shared-secret:${GATEWAY_SECRET_KEY:}}") String gatewaySecretKey,
            @Value("${conversation.bridge.host-tools-enabled:false}") boolean hostToolsEnabled) {
        return new BridgeClient(bridgeUrl, gatewaySecretKey, hostToolsEnabled);
    }
}
