/**
 * Types for API configuration functionality
 */

export interface ApiConfigurationRequest {
  apiName: string;
  apiDescription: string;
  selectedCategory: string;
  selectedSubcategory: string;
  categoryId?: string;
  subcategoryId?: string;
  apiConfig: ApiConfig;
  monetization: MonetizationConfig;
  mcpTools: McpTool[];
}

export interface ApiConfig {
  baseUrl: string;
  healthcheckEndpoint: string;
  authorization: Authorization;
  visibility: string;
}

export interface Authorization {
  type: string;
  description: string;
  headerName: string;
  headerValue: string;
}

export interface MonetizationConfig {
  pricing: string;
  selectedPricingModels?: ('freemium' | 'paid')[];
  toolFreeRequests?: Record<string, string | number>;
  toolRateLimits?: Record<string, ToolRateLimits>;
  toolPricing?: Record<string, ToolPricing>;
  // For FREEMIUM: rate limit and pricing
  rateLimit?: {
    requests: number;
    period: string;
  };
  freeRequestsPerUser?: number;
  uniformToolPrice?: number;
  uniformToolPriceInDollars?: number;
  // For PAID: plan configuration
  selectedPlans?: {
    basic: boolean;
    pro: boolean;
    ultra: boolean;
    mega: boolean;
  };
  priceBasic?: number;
  pricePro?: number;
  priceUltra?: number;
  priceMega?: number;
  quotaBasic?: number;
  quotaPro?: number;
  quotaUltra?: number;
  quotaMega?: number;
  rpsBasic?: number;
  rpsPro?: number;
  rpsUltra?: number;
  rpsMega?: number;
  rpsPeriodBasic?: string;
  rpsPeriodPro?: string;
  rpsPeriodUltra?: string;
  rpsPeriodMega?: string;
  overusageCostBasic?: number;
  overusageCostPro?: number;
  overusageCostUltra?: number;
  overusageCostMega?: number;
  hardLimitBasic?: boolean;
  hardLimitPro?: boolean;
  hardLimitUltra?: boolean;
  hardLimitMega?: boolean;
  planTools?: {
    basic: string[];
    pro: string[];
    ultra: string[];
    mega: string[];
  };
}

export interface ToolFreeRequests {
  id: string;
  value: number | string;
  type: string;
}

export interface ToolRateLimits {
  id: string;
  requests: number;
  period: string;
}

export interface ToolPricing {
  id: string;
  mauValue: number;
  price: number;
  currency: string;
}

import type { ToolRuntimeMetadata } from './runtimeMetadata';

export interface McpTool {
  id?: string; // Optional - will be generated by backend
  name: string;
  description: string;
  endpoint: string;
  method: string;
  toolCategory: string;
  toolNameId?: string; // ID du nom d'outil dans la DB
  isCustomCategory?: boolean; // Indique si c'est une categorie personnalisee
  isCustomToolName?: boolean; // Indique si c'est un nom d'outil personnalise
  headers: Header[];
  pathParameters: PathParameter[];
  queryParameters: QueryParameter[];
  bodyParams: BodyParam[];
  response: Response;
  runtimeMetadata?: ToolRuntimeMetadata;
}

export interface Header {
  name: string;
  value: string;
  required: boolean;
}

export interface PathParameter {
  name: string;
  type: string;
  required: boolean;
  description: string;
  example: string;
  pattern: string;
}

export interface QueryParameter {
  name: string;
  type: string;
  required: boolean;
  description: string;
  example: string;
  defaultValue: string;
  allowedValues: string[];
}

export interface BodyParam {
  name: string;
  value: string;
  type: string;
  description: string;
  fileSize: string;
}

export interface Response {
  type: string;
  description: string;
  schema?: any;
  success?: any;
  error?: any;
}
