package com.apimarketplace.auth.util;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The Spring-managed {@link NonceUtil} must use the CONFIGURED key.
 *
 * <p>Regression: the class has a no-arg constructor (tests) next to the {@code @Value}
 * constructor. Without {@code @Autowired} on the latter, Spring picks the no-arg one, so every
 * deployment ran on an ephemeral per-pod key no matter what {@code auth.nonce.encryption-key}
 * held. Symptom in prod on 2026-09-15: {@code NONCE_ENCRYPTION_KEY} present in the pod, the
 * "encryption-key is not set" warning still logged, and a Stripe webhook landing on the other
 * replica unable to decode the checkout nonce.
 *
 * <p>Two instances built from the same key must decode each other's nonces: that is exactly
 * what two replicas sharing {@code NONCE_ENCRYPTION_KEY} need, and exactly what an ephemeral
 * key breaks.
 */
@DisplayName("NonceUtil bean uses the configured auth.nonce.encryption-key")
class NonceUtilBeanWiringTest {

    private static final String KEY = "shared-key-for-all-replicas-2026";

    @Test
    @DisplayName("a nonce generated by the Spring bean decodes on another instance configured with the same key")
    void beanUsesTheConfiguredKey() {
        new ApplicationContextRunner()
                .withPropertyValues("auth.nonce.encryption-key=" + KEY)
                .withUserConfiguration(NonceUtil.class)
                .run(context -> {
                    NonceUtil bean = context.getBean(NonceUtil.class);
                    String nonce = bean.generateNonce(121L);

                    // A second "replica" with the same configured key, and no shared cache.
                    NonceUtil otherReplica = new NonceUtil(KEY);
                    assertThat(otherReplica.decodeNonce(nonce))
                            .as("pre-fix the bean ignored the property and used an ephemeral key")
                            .isEqualTo(121L);
                });
    }

    @Test
    @DisplayName("with no key configured the bean still starts (ephemeral key, warning logged)")
    void beanStartsWithoutAKey() {
        new ApplicationContextRunner()
                .withUserConfiguration(NonceUtil.class)
                .run(context -> {
                    NonceUtil bean = context.getBean(NonceUtil.class);
                    assertThat(bean.decodeNonce(bean.generateNonce(7L))).isEqualTo(7L);
                });
    }
}
