#!/bin/sh
# LiveContext CE - Entrypoint with auto-generated encryption keys
# On first boot, generates random CREDENTIAL_ENCRYPTION_PASSWORD and SALT,
# persists them to /app/data/keys/encryption.env so they survive container restarts.
# If the user explicitly sets these vars (non-default values), those take priority.
# On upgrade from a pre-auto-gen version, preserves the existing keys to avoid
# breaking previously encrypted credentials.

set -e

KEYS_DIR="/app/data/keys"
ENCRYPTION_ENV="$KEYS_DIR/encryption.env"

DEFAULT_PASSWORD="change""me"
DEFAULT_PASSWORD_ALT="${DEFAULT_PASSWORD}-in-production"
DEFAULT_SALT="deadbeef""deadbeef"
DEFAULT_CLOUD_LINK_ENCRYPTION_KEY="change-me-in-""production"

generate_password() {
  # 48 random bytes -> base64 (64 chars)
  head -c 48 /dev/urandom | base64 | tr -d '\n'
}

generate_salt() {
  # 16 random bytes -> 32 hex chars (Spring Security requires hex-encoded salt)
  head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n'
}

generate_hmac_key() {
  # 32 random bytes -> base64 (44 chars, including padding)
  head -c 32 /dev/urandom | base64 | tr -d '\n'
}

is_default_password() {
  [ "$1" = "$DEFAULT_PASSWORD" ] || [ "$1" = "$DEFAULT_PASSWORD_ALT" ] || [ -z "$1" ]
}

is_default_salt() {
  [ "$1" = "$DEFAULT_SALT" ] || [ -z "$1" ]
}

is_default_cloud_link_encryption_key() {
  [ "$1" = "$DEFAULT_CLOUD_LINK_ENCRYPTION_KEY" ] || [ -z "$1" ]
}

# Check if this volume was used before (JWT keys or other files exist).
# Split into two checks - BusyBox ls fails if ANY glob has zero matches.
is_existing_install() {
  ls "$KEYS_DIR"/*.pem >/dev/null 2>&1 || ls "$KEYS_DIR"/*.key >/dev/null 2>&1
}

read_persisted_var() {
  VAR_NAME="$1"
  if [ -f "$ENCRYPTION_ENV" ]; then
    grep "^export ${VAR_NAME}=" "$ENCRYPTION_ENV" 2>/dev/null | tail -n 1 | cut -d= -f2-
  fi
}

ensure_ip_hash_key() {
  if [ -n "$CLOUD_LINK_IP_HASH_KEY_V1" ] && [ -z "$IP_HASH_HMAC_KEY_V1" ]; then
    IP_HASH_HMAC_KEY_V1="$CLOUD_LINK_IP_HASH_KEY_V1"
  fi

  if [ -z "$IP_HASH_HMAC_KEY_V1" ]; then
    PERSISTED_IP_HASH_KEY="$(read_persisted_var IP_HASH_HMAC_KEY_V1)"
    if [ -n "$PERSISTED_IP_HASH_KEY" ]; then
      IP_HASH_HMAC_KEY_V1="$PERSISTED_IP_HASH_KEY"
    fi
  fi

  if [ -z "$IP_HASH_HMAC_KEY_V1" ]; then
    echo "[CE-Security] Generating Cloud Link IP hash HMAC key..."
    IP_HASH_HMAC_KEY_V1="$(generate_hmac_key)"
    if [ ! -f "$ENCRYPTION_ENV" ]; then
      cat > "$ENCRYPTION_ENV" <<EOF
# Auto-generated by LiveContext CE on first boot - do not delete.
export IP_HASH_HMAC_KEY_V1=$IP_HASH_HMAC_KEY_V1
EOF
    elif ! grep -q "^export IP_HASH_HMAC_KEY_V1=" "$ENCRYPTION_ENV" 2>/dev/null; then
      cat >> "$ENCRYPTION_ENV" <<EOF
export IP_HASH_HMAC_KEY_V1=$IP_HASH_HMAC_KEY_V1
EOF
    fi
    chmod 600 "$ENCRYPTION_ENV"
  fi

  export IP_HASH_HMAC_KEY_V1
  export CLOUD_LINK_IP_HASH_KEY_V1="$IP_HASH_HMAC_KEY_V1"

  if [ -n "$IP_HASH_HMAC_KEY_V2" ]; then
    export CLOUD_LINK_IP_HASH_KEY_V2="$IP_HASH_HMAC_KEY_V2"
  fi
  if [ -n "$KEY_HMAC_CURRENT_VERSION" ]; then
    export CLOUD_LINK_IP_HASH_CURRENT_VERSION="$KEY_HMAC_CURRENT_VERSION"
  fi
}

ensure_cloud_link_encryption_key() {
  if ! is_default_cloud_link_encryption_key "$CLOUD_LINK_ENCRYPTION_KEY"; then
    export CLOUD_LINK_ENCRYPTION_KEY
    return
  fi

  PERSISTED_CLOUD_LINK_ENCRYPTION_KEY="$(read_persisted_var CLOUD_LINK_ENCRYPTION_KEY)"
  if [ -n "$PERSISTED_CLOUD_LINK_ENCRYPTION_KEY" ]; then
    CLOUD_LINK_ENCRYPTION_KEY="$PERSISTED_CLOUD_LINK_ENCRYPTION_KEY"
  else
    echo "[CE-Security] Generating Cloud Link encryption key..."
    CLOUD_LINK_ENCRYPTION_KEY="$(generate_hmac_key)"
    if [ ! -f "$ENCRYPTION_ENV" ]; then
      cat > "$ENCRYPTION_ENV" <<EOF
# Auto-generated by LiveContext CE on first boot - do not delete.
export CLOUD_LINK_ENCRYPTION_KEY=$CLOUD_LINK_ENCRYPTION_KEY
EOF
    elif ! grep -q "^export CLOUD_LINK_ENCRYPTION_KEY=" "$ENCRYPTION_ENV" 2>/dev/null; then
      cat >> "$ENCRYPTION_ENV" <<EOF
export CLOUD_LINK_ENCRYPTION_KEY=$CLOUD_LINK_ENCRYPTION_KEY
EOF
    fi
    chmod 600 "$ENCRYPTION_ENV"
  fi

  export CLOUD_LINK_ENCRYPTION_KEY
}

# --- Key resolution logic ---

CUSTOM_PASSWORD=false
CUSTOM_SALT=false
! is_default_password "$CREDENTIAL_ENCRYPTION_PASSWORD" && CUSTOM_PASSWORD=true
! is_default_salt "$CREDENTIAL_ENCRYPTION_SALT" && CUSTOM_SALT=true

if [ "$CUSTOM_PASSWORD" = true ] && [ "$CUSTOM_SALT" = true ]; then
  # User explicitly provided strong values for both - use them
  echo "[CE-Security] Using user-provided encryption keys."

elif [ "$CUSTOM_PASSWORD" = true ] || [ "$CUSTOM_SALT" = true ]; then
  # User customized only one of the two - warn but respect both values as given
  echo "[CE-Security] WARNING: Only one of PASSWORD/SALT is custom, the other is a default."
  echo "[CE-Security] For full security, set BOTH CREDENTIAL_ENCRYPTION_PASSWORD and"
  echo "[CE-Security] CREDENTIAL_ENCRYPTION_SALT in your .env file."
  echo "[CE-Security] Proceeding with the provided values."

elif [ -f "$ENCRYPTION_ENV" ]; then
  # Previously generated/persisted keys exist on the volume - reload them
  if grep -q "CREDENTIAL_ENCRYPTION_PASSWORD=" "$ENCRYPTION_ENV" 2>/dev/null; then
    echo "[CE-Security] Loading encryption keys from $ENCRYPTION_ENV"
    . "$ENCRYPTION_ENV"
    export CREDENTIAL_ENCRYPTION_PASSWORD CREDENTIAL_ENCRYPTION_SALT
  else
    echo "[CE-Security] WARNING: $ENCRYPTION_ENV exists but appears corrupted."
    echo "[CE-Security] Cannot determine encryption keys. The application will start"
    echo "[CE-Security] with the keys from environment/defaults. If credentials were"
    echo "[CE-Security] encrypted with different keys, they will be unreadable."
  fi

elif is_existing_install; then
  # UPGRADE PATH: Volume has data from a previous version that didn't have auto-gen.
  # Credentials may already be encrypted with the current (default) keys.
  # Persist them as-is to avoid breaking existing data.
  echo "[CE-Security] Upgrade detected - existing installation found."
  echo "[CE-Security] Preserving current encryption keys to protect existing credentials."

  cat > "$ENCRYPTION_ENV" <<EOF
# Preserved from pre-auto-gen installation during upgrade.
# These may be default keys. To rotate to strong keys, you must:
#   1. Export/backup all credentials
#   2. Delete this file and the volume: docker volume rm livecontext_keys
#   3. Restart - new keys will be generated
#   4. Re-enter all credentials
export CREDENTIAL_ENCRYPTION_PASSWORD=${CREDENTIAL_ENCRYPTION_PASSWORD:-$DEFAULT_PASSWORD}
export CREDENTIAL_ENCRYPTION_SALT=${CREDENTIAL_ENCRYPTION_SALT:-$DEFAULT_SALT}
EOF
  chmod 600 "$ENCRYPTION_ENV"

  echo ""
  echo "================================================================="
  echo "  NOTICE: Your encryption keys have been preserved from upgrade."
  echo "  If these are default keys, your credentials are not securely"
  echo "  encrypted. See $ENCRYPTION_ENV for rotation instructions."
  echo "================================================================="
  echo ""

else
  # Fresh install - generate strong random keys
  echo "[CE-Security] First boot detected - generating unique encryption keys..."
  NEW_PASSWORD=$(generate_password)
  NEW_SALT=$(generate_salt)

  cat > "$ENCRYPTION_ENV" <<EOF
# Auto-generated by LiveContext CE on first boot - do not delete.
# If you lose this file, all previously encrypted credentials become unreadable.
export CREDENTIAL_ENCRYPTION_PASSWORD=$NEW_PASSWORD
export CREDENTIAL_ENCRYPTION_SALT=$NEW_SALT
EOF
  chmod 600 "$ENCRYPTION_ENV"

  export CREDENTIAL_ENCRYPTION_PASSWORD="$NEW_PASSWORD"
  export CREDENTIAL_ENCRYPTION_SALT="$NEW_SALT"

  echo "[CE-Security] Unique encryption keys generated and saved to $ENCRYPTION_ENV"
fi

ensure_cloud_link_encryption_key
ensure_ip_hash_key

# --- Final safety warning ---

if is_default_password "$CREDENTIAL_ENCRYPTION_PASSWORD"; then
  echo ""
  echo "================================================================="
  echo "  WARNING: Using default encryption password!"
  echo "  Your stored credentials are NOT securely encrypted."
  echo "  To rotate to strong keys:"
  echo "    1. Export/note all your API keys and credentials"
  echo "    2. docker compose down"
  echo "    3. docker volume rm livecontext_keys"
  echo "    4. docker compose up -d"
  echo "    5. Re-enter your credentials in the UI"
  echo "================================================================="
  echo ""
fi

# --- Corporate/AV TLS interception support (runtime) ---
# Installs behind a TLS-intercepting proxy (corporate MITM, some antivirus)
# present a private root CA on every outbound HTTPS call. The JVM only trusts
# its bundled cacerts, so cloud calls (API-catalog sync, version check, cloud
# link) fail with PKIX errors. Mount the intercepting chain as .pem/.crt
# file(s) into /app/extra-ca (or point CE_EXTRA_CA_DIR elsewhere): each
# certificate is imported into a COPY of the JRE truststore at startup - the
# image itself stays generic. The build-time BUILD_EXTRA_CA arg only covers
# image builds; this is its runtime counterpart. Import failures warn and the
# app still boots (a bad cert file must not take the install down).

EXTRA_CA_DIR="${CE_EXTRA_CA_DIR:-/app/extra-ca}"
if ls "$EXTRA_CA_DIR"/*.pem >/dev/null 2>&1 || ls "$EXTRA_CA_DIR"/*.crt >/dev/null 2>&1; then
  RUNTIME_TRUSTSTORE="/tmp/ce-cacerts"
  JRE_CACERTS="${JAVA_HOME:-/opt/java/openjdk}/lib/security/cacerts"
  if [ -f "$JRE_CACERTS" ] && command -v keytool >/dev/null 2>&1; then
    cp "$JRE_CACERTS" "$RUNTIME_TRUSTSTORE" && chmod u+w "$RUNTIME_TRUSTSTORE"
    CA_INDEX=0
    for ca_file in "$EXTRA_CA_DIR"/*.pem "$EXTRA_CA_DIR"/*.crt; do
      [ -f "$ca_file" ] || continue
      # A file may carry a whole chain (root + intermediates): split per block.
      rm -f /tmp/ce-extra-ca-part-*.pem
      awk '/BEGIN CERTIFICATE/{n++} n{print > ("/tmp/ce-extra-ca-part-" n ".pem")}' "$ca_file"
      for part in /tmp/ce-extra-ca-part-*.pem; do
        [ -f "$part" ] || continue
        CA_INDEX=$((CA_INDEX+1))
        if keytool -importcert -noprompt -storepass changeit             -keystore "$RUNTIME_TRUSTSTORE" -alias "ce-extra-ca-$CA_INDEX"             -file "$part" >/dev/null 2>&1; then
          echo "[CE-TLS] Imported extra CA #$CA_INDEX from $ca_file"
        else
          echo "[CE-TLS] WARNING: failed to import a certificate from $ca_file (continuing)"
        fi
      done
    done
    rm -f /tmp/ce-extra-ca-part-*.pem
    JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.trustStore=$RUNTIME_TRUSTSTORE -Djavax.net.ssl.trustStorePassword=changeit"
    echo "[CE-TLS] Runtime truststore active: $RUNTIME_TRUSTSTORE"
  else
    echo "[CE-TLS] WARNING: extra CAs found in $EXTRA_CA_DIR but no JRE cacerts/keytool - skipping"
  fi
fi

# --- Launch the application ---

exec java $JAVA_OPTS -jar /app/app.jar --spring.profiles.active=ce
