package com.apimarketplace.orchestrator.services.impl;

import com.apimarketplace.orchestrator.domain.ToolRef;
import com.apimarketplace.orchestrator.services.interfaces.ExecutionResult;
import com.apimarketplace.orchestrator.services.interfaces.ToolsGateway;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Mock implementation of ToolsGateway that returns example_jsonb from catalog service.
 *
 * BREAKING CHANGE: This implementation no longer generates random mock data.
 * Instead, it fetches the real example_jsonb from the tool_responses table
 * in the catalog service and returns it as the mock response.
 */
@Service
@ConditionalOnProperty(name = "orchestrator.mock.enabled", havingValue = "true")
public class MockToolsGateway implements ToolsGateway {

    private static final Logger logger = LoggerFactory.getLogger(MockToolsGateway.class);

    private final RestTemplate restTemplate;
    private final ObjectMapper objectMapper;
    private final String catalogBaseUrl;

    public MockToolsGateway(
            RestTemplate restTemplate,
            ObjectMapper objectMapper,
            @Value("${orchestrator.catalog.base-url:http://localhost:8081}") String catalogBaseUrl) {
        this.restTemplate = restTemplate;
        this.objectMapper = objectMapper;
        this.catalogBaseUrl = catalogBaseUrl;
    }

    @Override
    public ExecutionResult simulateTool(ToolRef tool, Map<String, Object> input, String tenantId) {
        return executeMockFromCatalog(tool, input, tenantId, true);
    }

    @Override
    public ExecutionResult executeTool(ToolRef tool, Map<String, Object> input, String tenantId) {
        return executeMockFromCatalog(tool, input, tenantId, false);
    }

    /**
     * Fetches the example_jsonb from catalog service and returns it as mock response.
     * Supports forced error via special input parameter "__force_error": true.
     *
     * For simple test slugs (no "/" separator, e.g., "s1", "s2"), skips the catalog
     * call entirely and returns the fallback response directly. This avoids noisy
     * "Tool not found" warnings in the catalog service logs during E2E tests.
     */
    private ExecutionResult executeMockFromCatalog(ToolRef tool, Map<String, Object> input, String tenantId, boolean simulation) {
        // Force error mechanism for E2E testing: if input contains "__force_error": true, return FAILURE
        if (input != null && Boolean.TRUE.equals(input.get("__force_error"))) {
            String errorMsg = (String) input.getOrDefault("__error_message", "Forced mock error for testing");
            logger.info("MockToolsGateway: Forcing error for tool {} - {}",
                tool != null ? tool.toolId() : "null", errorMsg);
            return new ExecutionResult(
                false,
                Map.of("error", errorMsg, "mock", true),
                List.of(Map.of("type", "forced_error", "message", errorMsg)),
                List.of()
            );
        }

        String toolId = tool != null ? tool.toolId() : null;

        if (toolId == null || toolId.isBlank()) {
            logger.error("MockToolsGateway: toolId is null or empty");
            return new ExecutionResult(
                false,
                Map.of(),
                List.of(Map.of("type", "mock_error", "message", "Tool ID is required")),
                List.of()
            );
        }

        // Simple test slugs (no "/", e.g., "s1", "s2") are auto-generated by WorkflowPlanBuilder.
        // No point calling the catalog - just return the fallback directly.
        if (!toolId.contains("/")) {
            logger.debug("MockToolsGateway: Simple test slug '{}', returning fallback directly", toolId);
            return createFallbackResponse(toolId, simulation, "Test slug - catalog lookup skipped");
        }

        try {
            logger.info("MockToolsGateway: Fetching mock response for tool {} from catalog service", toolId);

            // Call catalog service to get the default tool response using slug-based endpoint.
            // toolId is a slug (e.g. "apiSlug/toolSlug"), NOT a UUID.
            String url = catalogBaseUrl + "/api/tool-responses/tool/" + toolId + "/default";
            ToolResponseDto response = restTemplate.getForObject(url, ToolResponseDto.class);

            if (response == null) {
                logger.warn("MockToolsGateway: No default response found for tool {}", toolId);
                return createFallbackResponse(toolId, simulation, "No mock response configured for this tool");
            }

            // Parse example_jsonb and return it as the mock output
            String exampleJsonb = response.getExampleJsonb();
            if (exampleJsonb == null || exampleJsonb.isBlank()) {
                logger.warn("MockToolsGateway: example_jsonb is empty for tool {}", toolId);
                return createFallbackResponse(toolId, simulation, "No example_jsonb configured for this tool");
            }

            // Parse the JSON to a Map or List
            Object parsedExample = objectMapper.readValue(exampleJsonb, Object.class);

            // Build the output map
            Map<String, Object> output = new LinkedHashMap<>();
            output.put("tool_id", toolId);
            output.put("mock", true);
            output.put("simulation", simulation);
            output.put("http_status", response.getStatusCode() != null ? response.getStatusCode() : 200);

            // Flatten the parsed example into output if it's a Map, otherwise put it as "data"
            if (parsedExample instanceof Map<?, ?> parsedMap) {
                for (Map.Entry<?, ?> entry : parsedMap.entrySet()) {
                    if (entry.getKey() instanceof String key) {
                        output.put(key, entry.getValue());
                    }
                }
            } else {
                // If it's an array or primitive, put it under "data" key
                output.put("data", parsedExample);
            }

            logger.info("MockToolsGateway: Successfully returned mock response for tool {}", toolId);

            return new ExecutionResult(
                true,
                output,
                List.of(),
                List.of()
            );

        } catch (Exception e) {
            logger.warn("MockToolsGateway: Cannot fetch mock response for tool {} ({}), using fallback", toolId, e.getMessage());
            return createFallbackResponse(toolId, simulation, "Catalog unavailable: " + e.getMessage());
        }
    }

    /**
     * Creates a fallback response when no mock data is available.
     */
    private ExecutionResult createFallbackResponse(String toolId, boolean simulation, String reason) {
        Map<String, Object> output = new LinkedHashMap<>();
        output.put("tool_id", toolId);
        output.put("mock", true);
        output.put("simulation", simulation);
        output.put("http_status", 200);
        output.put("_warning", reason);
        output.put("_fallback", true);

        return new ExecutionResult(
            true,
            output,
            List.of(),
            List.of()
        );
    }

    /**
     * DTO to receive tool response from catalog service.
     */
    private static class ToolResponseDto {
        private String id;
        private String toolId;
        private String name;
        private String description;
        private String example;
        private String exampleJsonb;
        private String structureSkeleton;
        private Integer statusCode;
        private Boolean isDefault;
        private Boolean isActive;

        // Getters
        public String getId() { return id; }
        public String getToolId() { return toolId; }
        public String getName() { return name; }
        public String getDescription() { return description; }
        public String getExample() { return example; }
        public String getExampleJsonb() { return exampleJsonb; }
        public String getStructureSkeleton() { return structureSkeleton; }
        public Integer getStatusCode() { return statusCode; }
        public Boolean getIsDefault() { return isDefault; }
        public Boolean getIsActive() { return isActive; }

        // Setters for Jackson
        public void setId(String id) { this.id = id; }
        public void setToolId(String toolId) { this.toolId = toolId; }
        public void setName(String name) { this.name = name; }
        public void setDescription(String description) { this.description = description; }
        public void setExample(String example) { this.example = example; }
        public void setExampleJsonb(String exampleJsonb) { this.exampleJsonb = exampleJsonb; }
        public void setStructureSkeleton(String structureSkeleton) { this.structureSkeleton = structureSkeleton; }
        public void setStatusCode(Integer statusCode) { this.statusCode = statusCode; }
        public void setIsDefault(Boolean isDefault) { this.isDefault = isDefault; }
        public void setIsActive(Boolean isActive) { this.isActive = isActive; }

        // Jackson property aliases
        @com.fasterxml.jackson.annotation.JsonProperty("example_jsonb")
        public void setExampleJsonbAlias(String exampleJsonb) { this.exampleJsonb = exampleJsonb; }

        @com.fasterxml.jackson.annotation.JsonProperty("structure_skeleton")
        public void setStructureSkeletonAlias(String structureSkeleton) { this.structureSkeleton = structureSkeleton; }

        @com.fasterxml.jackson.annotation.JsonProperty("status_code")
        public void setStatusCodeAlias(Integer statusCode) { this.statusCode = statusCode; }

        @com.fasterxml.jackson.annotation.JsonProperty("is_default")
        public void setIsDefaultAlias(Boolean isDefault) { this.isDefault = isDefault; }

        @com.fasterxml.jackson.annotation.JsonProperty("is_active")
        public void setIsActiveAlias(Boolean isActive) { this.isActive = isActive; }

        @com.fasterxml.jackson.annotation.JsonProperty("tool_id")
        public void setToolIdAlias(String toolId) { this.toolId = toolId; }
    }
}
