package com.apimarketplace.orchestrator.archunit;

import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.domain.JavaConstructor;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.core.importer.ImportOption;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Structural guard: a Spring-managed bean that declares MORE THAN ONE constructor and NO
 * no-argument constructor MUST mark exactly one of them {@code @Autowired}.
 *
 * <p><b>Why this exists.</b> Spring only auto-detects an injection constructor when the class
 * declares exactly ONE. With two or more candidates and no {@code @Autowired}, it does not pick
 * the widest or the first: it falls back to the no-argument constructor. A bean that HAS one is
 * therefore safe, which is why the rule below tests for its absence rather than simply counting
 * constructors. A bean that has none takes collaborators through every candidate, so the fallback
 * finds nothing and the whole application context fails to start with
 * {@code BeanInstantiationException: No default constructor found}.
 *
 * <p>The narrower condition is deliberate. A first draft of this rule flagged any bean with two or
 * more constructors and immediately produced three false positives ({@code NodePolicyRunner},
 * {@code PistonClient}, {@code CloudBrowserAgentLlmRelayClient}), each of which declares a no-arg
 * constructor and each of which has been starting in production for months. A guard that cries
 * wolf on working code gets suppressed, and a suppressed guard is not a guard.
 *
 * <p>The failure mode is what makes this worth a guard. It compiles. Every unit test that calls
 * the constructor directly stays green, including the test that motivated adding the second
 * constructor in the first place. Nothing goes red until a real context boots, which in this
 * repository means the service simply does not come up in the environment it was deployed to.
 *
 * <p>This was introduced live on 2026-08-19 by the LC-064 split fan-out ceiling work: a
 * package-private "test seam" constructor was added next to the public one on the
 * {@code @Service}-annotated {@code SplitNodeExecutor}, so that a test could exercise the ceiling
 * without building a 10,000-element list. Both constructors were correct in isolation. Together,
 * and without the annotation, they would have taken every orchestrator replica down on the next
 * deploy.
 *
 * <p><b>Scope.</b> Orchestrator production classes only. ArchUnit sees the classpath of the module
 * it runs in, so a sibling service needs its own copy of this rule rather than an entry here: a
 * cross-service allow-list would be false reassurance, which is the same reasoning recorded on
 * {@link AgentListEnvelopeAdoptionTest}.
 */
@DisplayName("Spring constructor resolution - a multi-constructor bean must name its injection point")
class SpringConstructorResolutionInvariantTest {

    /**
     * Stereotypes that make Spring instantiate the class itself. A class Spring never constructs
     * (a DTO, a value object, a hand-built collaborator) may declare as many constructors as it
     * likes, so the rule deliberately does not look at those.
     */
    private static final List<String> BEAN_STEREOTYPES = List.of(
            "org.springframework.stereotype.Service",
            "org.springframework.stereotype.Component",
            "org.springframework.stereotype.Repository",
            "org.springframework.stereotype.Controller",
            "org.springframework.web.bind.annotation.RestController");

    private static final String AUTOWIRED = "org.springframework.beans.factory.annotation.Autowired";

    /**
     * Lombok's {@code @RequiredArgsConstructor} and friends generate exactly one constructor, so a
     * class carrying one cannot be ambiguous unless it ALSO hand-writes another. The importer sees
     * the generated bytecode, so no special case is needed here: this list documents that the
     * absence of a special case is deliberate rather than an oversight.
     */
    private static JavaClasses productionClasses;

    @BeforeAll
    static void importProductionClasses() {
        productionClasses = new ClassFileImporter()
                .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
                .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_JARS)
                .importPackages("com.apimarketplace.orchestrator");
    }

    @Test
    @DisplayName("the importer actually sees orchestrator beans, so a pass cannot be vacuous")
    void theImportIsNotEmpty() {
        long beanCount = productionClasses.stream().filter(this::isSpringBean).count();

        assertThat(beanCount)
                .describedAs("no Spring beans were imported from com.apimarketplace.orchestrator, "
                        + "so every assertion below would pass without examining anything. "
                        + "Check the import options before trusting a green run.")
                .isGreaterThan(50);
    }

    @Test
    @DisplayName("a bean with several constructors and no no-arg fallback names one @Autowired")
    void multiConstructorBeansNameTheirInjectionPoint() {
        List<String> offenders = new ArrayList<>();

        for (JavaClass candidate : productionClasses) {
            if (!isSpringBean(candidate)) {
                continue;
            }
            List<JavaConstructor> declared = new ArrayList<>(candidate.getConstructors());
            if (declared.size() < 2) {
                continue;
            }
            boolean hasNoArgFallback = declared.stream()
                    .anyMatch(constructor -> constructor.getRawParameterTypes().isEmpty());
            if (hasNoArgFallback) {
                continue;
            }
            long annotated = declared.stream()
                    .filter(constructor -> constructor.isAnnotatedWith(AUTOWIRED))
                    .count();
            if (annotated != 1) {
                offenders.add(String.format(
                        "%s declares %d constructors, none of them no-arg, and %d are @Autowired "
                                + "(exactly 1 is required)",
                        candidate.getName(), declared.size(), annotated));
            }
        }

        assertThat(offenders)
                .describedAs("Spring cannot choose between several constructors on its own. It does "
                        + "NOT take the widest or the first: it falls back to the no-argument "
                        + "constructor, and these classes do not have one, so the context fails to "
                        + "start with 'No default constructor found'. This compiles, and every "
                        + "unit test that calls the constructor directly stays green, so nothing "
                        + "catches it before the service fails to come up. Mark the constructor "
                        + "Spring should use with @Autowired, or delete the extra constructor and "
                        + "give the test a static factory method instead.")
                .isEmpty();
    }

    @Test
    @DisplayName("the rule is not vacuous: it would catch the SplitNodeExecutor shape")
    void theRuleFiresOnTheShapeThatMotivatedIt() {
        JavaClass splitNodeExecutor = productionClasses.get(
                "com.apimarketplace.orchestrator.execution.v2.split.SplitNodeExecutor");

        List<JavaConstructor> declared = new ArrayList<>(splitNodeExecutor.getConstructors());

        assertThat(declared)
                .describedAs("SplitNodeExecutor is the class that motivated this rule. If it ever "
                        + "drops back to a single constructor the rule stops being exercised here, "
                        + "which is fine, but this assertion should then be repointed at whatever "
                        + "class still carries the multi-constructor shape.")
                .hasSizeGreaterThan(1);
        assertThat(declared.stream().anyMatch(c -> c.getRawParameterTypes().isEmpty()))
                .describedAs("SplitNodeExecutor must not gain a no-arg constructor: it takes real "
                        + "collaborators, and a no-arg fallback would let Spring build one with "
                        + "null fields instead of failing loudly.")
                .isFalse();
        assertThat(declared.stream().filter(c -> c.isAnnotatedWith(AUTOWIRED)).count())
                .describedAs("Removing @Autowired here fails the orchestrator context at startup. "
                        + "It was missing on 2026-08-19 and only an audit caught it.")
                .isEqualTo(1);
    }

    private boolean isSpringBean(JavaClass candidate) {
        if (candidate.isInterface() || candidate.isEnum() || candidate.isRecord()) {
            return false;
        }
        return BEAN_STEREOTYPES.stream().anyMatch(candidate::isMetaAnnotatedWith);
    }
}
