'use client';

import React, { useState, useCallback, useEffect } from 'react';
import { ChevronLeft, ChevronRight, Send, Settings, Code, TestTube, DollarSign, CheckCircle, AlertCircle, Info, Binary, Sparkles, User } from 'lucide-react';
import Toast from '@/components/Toast';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { unifiedApiService } from '@/lib/api/unified-api-service';
import { apiClient } from '@/lib/api/api-client';
import { usePersistentState } from '@/hooks/usePersistentState';
import { useTranslations } from 'next-intl';
import { useAuthGuard } from '@/hooks/useAuthGuard';
import { useAuth } from '@/lib/providers/smart-providers';

import StepIndicator from './components/StepIndicator';
import Step1 from './components/Step1';
import Step2 from './components/Step2';
import Step3 from './components/Step3';
import Step4 from './components/Step4';
import Confirmation from './components/confirmation';
import ApiTemplatesSection from './components/ApiTemplatesSection';
import {
  predefinedTools,
  defaultToolCategories,
  predefinedToolNames
} from './constants';
import { generateCurlCommand } from './utils';
import { apiTemplates } from './templates/apiTemplates';
import { useDynamicCategories } from './dynamicConstants';
import { McpTool, ApiConfig, MonetizationConfig } from './types';
// import { generateId } from './utils'; // REMOVED: IDs generated by backend
import { useCategoriesContext } from '@/lib/hooks/smart-hooks-complete';

const createDefaultApiConfig = (): ApiConfig => ({
  baseUrl: '',
  healthcheckEndpoint: '/health',
  authorization: {
    type: 'apisecret',
    headerName: 'X-MCPW-PROXY-SECRET',
    headerValue: '',
    description: 'API proxy secret required for authentication'
  },
  visibility: 'public'
});

const createDefaultMonetizationConfig = (): MonetizationConfig => ({
  pricing: 'freemium',
  rateLimit: {
    requests: 1000,
    period: 'hour'
  },
  monetization: {
    freeRequests: 1000,
    tokenValue: 1
  },
  freeRequestsPerUser: 1000,
  selectedPlans: {
    basic: true,
    pro: false,
    ultra: false,
    mega: false
  },
  hardLimitBasic: true,
  hardLimitPro: true,
  hardLimitUltra: true,
  hardLimitMega: true,
  priceBasic: 0,
  pricePro: 9.99,
  priceUltra: 29.99,
  priceMega: 99.99,
  quotaBasic: 1000,
  quotaPro: 10000,
  quotaUltra: 50000,
  quotaMega: 200000,
  rpsBasic: 10,
  rpsPro: 100,
  rpsUltra: 500,
  rpsMega: 1000,
  rpsPeriodBasic: 'minute',
  rpsPeriodPro: 'minute',
  rpsPeriodUltra: 'minute',
  rpsPeriodMega: 'minute',
  overusageCostBasic: 0.01,
  overusageCostPro: 0.008,
  overusageCostUltra: 0.005,
  overusageCostMega: 0.003,
  showPlansInfo: false,
  uniformToolPrice: 1,
  uniformToolPriceInDollars: 0.005,
  toolPricing: {},
  planTools: {
    basic: [],
    pro: [],
    ultra: [],
    mega: []
  },
  planAllToolsMode: {
    basic: false,
    pro: false,
    ultra: false,
    mega: false
  }
});

const MCP_STORAGE_KEYS = [
  'livecontext_currentStep',
  'livecontext_apiName',
  'livecontext_apiDescription',
  'livecontext_selectedCategory',
  'livecontext_selectedSubcategory',
  'livecontext_mcpTools',
  'livecontext_apiConfig',
  'livecontext_monetizationConfig',
  'livecontext_selectedCategoryId',
  'livecontext_selectedSubcategoryId'
];

export default function DevelopersPage() {
  const { isAuthenticated, isAuthChecking } = useAuthGuard();
  const { loginWithRedirect } = useAuth();
  const t = useTranslations('developers');
  const tSettings = useTranslations('settings');
  const { categories, subcategories } = useCategoriesContext();

  // Custom CSS styles for clean OpenAI style
  React.useEffect(() => {
    const style = document.createElement('style');
    style.textContent = `
      /* Styles HomePage for consistency */
      .bg-theme-primary {
        background-color: var(--bg-primary);
      }
      
      .bg-theme-secondary {
        background-color: var(--bg-secondary);
      }
      
      .bg-theme-tertiary {
        background-color: var(--bg-tertiary);
      }
      
      .text-theme-primary {
        color: var(--text-primary);
      }
      
      .text-theme-secondary {
        color: var(--text-secondary);
      }
      
      .border-theme {
        border-color: var(--border-color);
      }
      
      .shadow-theme {
        box-shadow: 0 4px 6px -1px var(--shadow-color);
      }
    `;
    document.head.appendChild(style);

    return () => {
      document.head.removeChild(style);
    };
  }, []);

  const [currentStep, setCurrentStep] = usePersistentState<number>(
    'livecontext_currentStep',
    1,
    {
      serializer: (value) => value.toString(),
      deserializer: (value) => {
        const parsed = parseInt(value, 10);
        if (Number.isNaN(parsed)) {
          return 1;
        }
        return parsed >= 1 && parsed <= 4 ? parsed : 1;
      }
    }
  );
  const [apiName, setApiName] = usePersistentState('livecontext_apiName', '');
  const [apiDescription, setApiDescription] = usePersistentState('livecontext_apiDescription', '');

  // State for API name validation
  const [apiNameValidation, setApiNameValidation] = useState({
    isValid: true,
    message: '',
    isChecking: false
  });

  const [selectedCategory, setSelectedCategory] = usePersistentState('livecontext_selectedCategory', '');
  const [selectedSubcategory, setSelectedSubcategory] = usePersistentState('livecontext_selectedSubcategory', '');
  const [mcpTools, setMcpTools] = usePersistentState<McpTool[]>(
    'livecontext_mcpTools',
    () => []
  );
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [notification, setNotification] = useState<{
    type: 'success' | 'error' | 'info';
    message: string;
    visible: boolean;
  } | null>(null);
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' | 'info' } | null>(null);
  const [step4Validation, setStep4Validation] = useState(true);
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null);

  // API configuration
  const [apiConfig, setApiConfig] = usePersistentState<ApiConfig>(
    'livecontext_apiConfig',
    createDefaultApiConfig,
    {
      deserializer: (value) => {
        try {
          return JSON.parse(value);
        } catch (error) {
          console.warn('Error loading API configuration:', error);
          return createDefaultApiConfig();
        }
      }
    }
  );

  // Monetization configuration (new separate state)
  const [monetizationConfig, setMonetizationConfig] = usePersistentState<MonetizationConfig>(
    'livecontext_monetizationConfig',
    createDefaultMonetizationConfig,
    {
      deserializer: (value) => {
        try {
          const parsed = JSON.parse(value);
          if (!parsed.planAllToolsMode) {
            parsed.planAllToolsMode = {
              basic: false,
              pro: false,
              ultra: false,
              mega: false
            };
          }
          return parsed;
        } catch (error) {
          console.warn('Error loading monetization configuration:', error);
          return createDefaultMonetizationConfig();
        }
      }
    }
  );


  // Function to display notifications
  const showNotification = useCallback((type: 'success' | 'error' | 'info', message: string) => {
    setNotification({ type, message, visible: true });

    // Auto-hide after 5 seconds
    setTimeout(() => {
      setNotification(null);
    }, 5000);
  }, []);

  // Toast functions (same as pricing page)
  const showToast = useCallback((message: string, type: 'success' | 'error' | 'info') => {
    setToast({ message, type });
  }, []);

  const closeToast = useCallback(() => {
    setToast(null);
  }, []);

  // Step configuration for StepIndicator
  const steps = [
    {
      id: 1,
      title: t('steps.basic.title'),
      description: t('steps.basic.description'),
      icon: () => <Settings className="w-5 h-5" />,
      status: (currentStep >= 1 ? (currentStep > 1 ? 'completed' : 'current') : 'upcoming') as 'completed' | 'current' | 'upcoming'
    },
    {
      id: 2,
      title: t('steps.api.title'),
      description: t('steps.api.description'),
      icon: () => <Code className="w-5 h-5" />,
      status: (currentStep >= 2 ? (currentStep > 2 ? 'completed' : 'current') : 'upcoming') as 'completed' | 'current' | 'upcoming'
    },
    {
      id: 3,
      title: t('steps.tools.title'),
      description: t('steps.tools.description'),
      icon: () => <TestTube className="w-5 h-5" />,
      status: (currentStep >= 3 ? (currentStep > 3 ? 'completed' : 'current') : 'upcoming') as 'completed' | 'current' | 'upcoming'
    },
    {
      id: 4,
      title: t('steps.monetization.title'),
      description: t('steps.monetization.description'),
      icon: () => <DollarSign className="w-5 h-5" />,
      status: (currentStep >= 4 ? (currentStep > 4 ? 'completed' : 'current') : 'upcoming') as 'completed' | 'current' | 'upcoming'
    }
  ];

  // Function to reset all test statuses when base URL changes
  const resetAllTestStatuses = useCallback(() => {
    setMcpTools(prev => prev.map(tool => ({
      ...tool,
      testStatus: undefined,
      testResult: undefined
    })));
  }, [setMcpTools]);

  // Function to update API configuration with test reset
  const updateApiConfig = useCallback((newConfig: ApiConfig) => {
    // If base URL changes, reset all test statuses
    if (newConfig.baseUrl !== apiConfig.baseUrl) {
      resetAllTestStatuses();
    }
    setApiConfig(newConfig);
  }, [apiConfig.baseUrl, resetAllTestStatuses, setApiConfig]);

  // Update tools included in plans when tools change
  const updatePlanTools = useCallback((tools: McpTool[]) => {
    // Ensure at least one tool is selected per plan
    const currentPlanTools = monetizationConfig.planTools;
    const updatedPlanTools = { ...currentPlanTools };

    Object.keys(updatedPlanTools).forEach(plan => {
      const planKey = plan as keyof typeof monetizationConfig.planTools;
      const currentTools = updatedPlanTools[planKey] || [];

      // If the plan has no tools or if its tools no longer exist, assign the first available tool
      if (currentTools.length === 0 || !tools.some(tool => currentTools.includes(tool.name))) {
        if (tools.length > 0) {
          updatedPlanTools[planKey] = [tools[0].name];
        } else {
          updatedPlanTools[planKey] = [];
        }
      }
    });

    setMonetizationConfig(prev => ({
      ...prev,
      planTools: updatedPlanTools
    }));
  }, [monetizationConfig.planTools, setMonetizationConfig]);

  // Wrapper for setMcpTools that automatically updates plan tools
  const setMcpToolsWithPlanUpdate = useCallback(
    (tools: McpTool[] | ((prev: McpTool[]) => McpTool[])) => {
      setMcpTools(prev => {
        const nextTools = typeof tools === 'function' ? tools(prev) : tools;
        updatePlanTools(nextTools);
        return nextTools;
      });
    },
    [setMcpTools, updatePlanTools]
  );

  // Function to apply template defaults
  const applyTemplate = useCallback((templateId: string) => {
    const template = apiTemplates.find(t => t.id === templateId);
    if (!template) return;

    const { defaults } = template;

    // Apply basic configuration
    setApiName(defaults.apiName);
    setApiDescription(defaults.apiDescription);
    setSelectedCategory(defaults.selectedCategory);
    setSelectedSubcategory(defaults.selectedSubcategory);

    // Apply API configuration
    const newApiConfig: ApiConfig = {
      baseUrl: defaults.baseUrl,
      healthcheckEndpoint: '/health',
      authorization: defaults.authorization as any,
      visibility: 'public'
    };
    setApiConfig(newApiConfig);

    // Apply monetization configuration
    const newMonetizationConfig: MonetizationConfig = {
      pricing: defaults.pricing as any,
      rateLimit: defaults.rateLimit as any,
      monetization: {
        freeRequests: defaults.rateLimit.requests,
        tokenValue: 1
      },
      selectedPlans: {
        basic: true,
        pro: false,
        ultra: false,
        mega: false
      },
      hardLimitBasic: true,
      hardLimitPro: true,
      hardLimitUltra: true,
      hardLimitMega: true,
      priceBasic: 9.99,
      pricePro: 29.99,
      priceUltra: 79.99,
      priceMega: 199.99,
      quotaBasic: 10000,
      quotaPro: 50000,
      quotaUltra: 200000,
      quotaMega: 1000000,
      rpsBasic: 10,
      rpsPro: 50,
      rpsUltra: 200,
      rpsMega: 1000,
      rpsPeriodBasic: 'minute' as const,
      rpsPeriodPro: 'minute' as const,
      rpsPeriodUltra: 'minute' as const,
      rpsPeriodMega: 'minute' as const,
      overusageCostBasic: 0.001,
      overusageCostPro: 0.0005,
      overusageCostUltra: 0.0002,
      overusageCostMega: 0.0001,
      showPlansInfo: false,
      uniformToolPrice: 1,
      uniformToolPriceInDollars: 0.005,
      toolPricing: {},
      freeRequestsPerUser: defaults.rateLimit.requests,
      planTools: {
        basic: [],
        pro: [],
        ultra: [],
        mega: []
      },
      planAllToolsMode: {
        basic: false,
        pro: false,
        ultra: false,
        mega: false
      }
    };
    setMonetizationConfig(newMonetizationConfig);

    // Apply MCP tools
    const mcpTools = defaults.tools.map((tool, index) => ({
      id: `tool_${index}`,
      name: tool.name,
      description: `Tool for ${tool.category} operations`,
      category: defaults.selectedCategory,
      subcategory: defaults.selectedSubcategory,
      toolCategory: tool.category,
      method: tool.method as 'GET' | 'POST' | 'PUT' | 'DELETE',
      endpoint: tool.endpoint,
      headers: [],
      parameters: [],
      pathParameters: [],
      queryParameters: [],
      response: {
        success: tool.response,
        error: { message: 'Error occurred' },
        description: 'Response from the API',
        type: tool.response.type as 'json' | 'binary' | 'text' | 'xml' | 'csv' | 'html'
      },
      pricing: defaults.pricing as any,
      rateLimit: `${defaults.rateLimit.requests} per ${defaults.rateLimit.period}`,
      status: 'draft' as const,
      testStatus: undefined,
      testResult: undefined
    }));
    setMcpToolsWithPlanUpdate(mcpTools);

    // Set selected template
    setSelectedTemplate(templateId);

    // Reset to step 1
    setCurrentStep(1);

    // Show success notification
    showToast(`Template "${template.name}" applied successfully!`, 'success');
  }, [setApiName, setApiDescription, setSelectedCategory, setSelectedSubcategory, setApiConfig, setMonetizationConfig, setMcpToolsWithPlanUpdate, setCurrentStep, showToast]);

  // Auto-select basic plan when pricing is set to "paid"
  useEffect(() => {
    if (monetizationConfig.pricing === 'paid' && (!monetizationConfig.selectedPlans || Object.values(monetizationConfig.selectedPlans).every(selected => !selected))) {
      setMonetizationConfig(prev => ({
        ...prev,
        selectedPlans: {
          basic: true,
          pro: false,
          ultra: false,
          mega: false
        }
      }));
    }
  }, [monetizationConfig.pricing, monetizationConfig.selectedPlans, setMonetizationConfig]);

  // Navigation between steps
  const nextStep = useCallback(() => {
    if (currentStep < 4) {
      const newStep = currentStep + 1;
      setCurrentStep(newStep);
    }
  }, [currentStep, setCurrentStep]);

  const prevStep = useCallback(() => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1);
    }
  }, [currentStep, setCurrentStep]);

  const goToStep = useCallback((step: number) => {
    if (step >= 1 && step <= 4) {
      setCurrentStep(step);
    }
  }, [setCurrentStep]);


  // Endpoint testing - Real HTTP request
  const testEndpoint = useCallback(async (index: number) => {
    setMcpTools(prev => {
      const newTools = [...prev];
      newTools[index] = {
        ...newTools[index],
        testStatus: 'pending'
      };
      return newTools;
    });

    const tool = mcpTools[index];
    const startTime = Date.now();

    try {

      // Build the full URL
      const baseUrl = apiConfig.baseUrl.replace(/\/$/, ''); // Remove trailing slash
      const endpoint = tool.endpoint.startsWith('/') ? tool.endpoint : `/${tool.endpoint}`;
      let fullUrl = `${baseUrl}${endpoint}`;

      // Replace path parameters
      if (tool.pathParameters) {
        tool.pathParameters.forEach(param => {
          if (param.name && param.example) {
            fullUrl = fullUrl.replace(`{${param.name}}`, encodeURIComponent(param.example));
          }
        });
      }

      // Add query parameters
      const queryParams = new URLSearchParams();
      if (tool.queryParameters) {
        tool.queryParameters.forEach(param => {
          if (param.name && param.example) {
            queryParams.append(param.name, param.example);
          }
        });
      }

      if (queryParams.toString()) {
        fullUrl += `?${queryParams.toString()}`;
      }

      // Build headers
      const headers: Record<string, string> = {};

      // Add custom headers
      if (tool.headers) {
        tool.headers.forEach(header => {
          if (header.name && header.value) {
            headers[header.name] = header.value;
          }
        });
      }

      // Add authorization header
      if (apiConfig.authorization.type !== 'none') {
        if (apiConfig.authorization.type === 'bearer') {
          const tokenValue = apiConfig.authorization.headerValue || '';
          if (tokenValue) {
            const cleanToken = tokenValue.startsWith('Bearer ') ? tokenValue.substring(7) : tokenValue;
            headers['Authorization'] = `Bearer ${cleanToken}`;
          }
        } else if (apiConfig.authorization.type === 'basic') {
          const username = apiConfig.authorization.username || '';
          const password = apiConfig.authorization.password || '';
          if (username && password) {
            headers['Authorization'] = `Basic ${btoa(`${username}:${password}`)}`;
          }
        } else if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
          headers[apiConfig.authorization.headerName] = apiConfig.authorization.headerValue;
        }
      }


      // Build request body
      let body: string | undefined;
      if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams) {
        const bodyObj: Record<string, any> = {};
        tool.bodyParams.forEach(param => {
          if (param.name && param.value) {
            bodyObj[param.name] = param.value;
          }
        });
        body = JSON.stringify(bodyObj);
        headers['Content-Type'] = 'application/json';
      }

      // Use the external proxy to avoid CORS issues
      const proxyData = await apiClient.post<{ status: number; statusText?: string; data?: any; headers?: Record<string, string> }>('/external-proxy', {
        url: fullUrl,
        method: tool.method,
        headers,
        body: body ? body : undefined,
        timeout: 10000
      });

      const responseTime = Date.now() - startTime;

      // Check if the external API call was successful
      if (proxyData.status >= 400) {
        throw new Error(`API error: ${proxyData.status} ${proxyData.statusText || 'Unknown error'}`);
      }

      // The proxy response contains the actual API response data
      const testResult = {
        status: proxyData.status,
        responseTime,
        data: proxyData.data,
        headers: proxyData.headers || {}
      };

      // Update tool with successful result
      setMcpTools(prev => {
        const newTools = [...prev];
        newTools[index] = {
          ...tool,
          testStatus: proxyData.status >= 200 && proxyData.status < 300 ? 'success' : 'error',
          testResult,
          response: (proxyData.status >= 200 && proxyData.status < 300) ? {
            ...tool.response,
            success: proxyData.data
          } : tool.response
        };
        return newTools;
      });

    } catch (error) {
      const responseTime = Date.now() - startTime;
      console.error('Test endpoint error:', error);

      const errorResult = {
        status: 0, // Network error
        responseTime,
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        data: {
          success: false,
          message: 'Network error or timeout',
          timestamp: new Date().toISOString(),
          endpoint: tool.endpoint,
          method: tool.method,
          debug: {
            requestId: `req_${Math.random().toString(36).substr(2, 9)}`,
            timestamp: new Date().toISOString(),
            userAgent: navigator.userAgent,
            error: error instanceof Error ? error.message : 'Unknown error'
          }
        }
      };

      // Update tool with error result
      setMcpTools(prev => {
        const newTools = [...prev];
        newTools[index] = {
          ...tool,
          testStatus: 'error',
          testResult: errorResult
        };
        return newTools;
      });
    }
  }, [mcpTools, apiConfig]);

  const testAllEndpoints = useCallback(() => {
    mcpTools.forEach((_, index) => {
      testEndpoint(index);
    });
  }, [mcpTools, testEndpoint]);

  // Utility function to handle different HTTP response types
  const parseResponse = async (response: Response, expectedType?: string): Promise<{ data: any; contentType: string; errorMessage: string; parsedData: any }> => {
    const contentType = response.headers.get('content-type') || '';
    let data: any = null;
    let errorMessage = response.statusText;
    let parsedData: any = null;

    try {
      if (contentType.includes('application/json') || expectedType === 'json') {
        // JSON response
        data = await response.json();
        parsedData = data;
        errorMessage = data.details || data.error || response.statusText;
      } else if (contentType.includes('text/html') || expectedType === 'html') {
        // HTML response
        const htmlResponse = await response.text();
        data = { html: htmlResponse };
        parsedData = { type: 'html', content: htmlResponse.substring(0, 500) + '...' };
        errorMessage = `HTML response received (${response.status})`;
      } else if (contentType.includes('text/plain') || expectedType === 'text') {
        // Simple text response
        const textResponse = await response.text();
        data = { text: textResponse };
        parsedData = { type: 'text', content: textResponse };
        errorMessage = textResponse || response.statusText;
      } else if (contentType.includes('text/csv') || expectedType === 'csv') {
        // CSV response
        const csvResponse = await response.text();
        data = { csv: csvResponse };
        parsedData = { type: 'csv', content: csvResponse.substring(0, 200) + '...' };
        errorMessage = 'CSV response received';
      } else if (contentType.includes('text/xml') || expectedType === 'xml') {
        // XML response
        const xmlResponse = await response.text();
        data = { xml: xmlResponse };
        parsedData = { type: 'xml', content: xmlResponse.substring(0, 200) + '...' };
        errorMessage = 'XML response received';
      } else if (contentType.includes('application/octet-stream') || contentType.includes('application/pdf') ||
        contentType.includes('image/') || contentType.includes('video/') || expectedType === 'binary') {
        // Binary response (file)
        const blob = await response.blob();
        data = { binary: blob };
        parsedData = {
          type: 'binary',
          size: blob.size,
          contentType: blob.type,
          filename: response.headers.get('content-disposition')?.split('filename=')[1] || 'file'
        };
        errorMessage = `File received (${blob.size} bytes, ${blob.type})`;
      } else {
        // Unknown content type or unspecified
        try {
          const textResponse = await response.text();
          if (textResponse) {
            data = { unknown: textResponse };
            parsedData = { type: 'unknown', content: textResponse.substring(0, 200) + '...' };
            errorMessage = textResponse;
          }
        } catch (textError) {
          console.error('🚨 Unable to read response as text:', textError);
          parsedData = { type: 'error', content: 'Unable to read response' };
        }
      }
    } catch (parseError) {
      console.error('🚨 Error parsing response:', parseError);
      errorMessage = 'Unable to read server response';
      parsedData = { type: 'error', content: 'Parsing error' };
    }

    return { data, contentType, errorMessage, parsedData };
  };

  // API submission
  const handleSubmit = useCallback(async (success: boolean = true) => {
    // Cette fonction est maintenant appelee depuis Confirmation.tsx apres la soumission
    // Elle gere seulement les reponses de test, pas la soumission principale


    if (!success) {
      console.error('❌ API submission failed - NO RESET, NO TEST SENDING');
      setIsSubmitting(false);
      showToast('API submission failed. Form was not reset.', 'error');
      return; // ⛔ ARReT TOTAL : rien ne se passe
    }


    // ✅ SEULEMENT SI SUCCESS : Send test responses asynchronously and handle loading
    const toolsWithTestResults = (mcpTools || []).filter(tool =>
      tool.testResult && tool.testStatus === 'success'
    );

    if (toolsWithTestResults.length > 0) {

      // Launch test response sending in background
      setTimeout(async () => {
        let completedTests = 0;
        let failedTests = 0;
        const totalTests = toolsWithTestResults.length;

        for (const tool of toolsWithTestResults) {
          try {
            const testResponseData = {
              toolName: tool.name,
              testResult: {
                status: tool.testResult.status,
                responseTime: tool.testResult.responseTime,
                data: tool.testResult.data,
                responseType: tool.response?.type || 'json'
              }
            };

            console.log(`📤 Asynchronous test response sending for ${tool.name}:`, {
              toolName: tool.name,
              status: tool.testResult.status,
              responseTime: tool.testResult.responseTime,
              responseType: tool.response?.type || 'json',
              dataSize: JSON.stringify(tool.testResult.data).length,
              dataPreview: typeof tool.testResult.data === 'string'
                ? tool.testResult.data.substring(0, 100) + (tool.testResult.data.length > 100 ? '...' : '')
                : 'Non-textual data'
            });

            // Send individual test response
            // TODO: Implement proper test results endpoint
            // const testResponse = await unifiedApiService.submitProductTestResults(testResponseData);

            console.log(`✅ Test response would be sent for ${tool.name} (endpoint not implemented)`);
            completedTests++;

            console.log(`📊 Progress: ${completedTests}/${totalTests} test responses sent (${failedTests} failures)`);

          } catch (error) {
            console.warn(`⚠️ Error sending test response for ${tool.name}:`, error);
            failedTests++;
          }
        }

        console.log('📊 === FINISHED ASYNC SENDING OF TEST RESPONSES ===');

        // All tests are complete, stop loading
        setIsSubmitting(false);

        // Check if ALL tests succeeded
        if (failedTests === 0) {
          // All tests succeeded, reset form
          showToast('All files were sent successfully! Resetting form...', 'success');
          redirectToStep1AndReset();
        } else {
          // Some tests failed, don't reset
          showToast(`${failedTests} file(s) could not be sent. Form was not reset.`, 'error');
          // User stays on step 5 to retry
        }

      }, 100); // 100ms delay to not block main response
    } else {
      console.log('ℹ️ No test response to send');
      // No tests to send, stop loading immediately
      setIsSubmitting(false);
      showToast('API submitted successfully!', 'success');
      redirectToStep1AndReset();
    }
  }, [mcpTools]);

  // Category change handling
  const handleCategoryChange = useCallback((category: string) => {
    setSelectedCategory(category);
    setSelectedSubcategory('');
  }, [setSelectedCategory, setSelectedSubcategory]);

  const handleSubcategoryChange = useCallback((subcategory: string) => {
    setSelectedSubcategory(subcategory);
  }, [setSelectedSubcategory]);




  // Function to redirect to step 1 and reset form
  const redirectToStep1AndReset = useCallback(() => {
    if (typeof window !== 'undefined') {
      MCP_STORAGE_KEYS.forEach(key => localStorage.removeItem(key));
    }

    setApiName('');
    setApiDescription('');
    setSelectedCategory('');
    setSelectedSubcategory('');
    setSelectedTemplate(null);
    setStep4Validation(true);
    setApiConfig(createDefaultApiConfig());
    setMonetizationConfig(createDefaultMonetizationConfig());
    setMcpToolsWithPlanUpdate([]);
    setCurrentStep(1);
    showToast('Form reset! You can now create a new API.', 'info');
  }, [setApiName, setApiDescription, setSelectedCategory, setSelectedSubcategory, setSelectedTemplate, setStep4Validation, setApiConfig, setMonetizationConfig, setMcpToolsWithPlanUpdate, setCurrentStep, showToast]);


  // Step rendering
  const renderCurrentStep = () => {
    switch (currentStep) {
      case 1:
        return (
          <Step1
            apiName={apiName}
            setApiName={setApiName}
            selectedCategory={selectedCategory}
            setSelectedCategory={handleCategoryChange}
            selectedSubcategory={selectedSubcategory}
            apiNameValidation={apiNameValidation}
            setApiNameValidation={setApiNameValidation}
            setSelectedSubcategory={handleSubcategoryChange}
            apiDescription={apiDescription}
            setApiDescription={setApiDescription}
            predefinedTools={predefinedTools}
            setMcpTools={setMcpToolsWithPlanUpdate}
            setApiConfig={updateApiConfig}
          />
        );
      case 2:
        return (
          <Step2
            apiConfig={apiConfig}
            setApiConfig={updateApiConfig}
            apiName={apiName}
          />
        );
      case 3:
        return (
          <Step3
            mcpTools={mcpTools}
            setMcpTools={setMcpToolsWithPlanUpdate}
            apiConfig={apiConfig}
            setApiConfig={updateApiConfig}
            apiName={apiName}
            selectedCategory={selectedCategory}
            selectedSubcategory={selectedSubcategory}
            testEndpoint={testEndpoint}
            testAllEndpoints={testAllEndpoints}
          />
        );
      case 4:
        return (
          <Step4
            monetizationConfig={monetizationConfig}
            setMonetizationConfig={setMonetizationConfig}
            mcpTools={mcpTools}
            apiName={apiName}
            onValidationChange={setStep4Validation}
          />
        );
      case 5:
        return (
          <Confirmation
            apiConfig={apiConfig}
            monetizationConfig={monetizationConfig}
            mcpTools={mcpTools}
            apiName={apiName}
            apiDescription={apiDescription}
            selectedCategory={selectedCategory}
            selectedSubcategory={selectedSubcategory}
            onEditStep={goToStep}
            onSubmit={handleSubmit}
            isSubmitting={isSubmitting}
          />
        );
      default:
        return null;
    }
  };

  // Check if we can proceed to next step
  const canProceedToNextStep = () => {
    switch (currentStep) {
      case 1:
        return apiName.trim() &&
          apiDescription.trim() &&
          selectedCategory &&
          selectedSubcategory &&
          apiNameValidation.isValid &&
          !apiNameValidation.isChecking;
      case 2:
        // Check that URL is valid and not empty
        const isValidUrl = (url: string) => {
          try {
            const urlObj = new URL(url);
            return urlObj.protocol === 'http:' || urlObj.protocol === 'https:';
          } catch {
            return false;
          }
        };

        return apiConfig.baseUrl.trim() &&
          isValidUrl(apiConfig.baseUrl) &&
          apiConfig.authorization.type &&
          (apiConfig.authorization.type === 'none' ||
            (apiConfig.authorization.type === 'basic' &&
              apiConfig.authorization.username?.trim() &&
              apiConfig.authorization.password?.trim()) ||
            (apiConfig.authorization.type !== 'basic' &&
              apiConfig.authorization.headerName?.trim() &&
              apiConfig.authorization.headerValue?.trim()));
      case 3:
        return mcpTools.length > 0 && mcpTools.every(tool => tool.testStatus === 'success') && !mcpTools.some(tool => !tool.testStatus);
      case 4:
        return step4Validation; // Step 4 requires all tools to be assigned to at least one plan
      default:
        return false;
    }
  };

  // Check if we can submit
  const canSubmit = () => {
    const result = currentStep === 4;
    console.log('canSubmit() called:', { currentStep, result });

    // If visually on step 4 but currentStep is not 4,
    // force localStorage update and allow submission
    if (!result && currentStep === 3) {
      console.log('Force update currentStep to 4');
      setCurrentStep(4);
      // Return true immediately to allow submission
      return true;
    }

    return result;
  };

  if (isAuthChecking) {
    return (
      <div className="min-h-screen bg-theme-primary transition-colors duration-300">
        <div className="max-w-7xl mx-auto">
          <div className="space-y-4 animate-pulse">
            <div className="h-8 bg-theme-secondary rounded w-1/3" />
            <div className="h-64 bg-theme-secondary rounded-xl" />
          </div>
        </div>
      </div>
    );
  }

  if (!isAuthenticated) {
    return (
      <div className="min-h-screen bg-theme-primary transition-colors duration-300">
        <div className="mx-auto max-w-4xl">
          <div className="min-h-[300px] flex items-center justify-center">
            <div className="text-center">
              <h1 className="text-2xl font-bold text-theme-primary mb-4">
                {tSettings('unauthorized')}
              </h1>
              <p className="text-theme-secondary mb-6">
                {tSettings('mustBeLoggedIn')}
              </p>
              <Button onClick={() => loginWithRedirect()} size="sm" className="h-8 px-3">
                <User className="w-4 h-4 mr-1" />
                {tSettings('signIn')}
              </Button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-theme-primary transition-colors duration-300">


      {/* Notification component */}
      {notification && (
        <div className={`fixed top-4 right-4 z-50 max-w-md p-4 rounded-lg shadow-lg transition-all duration-300 ${notification.type === 'success'
          ? 'bg-green-500 text-white'
          : notification.type === 'error'
            ? 'bg-red-500 text-white'
            : 'bg-blue-500 text-white'
          }`}>
          <div className="flex items-center space-x-3">
            {notification.type === 'success' && <CheckCircle className="w-5 h-5" />}
            {notification.type === 'error' && <AlertCircle className="w-5 h-5" />}
            {notification.type === 'info' && <Info className="w-5 h-5" />}
            <div className="flex-1">
              <p className="font-medium">{notification.message}</p>
            </div>
            <Button
              onClick={() => setNotification(null)}
              variant="ghost"
              size="icon"
              className="text-white/80 hover:text-white h-6 w-6"
            >
              <span className="sr-only">Close</span>
              ×
            </Button>
          </div>
        </div>
      )}

      <div className="max-w-7xl mx-auto">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between mb-8">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-theme-secondary rounded-full flex items-center justify-center">
              <Code className="w-5 h-5 text-theme-primary" />
            </div>
            <div>
              <h1 className="text-2xl font-semibold text-theme-primary">{t('title')}</h1>
              <p className="text-sm text-theme-secondary">{t('subtitle')}</p>
            </div>
          </div>
        </div>
        <ApiTemplatesSection
          templates={apiTemplates}
          selectedTemplate={selectedTemplate}
          onTemplateSelect={applyTemplate}
          showSection={currentStep === 1}
          apiName={apiName}
          apiDescription={apiDescription}
          selectedCategory={selectedCategory}
          selectedSubcategory={selectedSubcategory}
          apiConfig={apiConfig}
          mcpTools={mcpTools}
        />

        <div className="">
          {currentStep < 5 && (
            <StepIndicator
              currentStep={currentStep}
              onStepClick={goToStep}
              steps={steps}
            />
          )}

          <form onSubmit={(e) => e.preventDefault()}>
            {renderCurrentStep()}

            {/* Step navigation */}
            {currentStep < 5 && (
              <div className="flex justify-between items-center mt-8 pt-8 border-t border-theme/20">
                <Button
                  type="button"
                  onClick={prevStep}
                  disabled={currentStep === 1}
                  variant="secondary"
                  size="lg"
                  className="px-6 disabled:bg-gray-300 disabled:text-gray-500 disabled:dark:bg-gray-600 disabled:dark:text-gray-400 disabled:cursor-not-allowed"
                >
                  <ChevronLeft className="w-5 h-5" />
                  <span>{t('navigation.previous')}</span>
                </Button>

                <div className="flex items-center space-x-4">
                  {currentStep === 4 && (
                    <Button
                      type="button"
                      onClick={() => setCurrentStep(5)}
                      disabled={!step4Validation}
                      variant="default"
                      size="lg"
                      className="px-6 disabled:bg-gray-300 disabled:text-gray-500 disabled:dark:bg-gray-600 disabled:dark:text-gray-400 disabled:cursor-not-allowed"
                    >
                      <span>{t('navigation.summary')}</span>
                      <ChevronRight className="w-5 h-5" />
                    </Button>
                  )}

                  {currentStep < 4 && (
                    <Button
                      type="button"
                      onClick={nextStep}
                      disabled={!canProceedToNextStep()}
                      variant="default"
                      size="lg"
                      className="px-6 disabled:bg-gray-300 disabled:text-gray-500 disabled:dark:bg-gray-600 disabled:dark:text-gray-400 disabled:cursor-not-allowed"
                    >
                      <span>{t('navigation.next')}</span>
                      <ChevronRight className="w-5 h-5" />
                    </Button>
                  )}
                </div>
              </div>
            )}
          </form>
        </div>
      </div>



      {/* Toast notifications (same as pricing page) */}
      {toast && (
        <Toast
          id="developer-toast"
          title={toast.type === 'success' ? 'Success' : toast.type === 'error' ? 'Error' : 'Info'}
          message={toast.message}
          type={toast.type}
          onClose={() => closeToast()}
        />
      )}
    </div>
  );
}
