import type { ToolRuntimeMetadata } from '@/types/runtimeMetadata';

export interface ApiTemplateToolResponse {
  type: 'json' | 'binary' | 'text' | 'xml' | 'csv' | 'html';
}

export interface ApiTemplateTool {
  name: string;
  endpoint: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  category: string;
  response: ApiTemplateToolResponse;
}

export interface ApiTemplateDefaults {
  apiName: string;
  apiDescription: string;
  selectedCategory: string;
  selectedSubcategory: string;
  baseUrl: string;
  authorization: {
    type: string;
    headerName?: string;
    headerValue?: string;
    username?: string;
    password?: string;
    description?: string;
  };
  pricing: 'free' | 'freemium' | 'paid';
  rateLimit: {
    requests: number;
    period: 'second' | 'minute' | 'hour' | 'day';
  };
  tools: ApiTemplateTool[];
}

export interface ApiTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  type: 'local' | 'external';
  defaults: ApiTemplateDefaults;
}

export interface McpTool {
  id?: string; // Optional - will be generated by backend
  name: string;
  description: string;
  category: string;
  subcategory: string;
  toolCategory: string;
  toolNameId?: string; // ID du nom d'outil dans la DB
  isCustomCategory?: boolean; // Indique si c'est une categorie personnalisee
  isCustomToolName?: boolean; // Indique si c'est un nom d'outil personnalise
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  endpoint: string;
  headers: Header[];
  parameters: Parameter[];
  pathParameters: PathParameter[];
  queryParameters: QueryParameter[];
  response: ResponseSchema;
  body?: any;
  bodyParams?: { name: string; value: string; type: 'text' | 'file'; description?: string; required?: boolean }[];
  bodySchema?: string; // JSON schema for request body validation
  pricing: 'free' | 'freemium' | 'paid';
  rateLimit: string;
  status: 'draft' | 'submitted' | 'approved' | 'rejected';
  isActive?: boolean;
  testStatus?: 'pending' | 'success' | 'error';
  testResult?: {
    status: number;
    responseTime: number;
    error?: string;
    data?: any;
    headers?: Record<string, string>;
  };
  runtimeMetadata?: ToolRuntimeMetadata;
}

export interface Header {
  name: string;
  value: string;
  required: boolean;
  description?: string;
}

export interface Parameter {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'object' | 'array';
  required: boolean;
  description?: string;
  example?: string;
}

export interface PathParameter {
  name: string;
  type: 'string' | 'number' | 'boolean';
  required: boolean;
  description?: string;
  example?: string;
  pattern?: string;
}

export interface QueryParameter {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'array';
  required: boolean;
  description?: string;
  example?: string;
  defaultValue?: string;
  allowedValues?: string[];
}

export interface ResponseSchema {
  success: any;
  error: any;
  description: string;
  type?: 'json' | 'xml' | 'csv' | 'text' | 'html' | 'binary';
}

export interface ApiConfig {
  baseUrl: string;
  healthcheckEndpoint: string;
  authorization: {
    type: 'apisecret' | 'bearer' | 'basic' | 'none';
    headerName?: string;
    headerValue?: string;
    username?: string;
    password?: string;
    description?: string;
  };
  visibility: 'public' | 'private' | 'enterprise';
}

export interface MonetizationConfig {
  pricing: 'freemium' | 'paid';
  selectedPricingModels?: ('freemium' | 'paid')[];
  rateLimit: {
    requests: number;
    period: 'second' | 'minute' | 'hour' | 'day' | 'month';
  };
  monetization: {
    freeRequests: number;
    tokenValue: number;
  };
  selectedPlans: {
    basic: boolean;
    pro: boolean;
    ultra: boolean;
    mega: boolean;
  };
  hardLimitBasic: boolean;
  hardLimitPro: boolean;
  hardLimitUltra: boolean;
  hardLimitMega: boolean;
  // Prices and quotas per plan
  priceBasic: number;
  pricePro: number;
  priceUltra: number;
  priceMega: number;
  quotaBasic: number;
  quotaPro: number;
  quotaUltra: number;
  quotaMega: number;
  rpsBasic: number;
  rpsPro: number;
  rpsUltra: number;
  rpsMega: number;
  rpsPeriodBasic: 'second' | 'minute' | 'hour' | 'day';
  rpsPeriodPro: 'second' | 'minute' | 'hour' | 'day';
  rpsPeriodUltra: 'second' | 'minute' | 'hour' | 'day';
  rpsPeriodMega: 'second' | 'minute' | 'hour' | 'day';
  // Overusage costs for plans without hard limit
  overusageCostBasic: number;
  overusageCostPro: number;
  overusageCostUltra: number;
  overusageCostMega: number;
  showPlansInfo: boolean;
  // Uniform price for all tools (freemium) - in MAU
  uniformToolPrice?: number;
  uniformToolPriceInDollars?: number;
  uniformCalls?: number;
  // Free requests per user (freemium)
  freeRequestsPerUser?: number;
  // Free requests type (per-user or global)
  freeRequestsType?: 'per-user' | 'global';
  // Specific free requests per tool for freemium plan
  toolFreeRequests?: Record<string, number | string>;
  // Specific rate limits per tool
  toolRateLimits?: Record<string, {
    requests: number;
    period: 'second' | 'minute' | 'hour' | 'day' | 'month';
  }>;
  // Specific prices per tool for freemium plan
  toolPricing: Record<string, {
    mauValue: number;
    price: number;
    currency: string;
    calls?: number; // Number of calls per MAU
  }>;
  // Tools included in each plan (only for paid model)
  planTools: {
    basic: string[]; // Names of included tools
    pro: string[];
    ultra: string[];
    mega: string[];
  };
  // Track explicit "all tools" mode for each plan
  planAllToolsMode: {
    basic: boolean;
    pro: boolean;
    ultra: boolean;
    mega: boolean;
  };
  // Multi-pricing model configuration
  modelInteractionStrategy?: 'separate' | 'upgrade' | 'hybrid';
  userSegmentationStrategy?: 'manual' | 'auto' | 'tiered';
  conversionIncentives?: string;
  upgradeIncentives?: string;
  defaultModelPriority?: 'free' | 'freemium' | 'paid';
  // Specific PAID configuration per tool
  toolPaidConfig?: Record<string, {
    planName?: string;
    quota?: number;
    price?: number;
    overusageCost?: number;
    hardLimit?: boolean;
    rateLimitRequests?: number;
    rateLimitPeriod?: 'second' | 'minute' | 'hour' | 'day' | 'month';
  }>;
}

// Props for components
export interface StepIndicatorProps {
  currentStep: number;
}

export interface HeaderSectionProps {
  // No props needed for now
}

export interface FeaturesSectionProps {
  // No props needed for now
}

export interface Step1Props {
  apiName: string;
  setApiName: (name: string) => void;
  selectedCategory: string;
  setSelectedCategory: (category: string) => void;
  selectedSubcategory: string;
  setSelectedSubcategory: (subcategory: string) => void;
  apiDescription: string;
  setApiDescription: (description: string) => void;
  predefinedTools: Record<string, Record<string, string[]>>;
  setMcpTools?: (tools: McpTool[]) => void;
  apiNameValidation?: {
    isValid: boolean;
    message: string;
    isChecking: boolean;
  };
  setApiNameValidation?: (validation: {
    isValid: boolean;
    message: string;
    isChecking: boolean;
  }) => void;
  setApiConfig?: (config: ApiConfig) => void;
}

export interface Step2Props {
  apiConfig: ApiConfig;
  setApiConfig: (config: ApiConfig) => void;
  apiName: string;
}

export interface Step3Props {
  mcpTools: McpTool[];
  setMcpTools: (tools: McpTool[]) => void;
  apiConfig: ApiConfig;
  setApiConfig: (config: ApiConfig) => void;
  apiName: string;
  selectedCategory: string;
  selectedSubcategory: string;
  testEndpoint: (index: number) => void;
  testAllEndpoints: () => void;
}

export interface Step4Props {
  monetizationConfig: MonetizationConfig;
  setMonetizationConfig: (config: MonetizationConfig) => void;
  mcpTools: McpTool[];
  apiName: string;
  onValidationChange?: (isValid: boolean) => void;
}

export interface ConfirmationProps {
  apiName: string;
  mcpTools: McpTool[];
}

export interface ToolCategoryGroupProps {
  category: string;
  tools: McpTool[];
  onToolUpdate: (toolIndex: number, updatedTool: McpTool) => void;
  onTestEndpoint: (toolIndex: number) => void;
  apiConfig: ApiConfig;
  mcpTools: McpTool[];
  setMcpTools: (tools: McpTool[]) => void;
}
