import { McpTool, ApiConfig, MonetizationConfig } from './types';
import { unifiedApiService } from '@/lib/api/unified-api-service';

// Utility function to generate a unique ID - REMOVED: IDs are now generated by backend

// Utility function to automatically detect path parameters
export const detectPathParameters = (endpoint: string, existingParams?: { name: string; type: 'string' | 'number' | 'boolean'; required: boolean; description?: string; example?: string; pattern?: string }[]): { name: string; type: 'string' | 'number' | 'boolean'; required: boolean; description: string; example: string; pattern: string }[] => {
  if (!endpoint) return [];

  const pathParamRegex = /{([^}]+)}/g;
  const matches = endpoint.match(pathParamRegex);

  if (!matches) return [];

  return matches.map(match => {
    // Extract parameter name from {paramName} format
    const paramName = match.slice(1, -1); // Remove { and }

    // Check if this parameter already exists to preserve its example
    const existingParam = existingParams?.find(p => p.name === paramName);

    // Determine type based on parameter name
    let paramType: 'string' | 'number' | 'boolean' = 'string';
    if (paramName.toLowerCase().includes('id') || paramName.toLowerCase().includes('number') || paramName.toLowerCase().includes('count')) {
      paramType = 'number';
    } else if (paramName.toLowerCase().includes('enabled') || paramName.toLowerCase().includes('active') || paramName.toLowerCase().includes('status')) {
      paramType = 'boolean';
    }

    // Generate an example based on the type, but preserve existing example if available
    let example = '';
    if (existingParam?.example) {
      example = existingParam.example;
    } else {
      switch (paramType) {
        case 'number':
          example = '123';
          break;
        case 'boolean':
          example = 'true';
          break;
        default:
          example = 'example';
      }
    }

    return {
      name: paramName,
      type: paramType,
      required: true,
      description: existingParam?.description || `Path parameter ${paramName}`,
      example,
      pattern: existingParam?.pattern || ''
    };
  });
};

// Utility function to automatically detect query parameters
export const detectQueryParameters = (endpoint: string, existingParams?: { name: string; type: 'string' | 'number' | 'boolean' | 'array'; required: boolean; description?: string; example?: string; defaultValue?: string }[]): { name: string; type: 'string' | 'number' | 'boolean' | 'array'; required: boolean; description: string; example: string; defaultValue?: string }[] => {
  if (!endpoint) return [];

  // Extract the query string (after ?)
  const queryString = endpoint.split('?')[1];
  if (!queryString) return [];

  // Split by & to get individual parameters
  const paramPairs = queryString.split('&');
  const queryParams: { name: string; type: 'string' | 'number' | 'boolean' | 'array'; required: boolean; description: string; example: string; defaultValue?: string }[] = [];

  for (const paramPair of paramPairs) {
    if (!paramPair.trim()) continue;

    let paramName = '';
    let defaultValue = '';
    let isRequired = false;

    if (paramPair.includes('=')) {
      // Format: param=value or param={value}
      const [name, value] = paramPair.split('=', 2);
      paramName = name.trim();

      if (value) {
        // Check if it's a placeholder {value}
        const placeholderMatch = value.match(/^\{([^}]+)\}$/);
        if (placeholderMatch) {
          // It's a placeholder, parameter is required
          isRequired = true;
          defaultValue = `example_${placeholderMatch[1]}`;
        } else {
          // It's a default value
          defaultValue = value;
          isRequired = false;
        }
      } else {
        // param= (empty value)
        isRequired = false;
        defaultValue = '';
      }
    } else {
      // Format: just param (no =)
      paramName = paramPair.trim();
      isRequired = false;
      defaultValue = '';
    }

    // Skip if parameter already exists
    if (paramName && !queryParams.some(p => p.name === paramName)) {
      // Check if this parameter already exists to preserve its properties
      const existingParam = existingParams?.find(p => p.name === paramName);

      // Determine type based on parameter name
      let paramType: 'string' | 'number' | 'boolean' | 'array' = 'string';
      if (paramName.toLowerCase().includes('id') || paramName.toLowerCase().includes('count') || paramName.toLowerCase().includes('limit')) {
        paramType = 'number';
      } else if (paramName.toLowerCase().includes('enabled') || paramName.toLowerCase().includes('active') || paramName.toLowerCase().includes('status')) {
        paramType = 'boolean';
      } else if (paramName.toLowerCase().includes('tags') || paramName.toLowerCase().includes('ids') || paramName.toLowerCase().includes('list')) {
        paramType = 'array';
      }

      // Generate example based on type, but preserve existing example if available
      let example = '';
      if (existingParam?.example) {
        example = existingParam.example;
      } else {
        switch (paramType) {
          case 'number':
            example = '123';
            break;
          case 'boolean':
            example = 'true';
            break;
          case 'array':
            example = 'item1,item2,item3';
            break;
          default:
            example = 'example';
        }
      }

      queryParams.push({
        name: paramName,
        type: paramType,
        required: isRequired,
        description: existingParam?.description || `Query parameter ${paramName}`,
        example: defaultValue || example,
        defaultValue: isRequired ? undefined : defaultValue || undefined
      });
    }
  }

  return queryParams;
};

// Utility function to build query string from query parameters
export const buildQueryString = (queryParameters?: any[]): string => {
  if (!queryParameters || queryParameters.length === 0) return '';

  const queryParts: string[] = [];

  for (const param of queryParameters) {
    if (param.name) {
      if (param.required) {
        // Required parameter uses placeholder
        queryParts.push(`${param.name}={${param.name}}`);
      } else if (param.example) {
        // Optional parameter with example value
        queryParts.push(`${param.name}=${param.example}`);
      } else {
        // Optional parameter without example
        queryParts.push(`${param.name}`);
      }
    }
  }

  return queryParts.length > 0 ? queryParts.join('&') : '';
};

// Utility function to build the full URL
export const getFullUrl = (endpoint: string, baseUrl: string, pathParameters?: any[]): string => {
  if (!endpoint || !baseUrl) return endpoint || baseUrl || '';
  
  let processedEndpoint = endpoint;
  
  // Replace path parameters with their examples
  if (pathParameters && pathParameters.length > 0) {
    pathParameters.forEach(param => {
      if (param.name && param.example) {
        processedEndpoint = processedEndpoint.replace(`{${param.name}}`, param.example);
      }
    });
  }
  
  const cleanBaseUrl = baseUrl.replace(/\/$/, ''); // Remove trailing slash
  const cleanEndpoint = processedEndpoint.replace(/^\//, ''); // Remove leading slash
  
  return `${cleanBaseUrl}/${cleanEndpoint}`;
};

// Utility function to build URL parameters
export const buildUrlParams = (queryParameters?: any[]): string => {
  if (!queryParameters || queryParameters.length === 0) return '';
  
  const allParams = [];
  
  // Add query parameters
  allParams.push(...queryParameters.filter(p => p.name && (p.example || p.defaultValue)).map(p => {
    const value = p.example || p.defaultValue;
    return `${p.name}=${encodeURIComponent(value)}`;
  }));
  
  return allParams.length > 0 ? `?${allParams.join('&')}` : '';
};

// Utility function to build encoded body
export const buildEncodedBody = (bodyParams: any[]): string => {
  if (!bodyParams || bodyParams.length === 0) return '';
  
  const allParams = bodyParams.filter(p => p.name && (p.example || p.defaultValue)).map(p => {
    const value = p.example || p.defaultValue;
    return `${p.name}=${encodeURIComponent(value)}`;
  });
  
  return allParams.join('&');
};

// Utility function to build JSON body
export const buildJsonBody = (bodyParams: any[]): any => {
  if (!bodyParams || bodyParams.length === 0) return {};
  
  const body: any = {};
  bodyParams.forEach(p => {
    if (p.name && (p.example || p.defaultValue)) {
      body[p.name] = p.example || p.defaultValue;
    }
  });
  
  return body;
};

// Utility function to generate cURL command
export const generateCurlCommand = (tool: McpTool, apiConfig: ApiConfig): string => {
  console.log('🔍 generateCurlCommand Debug:', {
    endpoint: tool.endpoint,
    baseUrl: apiConfig.baseUrl,
    pathParameters: tool.pathParameters,
    queryParameters: tool.queryParameters
  });
  
  const url = getFullUrl(tool.endpoint, apiConfig.baseUrl, tool.pathParameters);
  const queryParams = buildUrlParams(tool.queryParameters);
  const fullUrl = url + queryParams;
  
  console.log('🔍 URL Generation:', {
    url,
    queryParams,
    fullUrl
  });
  
  let curl = `curl -X ${tool.method} "${fullUrl}"`;
  
  // Add headers
  if (tool.headers && tool.headers.length > 0) {
    tool.headers.forEach(header => {
      if (header.name && header.value) {
        curl += ` \\\n  -H "${header.name}: ${header.value}"`;
      }
    });
  }
  
  // Add authorization header
  if (apiConfig.authorization.type !== 'none') {
    if (apiConfig.authorization.type === 'bearer') {
      const tokenValue = apiConfig.authorization.headerValue || 'YOUR_TOKEN';
      // Remove "Bearer " prefix if it's already in the value
      const cleanToken = tokenValue.startsWith('Bearer ') ? tokenValue.substring(7) : tokenValue;
      curl += ` \\\n  -H "Authorization: Bearer ${cleanToken}"`;
    } else if (apiConfig.authorization.type === 'basic') {
      const username = apiConfig.authorization.username || 'YOUR_USERNAME';
      const password = apiConfig.authorization.password || 'YOUR_PASSWORD';
      curl += ` \\\n  -u "${username}:${password}"`;
    } else if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
      curl += ` \\\n  -H "${apiConfig.authorization.headerName}: ${apiConfig.authorization.headerValue}"`;
    }
  }
  
  // Add body for POST/PUT
  if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams && tool.bodyParams.length > 0) {
    const body = buildEncodedBody(tool.bodyParams);
    if (body) {
      curl += ` \\\n  -d "${body}"`;
    }
  }
  
  return curl;
};

// Utility function to generate JavaScript code
export const generateJavaScriptCode = (tool: McpTool, apiConfig: ApiConfig): string => {
  const url = getFullUrl(tool.endpoint, apiConfig.baseUrl, tool.pathParameters);
  const queryParams = buildUrlParams(tool.queryParameters);
  const fullUrl = url + queryParams;
  
  let js = `const response = await fetch("${fullUrl}", {\n`;
  js += `  method: "${tool.method}",\n`;
  
  // Add headers
  if (tool.headers && tool.headers.length > 0) {
    js += `  headers: {\n`;
    tool.headers.forEach(header => {
      if (header.name && header.value) {
        js += `    "${header.name}": "${header.value}",\n`;
      }
    });
    
    // Add authorization header
    if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
      js += `    "${apiConfig.authorization.headerName}": "${apiConfig.authorization.headerValue}",\n`;
    }
    
    js += `  },\n`;
  } else if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
    js += `  headers: {\n`;
    js += `    "${apiConfig.authorization.headerName}": "${apiConfig.authorization.headerValue}",\n`;
    js += `  },\n`;
  }
  
  // Add body for POST/PUT
  if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams && tool.bodyParams.length > 0) {
    const body = buildJsonBody(tool.bodyParams);
    js += `  body: JSON.stringify(${JSON.stringify(body, null, 2)}),\n`;
  }
  
  js += `});\n\nconst data = await response.json();`;
  
  return js;
};

// Utility function to generate Python code
export const generatePythonCode = (tool: McpTool, apiConfig: ApiConfig): string => {
  const url = getFullUrl(tool.endpoint, apiConfig.baseUrl, tool.pathParameters);
  const queryParams = buildUrlParams(tool.queryParameters);
  const fullUrl = url + queryParams;
  
  let python = `import requests\n\n`;
  
  // Add headers
  let headers = '{}';
  if (tool.headers && tool.headers.length > 0) {
    const headerDict: any = {};
    tool.headers.forEach(header => {
      if (header.name && header.value) {
        headerDict[header.name] = header.value;
      }
    });
    
    // Add authorization header
    if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
      headerDict[apiConfig.authorization.headerName] = apiConfig.authorization.headerValue;
    }
    
    headers = JSON.stringify(headerDict, null, 2);
  } else if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
    headers = JSON.stringify({
      [apiConfig.authorization.headerName]: apiConfig.authorization.headerValue
    }, null, 2);
  }
  
  python += `headers = ${headers}\n`;
  
  // Add body for POST/PUT
  if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams && tool.bodyParams.length > 0) {
    const body = buildJsonBody(tool.bodyParams);
    python += `data = ${JSON.stringify(body, null, 2)}\n\n`;
    python += `response = requests.${tool.method.toLowerCase()}("${fullUrl}", headers=headers, json=data)\n`;
  } else {
    python += `\nresponse = requests.${tool.method.toLowerCase()}("${fullUrl}", headers=headers)\n`;
  }
  
  python += `data = response.json()`;
  
  return python;
};

// Utility function to generate Java code
export const generateJavaCode = (tool: McpTool, apiConfig: ApiConfig): string => {
  const url = getFullUrl(tool.endpoint, apiConfig.baseUrl, tool.pathParameters);
  const queryParams = buildUrlParams(tool.queryParameters);
  const fullUrl = url + queryParams;
  
  let java = `import java.net.http.HttpClient;\n`;
  java += `import java.net.http.HttpRequest;\n`;
  java += `import java.net.http.HttpResponse;\n`;
  java += `import java.net.URI;\n`;
  java += `import java.util.Map;\n`;
  java += `import java.util.HashMap;\n`;
  java += `import com.google.gson.Gson;\n\n`;
  
  java += `HttpClient client = HttpClient.newHttpClient();\n\n`;
  
  // Add headers
  if (tool.headers && tool.headers.length > 0) {
    java += `        Map<String, String> headers = new HashMap<>();\n`;
    tool.headers.forEach(header => {
      if (header.name && header.value) {
        java += `        headers.put("${header.name}", "${header.value}");\n`;
      }
    });
    
    // Add authorization header
    if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
      java += `        headers.put("${apiConfig.authorization.headerName}", "${apiConfig.authorization.headerValue}");\n`;
    }
    
    java += `        \n`;
  } else if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
    java += `        Map<String, String> headers = new HashMap<>();\n`;
    java += `        headers.put("${apiConfig.authorization.headerName}", "${apiConfig.authorization.headerValue}");\n\n`;
  }
  
  java += `        HttpRequest.Builder requestBuilder = HttpRequest.newBuilder()\n`;
  java += `            .uri(URI.create("${fullUrl}"))\n`;
  java += `            .method("${tool.method}", HttpRequest.BodyPublishers.noBody())\n`;
  
  // Add body for POST/PUT
  if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams && tool.bodyParams.length > 0) {
    const body = buildJsonBody(tool.bodyParams);
    java += `            .header("Content-Type", "application/json")\n`;
    java += `            .method("${tool.method}", HttpRequest.BodyPublishers.ofString(new Gson().toJson(${JSON.stringify(body)})))\n`;
  }
  
  // Add headers to the request
  if (tool.headers && tool.headers.length > 0) {
    java += `            .header("Content-Type", "application/json")\n`;
    java += `            .headers(headers.entrySet().stream()\n`;
    java += `                .map(e -> new String[]{e.getKey(), e.getValue()})\n`;
    java += `                .flatMap(arr -> java.util.Arrays.stream(arr))\n`;
    java += `                .toArray(String[]::new))\n`;
  }
  
  java += `            .build();\n\n`;
  java += `        HttpResponse<String> response = client.send(requestBuilder.build(), HttpResponse.BodyHandlers.ofString());\n`;
  java += `        String data = response.body();`;
  
  return java;
};

// Utility function to generate PHP code
export const generatePHPCode = (tool: McpTool, apiConfig: ApiConfig): string => {
  const url = getFullUrl(tool.endpoint, apiConfig.baseUrl, tool.pathParameters);
  const queryParams = buildUrlParams(tool.queryParameters);
  const fullUrl = url + queryParams;
  
  let php = `<?php\n\n`;
  
  // Add headers
  let headers = '[]';
  if (tool.headers && tool.headers.length > 0) {
    const headerArray: string[] = [];
    tool.headers.forEach(header => {
      if (header.name && header.value) {
        headerArray.push(`"${header.name}: ${header.value}"`);
      }
    });
    
    // Add authorization header
    if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
      headerArray.push(`"${apiConfig.authorization.headerName}: ${apiConfig.authorization.headerValue}"`);
    }
    
    headers = `[\n    ${headerArray.join(",\n    ")}\n]`;
  } else if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
    headers = `["${apiConfig.authorization.headerName}: ${apiConfig.authorization.headerValue}"]`;
  }
  
  php += `$headers = ${headers};\n`;
  
  // Add body for POST/PUT
  if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams && tool.bodyParams.length > 0) {
    const body = buildJsonBody(tool.bodyParams);
    php += `$data = ${JSON.stringify(body, null, 2)};\n\n`;
    php += `$ch = curl_init();\n`;
    php += `curl_setopt($ch, CURLOPT_URL, "${fullUrl}");\n`;
    php += `curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);\n`;
    php += `curl_setopt($ch, CURLOPT_POST, true);\n`;
    php += `curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));\n`;
    php += `curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);\n\n`;
    php += `$response = curl_exec($ch);\n`;
    php += `curl_close($ch);\n\n`;
    php += `$data = json_decode($response, true);`;
  } else {
    php += `\n$ch = curl_init();\n`;
    php += `curl_setopt($ch, CURLOPT_URL, "${fullUrl}");\n`;
    php += `curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);\n`;
    php += `curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);\n\n`;
    php += `$response = curl_exec($ch);\n`;
    php += `curl_close($ch);\n\n`;
    php += `$data = json_decode($response, true);`;
  }
  
  return php;
};

// Utility function to generate Node.js code
export const generateNodeJSCode = (tool: McpTool, apiConfig: ApiConfig): string => {
  const url = getFullUrl(tool.endpoint, apiConfig.baseUrl, tool.pathParameters);
  const queryParams = buildUrlParams(tool.queryParameters);
  const fullUrl = url + queryParams;
  
  let nodejs = `const fetch = require('node-fetch');\n\n`;
  
  // Add headers
  let headers = '{}';
  if (tool.headers && tool.headers.length > 0) {
    const headerDict: any = {};
    tool.headers.forEach(header => {
      if (header.name && header.value) {
        headerDict[header.name] = header.value;
      }
    });
    
    // Add authorization header
    if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
      headerDict[apiConfig.authorization.headerName] = apiConfig.authorization.headerValue;
    }
    
    headers = JSON.stringify(headerDict, null, 2);
  } else if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
    headers = JSON.stringify({
      [apiConfig.authorization.headerName]: apiConfig.authorization.headerValue
    }, null, 2);
  }
  
  nodejs += `const headers = ${headers};\n`;
  
  // Add body for POST/PUT
  if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams && tool.bodyParams.length > 0) {
    const body = buildJsonBody(tool.bodyParams);
    nodejs += `const data = ${JSON.stringify(body, null, 2)};\n\n`;
    nodejs += `const response = await fetch("${fullUrl}", {\n`;
    nodejs += `  method: '${tool.method}',\n`;
    nodejs += `  headers: { ...headers, 'Content-Type': 'application/json' },\n`;
    nodejs += `  body: JSON.stringify(data)\n`;
    nodejs += `});\n\n`;
    nodejs += `const result = await response.json();`;
  } else {
    nodejs += `\nconst response = await fetch("${fullUrl}", {\n`;
    nodejs += `  method: '${tool.method}',\n`;
    nodejs += `  headers\n`;
    nodejs += `});\n\n`;
    nodejs += `const result = await response.json();`;
  }
  
  return nodejs;
};

// Utility function to generate Go code
export const generateGoCode = (tool: McpTool, apiConfig: ApiConfig): string => {
  const url = getFullUrl(tool.endpoint, apiConfig.baseUrl, tool.pathParameters);
  const queryParams = buildUrlParams(tool.queryParameters);
  const fullUrl = url + queryParams;
  
  let go = `package main\n\n`;
  go += `import (\n`;
  go += `    "bytes"\n`;
  go += `    "encoding/json"\n`;
  go += `    "fmt"\n`;
  go += `    "net/http"\n`;
  go += `)\n\n`;
  
  // Add body for POST/PUT
  if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams && tool.bodyParams.length > 0) {
    const body = buildJsonBody(tool.bodyParams);
    go += `func main() {\n`;
    go += `    data := ${JSON.stringify(body, null, 2)}\n`;
    go += `    jsonData, _ := json.Marshal(data)\n\n`;
    go += `    req, _ := http.NewRequest("${tool.method}", "${fullUrl}", bytes.NewBuffer(jsonData))\n`;
    go += `    req.Header.Set("Content-Type", "application/json")\n`;
    
    // Add authorization header
    if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
      go += `    req.Header.Set("${apiConfig.authorization.headerName}", "${apiConfig.authorization.headerValue}")\n`;
    }
    
    go += `\n    client := &http.Client{}\n`;
    go += `    resp, _ := client.Do(req)\n`;
    go += `    defer resp.Body.Close()\n\n`;
    go += `    var result map[string]interface{}\n`;
    go += `    json.NewDecoder(resp.Body).Decode(&result)\n`;
    go += `    fmt.Printf("%+v\\n", result)\n`;
    go += `}`;
  } else {
    go += `func main() {\n`;
    go += `    req, _ := http.NewRequest("${tool.method}", "${fullUrl}", nil)\n`;
    
    // Add authorization header
    if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
      go += `    req.Header.Set("${apiConfig.authorization.headerName}", "${apiConfig.authorization.headerValue}")\n`;
    }
    
    go += `\n    client := &http.Client{}\n`;
    go += `    resp, _ := client.Do(req)\n`;
    go += `    defer resp.Body.Close()\n\n`;
    go += `    var result map[string]interface{}\n`;
    go += `    json.NewDecoder(resp.Body).Decode(&result)\n`;
    go += `    fmt.Printf("%+v\\n", result)\n`;
    go += `}`;
  }
  
  return go;
};

// Utility function to generate Ruby code
export const generateRubyCode = (tool: McpTool, apiConfig: ApiConfig): string => {
  const url = getFullUrl(tool.endpoint, apiConfig.baseUrl, tool.pathParameters);
  const queryParams = buildUrlParams(tool.queryParameters);
  const fullUrl = url + queryParams;
  
  let ruby = `require 'net/http'\n`;
  ruby += `require 'json'\n\n`;
  
  // Add headers
  let headers = '{}';
  if (tool.headers && tool.headers.length > 0) {
    const headerDict: any = {};
    tool.headers.forEach(header => {
      if (header.name && header.value) {
        headerDict[header.name] = header.value;
      }
    });
    
    // Add authorization header
    if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
      headerDict[apiConfig.authorization.headerName] = apiConfig.authorization.headerValue;
    }
    
    headers = JSON.stringify(headerDict, null, 2);
  } else if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
    headers = JSON.stringify({
      [apiConfig.authorization.headerName]: apiConfig.authorization.headerValue
    }, null, 2);
  }
  
  ruby += `headers = ${headers}\n`;
  
  // Add body for POST/PUT
  if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams && tool.bodyParams.length > 0) {
    const body = buildJsonBody(tool.bodyParams);
    ruby += `data = ${JSON.stringify(body, null, 2)}\n\n`;
    ruby += `uri = URI("${fullUrl}")\n`;
    ruby += `http = Net::HTTP.new(uri.host, uri.port)\n`;
    ruby += `http.use_ssl = true if uri.scheme == 'https'\n\n`;
    ruby += `request = Net::HTTP::${tool.method.charAt(0) + tool.method.slice(1).toLowerCase()}.new(uri)\n`;
    
    // Add headers
    if (tool.headers && tool.headers.length > 0) {
      ruby += `headers.each { |key, value| request[key] = value }\n`;
    }
    
    // Add body for POST/PUT
    if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams && tool.bodyParams.length > 0) {
      ruby += `request.body = data.to_json\n`;
    }
    
    ruby += `\nresponse = http.request(request)\n`;
    ruby += `result = JSON.parse(response.body)\n`;
    ruby += `puts result`;
  } else {
    ruby += `\nuri = URI("${fullUrl}")\n`;
    ruby += `http = Net::HTTP.new(uri.host, uri.port)\n`;
    ruby += `http.use_ssl = true if uri.scheme == 'https'\n\n`;
    ruby += `request = Net::HTTP::${tool.method.charAt(0) + tool.method.slice(1).toLowerCase()}.new(uri)\n`;
    
    // Add headers
    if (tool.headers && tool.headers.length > 0) {
      ruby += `headers.each { |key, value| request[key] = value }\n`;
    }
    
    ruby += `\nresponse = http.request(request)\n`;
    ruby += `result = JSON.parse(response.body)\n`;
    ruby += `puts result`;
  }
  
  return ruby;
};

// Utility function to generate Shell command
export const generateShellCommand = (tool: McpTool, apiConfig: ApiConfig): string => {
  const url = getFullUrl(tool.endpoint, apiConfig.baseUrl, tool.pathParameters);
  const queryParams = buildUrlParams(tool.queryParameters);
  const fullUrl = url + queryParams;
  
  let shell = `curl -X ${tool.method} "${fullUrl}"`;
  
  // Add headers
  if (tool.headers && tool.headers.length > 0) {
    tool.headers.forEach(header => {
      if (header.name && header.value) {
        shell += ` \\\n  -H "${header.name}: ${header.value}"`;
      }
    });
  }
  
  // Add authorization header
  if (apiConfig.authorization.type !== 'none') {
    if (apiConfig.authorization.type === 'bearer') {
      const tokenValue = apiConfig.authorization.headerValue || 'YOUR_TOKEN';
      // Remove "Bearer " prefix if it's already in the value
      const cleanToken = tokenValue.startsWith('Bearer ') ? tokenValue.substring(7) : tokenValue;
      shell += ` \\\n  -H "Authorization: Bearer ${cleanToken}"`;
    } else if (apiConfig.authorization.type === 'basic') {
      const username = apiConfig.authorization.username || 'YOUR_USERNAME';
      const password = apiConfig.authorization.password || 'YOUR_PASSWORD';
      shell += ` \\\n  -u "${username}:${password}"`;
    } else if (apiConfig.authorization.headerName && apiConfig.authorization.headerValue) {
      shell += ` \\\n  -H "${apiConfig.authorization.headerName}: ${apiConfig.authorization.headerValue}"`;
    }
  }
  
  // Add body for POST/PUT
  if ((tool.method === 'POST' || tool.method === 'PUT') && tool.bodyParams && tool.bodyParams.length > 0) {
    const body = buildEncodedBody(tool.bodyParams);
    if (body) {
      shell += ` \\\n  -d "${body}"`;
    }
  }
  
  return shell;
};

// Utility function to generate code examples in different languages
export const generateCodeExamples = (tool: McpTool, apiConfig: ApiConfig, language: string): string => {
  switch (language) {
    case 'curl':
      return generateCurlCommand(tool, apiConfig);
    case 'javascript':
      return generateJavaScriptCode(tool, apiConfig);
    case 'python':
      return generatePythonCode(tool, apiConfig);
    case 'java':
      return generateJavaCode(tool, apiConfig);
    case 'php':
      return generatePHPCode(tool, apiConfig);
    case 'nodejs':
      return generateNodeJSCode(tool, apiConfig);
    case 'go':
      return generateGoCode(tool, apiConfig);
    case 'ruby':
      return generateRubyCode(tool, apiConfig);
    case 'shell':
      return generateShellCommand(tool, apiConfig);
    default:
      return generateCurlCommand(tool, apiConfig);
  }
};

// Utility function to validate API configuration
export const validateApiConfig = (config: ApiConfig): { isValid: boolean; errors: string[] } => {
  const errors: string[] = [];
  
  if (!config.baseUrl.trim()) {
    errors.push('Base URL required');
  }
  
  if (!config.healthcheckEndpoint.trim()) {
    errors.push('Healthcheck endpoint required');
  }
  
  if (!config.authorization.headerName.trim()) {
    errors.push('Authorization header name required');
  }
  
  if (!config.authorization.headerValue.trim()) {
    errors.push('Authorization header value required');
  }
  
  return {
    isValid: errors.length === 0,
    errors
  };
};

// Utility function to validate parameter value based on type
export const validateParameterValue = (value: string, type: string): { isValid: boolean; error?: string } => {
  if (!value.trim()) {
    return { isValid: true }; // Empty values are valid
  }

  switch (type) {
    case 'number':
      const numValue = parseFloat(value);
      if (isNaN(numValue)) {
        return { isValid: false, error: 'Must be a valid number' };
      }
      break;

    case 'boolean':
      const lowerValue = value.toLowerCase().trim();
      if (!['true', 'false', '1', '0', 'yes', 'no'].includes(lowerValue)) {
        return { isValid: false, error: 'Must be true/false, 1/0, or yes/no' };
      }
      break;

    case 'array':
      // For arrays, expect comma-separated values or JSON array format
      if (!value.includes(',') && !value.match(/^\[.*\]$/)) {
        return { isValid: false, error: 'Must be comma-separated values or JSON array format' };
      }
      break;

    case 'string':
    default:
      // String accepts any non-empty value
      break;
  }

  return { isValid: true };
};

// Utility function to validate tool data
export const validateToolData = (tool: McpTool): { isValid: boolean; errors: string[] } => {
  const errors: string[] = [];

  if (!tool.name.trim()) {
    errors.push('Tool name required');
  }

  if (!tool.description.trim()) {
    errors.push('Tool description required');
  }

  if (!tool.toolCategory.trim()) {
    errors.push('Tool category required');
  }

  return {
    isValid: errors.length === 0,
    errors
  };
};

// Utility function to prepare submission data for backend
export const prepareSubmissionData = (
  apiName: string,
  apiDescription: string,
  selectedCategory: string,
  selectedSubcategory: string,
  apiConfig: ApiConfig,
  mcpTools: McpTool[],
  monetizationConfig: MonetizationConfig
) => {
  return {
    // Basic information
    apiName: apiName.trim(),
    apiDescription: apiDescription.trim(),
    selectedCategory: selectedCategory,
    selectedSubcategory: selectedSubcategory,
    
    // API configuration
    apiConfig: {
      baseUrl: apiConfig.baseUrl.trim(),
      healthcheckEndpoint: apiConfig.healthcheckEndpoint.trim(),
      authorization: {
        type: apiConfig.authorization.type,
        headerName: apiConfig.authorization.headerName.trim(),
        headerValue: apiConfig.authorization.headerValue.trim()
      }
    },
    
    // MCP tools
    mcpTools: mcpTools.map(tool => ({
      // id will be generated by backend
      name: tool.name.trim(),
      description: tool.description.trim(),
      toolCategory: tool.toolCategory.trim(),
      method: tool.method,
      endpoint: tool.endpoint.trim(),
      
      // Parameters
      pathParameters: tool.pathParameters || [],
      queryParameters: tool.queryParameters || [],
      headers: tool.headers || [],
      bodyParams: tool.bodyParams || [],
      
      // Response configuration
      response: tool.response || {
        type: 'json',
        description: 'API response',
        success: {},
        error: {}
      },
      
      // Pricing
      pricing: tool.pricing || 'free',
      rateLimit: tool.rateLimit || '1000 requests/hour',
      
      // Metadata
      category: selectedCategory,
      subcategory: selectedSubcategory,
      status: 'draft'
    })),
    
    // Monetization configuration
    monetization: {
      pricing: monetizationConfig.pricing,
      ...monetizationConfig
    },
    
    // Submission metadata
    submittedAt: new Date().toISOString(),
    version: '1.0.0'
  };
};

// Test function for real-time parameter detection
export const testQueryParameterDetection = (endpoint: string) => {
  console.log('🔍 Testing query parameter detection for:', endpoint);
  const params = detectQueryParameters(endpoint);
  console.log('📋 Detected parameters:', params);
  return params;
};

// Utility function to submit API to backend
export const submitDeveloperApi = async (submissionData: any): Promise<{ success: boolean; data?: any; error?: string }> => {
  try {
    const data = await unifiedApiService.processApiConfiguration(submissionData, 'default-user-id', '');
    return { success: true, data };
  } catch (error) {
    console.error('Error during submission:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
};
