// GENERATED by scripts/models/build_models_page.py - do not hand-edit.
//
// Numbers (context, list price, capabilities) come from the committed catalog
// snapshot (scripts/models/catalog-snapshot.json); release dates and the editorial
// selection come from scripts/models/models-page.json. Re-run the generator to refresh.

export type ModelCapability = 'reasoning' | 'vision' | 'tools' | 'caching' | 'web';

export interface CatalogModel {
  id: string;
  name: string;
  provider: string;
  /** ISO date of the provider announcement: 'YYYY-MM-DD', or 'YYYY-MM' when only the month is published. */
  released: string;
  /** Input context window, in tokens. */
  context: number;
  maxOutput: number | null;
  /** Provider list price, USD per 1M tokens. */
  priceIn: number;
  priceOut: number;
  caps: ModelCapability[];
  note: string | null;
}

/** Headline counts of the catalog snapshot the page was generated from. */
export const MODEL_CATALOG_STATS = {
  /** Every chat model row in the snapshot, aggregator duplicates included. */
  catalogModels: 823,
  /** Distinct models reachable through a provider of their own. */
  distinctModels: 360,
  /** Extra models reachable only through the OpenRouter aggregator. */
  aggregatorModels: 458,
  /** Providers with a native integration (the aggregator excluded). */
  directProviders: 12,
  providers: 13,
} as const;

export const CATALOG_MODELS: CatalogModel[] = [
  { id: 'gpt-6-sol', name: 'GPT-6 Sol', provider: 'openai', released: '2026-09-22', context: 922000, maxOutput: 128000, priceIn: 2, priceOut: 10, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'gpt-6-luna', name: 'GPT-6 Luna', provider: 'openai', released: '2026-09-22', context: 922000, maxOutput: 128000, priceIn: 0.1, priceOut: 0.5, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'claude-opus-5-5', name: 'Claude Opus 5.5', provider: 'anthropic', released: '2026-09-22', context: 1000000, maxOutput: 128000, priceIn: 4, priceOut: 20, caps: ['reasoning', 'vision', 'tools', 'caching'], note: 'Anthropic\'s newest model.' },
  { id: 'gpt-6-astra', name: 'GPT-6 Astra', provider: 'openai', released: '2026-09-03', context: 922000, maxOutput: 128000, priceIn: 10, priceOut: 50, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'OpenAI\'s frontier model, 922k context.' },
  { id: 'gemini-3.8-flash', name: 'Gemini 3.8 Flash', provider: 'google', released: '2026-09-02', context: 1048576, maxOutput: 65536, priceIn: 0.75, priceOut: 3.75, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'Google\'s newest workhorse Flash.' },
  { id: 'claude-fable-5-1', name: 'Claude Fable 5.1', provider: 'anthropic', released: '2026-09-01', context: 1000000, maxOutput: 128000, priceIn: 10, priceOut: 50, caps: ['reasoning', 'vision', 'tools', 'caching'], note: 'Anthropic\'s frontier model, 1M context.' },
  { id: 'grok-4.7', name: 'Grok 4.7', provider: 'xai', released: '2026-09', context: 500000, maxOutput: 500000, priceIn: 2, priceOut: 6, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'xAI\'s current flagship, 500K context.' },
  { id: 'qwen3.8-flash', name: 'Qwen3.8-Flash', provider: 'qwen', released: '2026-08-28', context: 991808, maxOutput: 131072, priceIn: 0.15, priceOut: 0.47, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'glm-5.3-flash', name: 'GLM-5.3-Flash', provider: 'zai', released: '2026-08-26', context: 1048576, maxOutput: 128000, priceIn: 0.15, priceOut: 0.5, caps: ['reasoning', 'vision', 'tools', 'caching'], note: null },
  { id: 'glm-5.3', name: 'GLM-5.3', provider: 'zai', released: '2026-08-14', context: 1000000, maxOutput: 128000, priceIn: 1.4, priceOut: 4.4, caps: ['reasoning', 'tools', 'caching'], note: 'Coding and cyber-defence tuned.' },
  { id: 'gemini-3.7-flash', name: 'Gemini 3.7 Flash', provider: 'google', released: '2026-08-13', context: 1048576, maxOutput: 65536, priceIn: 0.75, priceOut: 3.75, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'deepseek-v4-pro', name: 'DeepSeek V4 Pro', provider: 'deepseek', released: '2026-08-13', context: 1000000, maxOutput: 384000, priceIn: 1.32, priceOut: 3.96, caps: ['reasoning', 'tools', 'caching'], note: '1.6T MoE, 49B active per token.' },
  { id: 'grok-4.6', name: 'Grok 4.6', provider: 'xai', released: '2026-08-12', context: 500000, maxOutput: 500000, priceIn: 2, priceOut: 6, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'Coding and agentic flagship, 500K context.' },
  { id: 'qwen3.8-max', name: 'Qwen3.8-Max', provider: 'qwen', released: '2026-08-03', context: 991808, maxOutput: 131072, priceIn: 2, priceOut: 6, caps: ['reasoning', 'vision', 'tools', 'caching'], note: '2.4T MoE, 95B active, 1M context.' },
  { id: 'deepseek-v4-flash', name: 'DeepSeek V4 Flash', provider: 'deepseek', released: '2026-07-31', context: 1000000, maxOutput: 16384, priceIn: 0.3, priceOut: 1.2, caps: ['reasoning', 'vision', 'tools', 'caching'], note: '284B MoE, 13B active per token.' },
  { id: 'claude-opus-5', name: 'Claude Opus 5', provider: 'anthropic', released: '2026-07-24', context: 1000000, maxOutput: 128000, priceIn: 5, priceOut: 25, caps: ['reasoning', 'vision', 'tools', 'caching'], note: 'Near-frontier at half the Fable price.' },
  { id: 'gemini-3.6-flash', name: 'Gemini 3.6 Flash', provider: 'google', released: '2026-07-21', context: 1048576, maxOutput: 65536, priceIn: 0.75, priceOut: 3.75, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'gemini-3.5-flash-lite', name: 'Gemini 3.5 Flash-Lite', provider: 'google', released: '2026-07-21', context: 1048576, maxOutput: 65536, priceIn: 0.3, priceOut: 2.5, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'Lowest-latency Gemini.' },
  { id: 'kimi-k3', name: 'Kimi K3', provider: 'moonshot', released: '2026-07-16', context: 1048576, maxOutput: 1048576, priceIn: 3, priceOut: 15, caps: ['reasoning', 'vision', 'tools'], note: '1M context, 2.8T open-weight.' },
  { id: 'gpt-5.6-terra', name: 'GPT-5.6 Terra', provider: 'openai', released: '2026-07-09', context: 922000, maxOutput: 128000, priceIn: 2, priceOut: 12, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'Balanced tier, roughly GPT-5.5 performance for less.' },
  { id: 'gpt-5.6-sol', name: 'GPT-5.6 Sol', provider: 'openai', released: '2026-07-09', context: 922000, maxOutput: 128000, priceIn: 4, priceOut: 20, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'Flagship tier of the 5.6 family.' },
  { id: 'gpt-5.6-luna', name: 'GPT-5.6 Luna', provider: 'openai', released: '2026-07-09', context: 922000, maxOutput: 128000, priceIn: 0.2, priceOut: 1.2, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'The high-volume tier of the 5.6 family.' },
  { id: 'grok-4.5', name: 'Grok 4.5', provider: 'xai', released: '2026-07-08', context: 500000, maxOutput: 500000, priceIn: 2, priceOut: 6, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'claude-sonnet-5', name: 'Claude Sonnet 5', provider: 'anthropic', released: '2026-06-30', context: 1000000, maxOutput: 128000, priceIn: 2, priceOut: 10, caps: ['reasoning', 'vision', 'tools', 'caching'], note: 'The everyday workhorse of the Claude line.' },
  { id: 'glm-5.2', name: 'GLM-5.2', provider: 'zai', released: '2026-06-16', context: 1000000, maxOutput: 128000, priceIn: 1.4, priceOut: 4.4, caps: ['reasoning', 'tools', 'caching'], note: null },
  { id: 'claude-mythos-5', name: 'Claude Mythos 5', provider: 'anthropic', released: '2026-06-09', context: 1000000, maxOutput: 128000, priceIn: 10, priceOut: 50, caps: ['reasoning', 'vision', 'tools', 'caching'], note: 'Long-form writing sibling of Fable 5.' },
  { id: 'claude-fable-5', name: 'Claude Fable 5', provider: 'anthropic', released: '2026-06-09', context: 1000000, maxOutput: 128000, priceIn: 10, priceOut: 50, caps: ['reasoning', 'vision', 'tools', 'caching'], note: 'First of the Claude 5 generation.' },
  { id: 'MiniMax-M3', name: 'MiniMax M3', provider: 'minimax', released: '2026-06-01', context: 1000000, maxOutput: 128000, priceIn: 0.3, priceOut: 1.2, caps: ['reasoning', 'vision', 'tools', 'caching'], note: '428B MoE, 1M context, multimodal.' },
  { id: 'kimi-k2.7-code', name: 'Kimi K2.7 Code', provider: 'moonshot', released: '2026-06', context: 262144, maxOutput: 262144, priceIn: 0.95, priceOut: 4, caps: ['reasoning', 'vision', 'tools', 'caching'], note: null },
  { id: 'claude-opus-4-8', name: 'Claude Opus 4.8', provider: 'anthropic', released: '2026-05-28', context: 1000000, maxOutput: 128000, priceIn: 5, priceOut: 25, caps: ['reasoning', 'vision', 'tools', 'caching'], note: null },
  { id: 'qwen3.7-max', name: 'Qwen3.7-Max', provider: 'qwen', released: '2026-05-20', context: 991808, maxOutput: 65536, priceIn: 2.5, priceOut: 7.5, caps: ['reasoning', 'tools', 'caching'], note: null },
  { id: 'gemini-3.5-flash', name: 'Gemini 3.5 Flash', provider: 'google', released: '2026-05-19', context: 1048576, maxOutput: 65536, priceIn: 1.5, priceOut: 9, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'Shipped at Google I/O 2026.' },
  { id: 'qwen3.7-plus', name: 'Qwen3.7-Plus', provider: 'qwen', released: '2026-05', context: 991808, maxOutput: 65536, priceIn: 0.4, priceOut: 1.6, caps: ['reasoning', 'vision', 'tools', 'caching'], note: null },
  { id: 'grok-build-0.1', name: 'Grok Build 0.1', provider: 'xai', released: '2026-05', context: 256000, maxOutput: 256000, priceIn: 1, priceOut: 2, caps: ['reasoning', 'vision', 'tools', 'caching'], note: 'Replaced Grok Code Fast for code.' },
  { id: 'mistral-medium-3-5', name: 'Mistral Medium 3.5', provider: 'mistral', released: '2026-04-30', context: 262144, maxOutput: 262144, priceIn: 1.5, priceOut: 7.5, caps: ['reasoning', 'vision', 'tools'], note: null },
  { id: 'gpt-5.5', name: 'GPT-5.5', provider: 'openai', released: '2026-04-23', context: 1050000, maxOutput: 128000, priceIn: 5, priceOut: 30, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'kimi-k2.6', name: 'Kimi K2.6', provider: 'moonshot', released: '2026-04-20', context: 262144, maxOutput: 262144, priceIn: 0.95, priceOut: 4, caps: ['reasoning', 'vision', 'tools'], note: null },
  { id: 'claude-opus-4-7', name: 'Claude Opus 4.7', provider: 'anthropic', released: '2026-04-16', context: 1000000, maxOutput: 128000, priceIn: 5, priceOut: 25, caps: ['reasoning', 'vision', 'tools', 'caching'], note: null },
  { id: 'glm-5.1', name: 'GLM-5.1', provider: 'zai', released: '2026-04-07', context: 200000, maxOutput: 128000, priceIn: 1.4, priceOut: 4.4, caps: ['reasoning', 'tools', 'caching'], note: null },
  { id: 'grok-4.3', name: 'Grok 4.3', provider: 'xai', released: '2026-04', context: 1000000, maxOutput: 1000000, priceIn: 1.25, priceOut: 2.5, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: '1M context, native video input.' },
  { id: 'MiniMax-M2.7', name: 'MiniMax M2.7', provider: 'minimax', released: '2026-03-18', context: 204800, maxOutput: 131072, priceIn: 0.3, priceOut: 1.2, caps: ['reasoning', 'tools', 'caching'], note: 'Self-evolving agent model.' },
  { id: 'gpt-5.4-nano', name: 'GPT-5.4 nano', provider: 'openai', released: '2026-03-17', context: 272000, maxOutput: 128000, priceIn: 0.2, priceOut: 1.25, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'gpt-5.4-mini', name: 'GPT-5.4 mini', provider: 'openai', released: '2026-03-17', context: 272000, maxOutput: 128000, priceIn: 0.75, priceOut: 4.5, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'grok-4.20-0309-reasoning', name: 'Grok 4.20 Reasoning', provider: 'xai', released: '2026-03-09', context: 1000000, maxOutput: 1000000, priceIn: 1.25, priceOut: 2.5, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'gpt-5.4', name: 'GPT-5.4', provider: 'openai', released: '2026-03-05', context: 1050000, maxOutput: 128000, priceIn: 2.5, priceOut: 15, caps: ['reasoning', 'vision', 'tools', 'caching'], note: null },
  { id: 'mistral-small-2603', name: 'Mistral Small (2603)', provider: 'mistral', released: '2026-03', context: 262144, maxOutput: 262144, priceIn: 0.15, priceOut: 0.6, caps: ['reasoning', 'vision', 'tools'], note: null },
  { id: 'gemini-3.1-flash-lite', name: 'Gemini 3.1 Flash-Lite', provider: 'google', released: '2026-03', context: 1048576, maxOutput: 65536, priceIn: 0.25, priceOut: 1.5, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: null },
  { id: 'gemini-3.1-pro-preview', name: 'Gemini 3.1 Pro', provider: 'google', released: '2026-02-19', context: 1048576, maxOutput: 65536, priceIn: 2, priceOut: 12, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'Newest Pro-tier Gemini in the API.' },
  { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6', provider: 'anthropic', released: '2026-02-17', context: 1000000, maxOutput: 128000, priceIn: 3, priceOut: 15, caps: ['reasoning', 'vision', 'tools', 'caching'], note: null },
  { id: 'glm-5', name: 'GLM-5', provider: 'zai', released: '2026-02-12', context: 200000, maxOutput: 128000, priceIn: 1, priceOut: 3.2, caps: ['reasoning', 'tools', 'caching'], note: null },
  { id: 'MiniMax-M2.5', name: 'MiniMax M2.5', provider: 'minimax', released: '2026-02-12', context: 1000000, maxOutput: 8192, priceIn: 0.3, priceOut: 1.2, caps: ['reasoning', 'tools', 'caching'], note: null },
  { id: 'claude-opus-4-6', name: 'Claude Opus 4.6', provider: 'anthropic', released: '2026-02-05', context: 1000000, maxOutput: 128000, priceIn: 5, priceOut: 25, caps: ['reasoning', 'vision', 'tools', 'caching'], note: null },
  { id: 'qwen3.5-plus', name: 'Qwen3.5-Plus', provider: 'qwen', released: '2026-02', context: 991808, maxOutput: 65536, priceIn: 0.4, priceOut: 2.4, caps: ['reasoning', 'vision', 'tools'], note: null },
  { id: 'kimi-k2.5', name: 'Kimi K2.5', provider: 'moonshot', released: '2026-01-27', context: 262144, maxOutput: 262144, priceIn: 0.6, priceOut: 3, caps: ['reasoning', 'vision', 'tools'], note: 'Native multimodal with thinking.' },
  { id: 'MiniMax-M2.1', name: 'MiniMax M2.1', provider: 'minimax', released: '2025-12-23', context: 1000000, maxOutput: 8192, priceIn: 0.3, priceOut: 1.2, caps: ['reasoning', 'tools', 'caching'], note: null },
  { id: 'glm-4.7', name: 'GLM-4.7', provider: 'zai', released: '2025-12-22', context: 200000, maxOutput: 128000, priceIn: 0.6, priceOut: 2.2, caps: ['reasoning', 'tools', 'caching'], note: null },
  { id: 'glm-4.6v', name: 'GLM-4.6V', provider: 'zai', released: '2025-12-08', context: 131072, maxOutput: 32768, priceIn: 0.3, priceOut: 0.9, caps: ['reasoning', 'vision', 'tools', 'caching'], note: null },
  { id: 'mistral-large-3', name: 'Mistral Large 3', provider: 'mistral', released: '2025-12-02', context: 262144, maxOutput: 262144, priceIn: 0.5, priceOut: 1.5, caps: ['vision', 'tools'], note: '675B sparse MoE, 41B active.' },
  { id: 'ministral-3-14b-2512', name: 'Ministral 3 14B', provider: 'mistral', released: '2025-12', context: 262144, maxOutput: 262144, priceIn: 0.2, priceOut: 0.2, caps: ['vision', 'tools'], note: null },
  { id: 'devstral-2512', name: 'Devstral (2512)', provider: 'mistral', released: '2025-12', context: 256000, maxOutput: 256000, priceIn: 0.4, priceOut: 2, caps: ['tools'], note: null },
  { id: 'grok-4-1-fast', name: 'Grok 4.1 Fast', provider: 'xai', released: '2025-11-19', context: 2000000, maxOutput: 2000000, priceIn: 1.25, priceOut: 2.5, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: '2M context, the widest window we carry.' },
  { id: 'gemini-3-pro-preview', name: 'Gemini 3 Pro', provider: 'google', released: '2025-11-18', context: 1048576, maxOutput: 65535, priceIn: 2, priceOut: 12, caps: ['reasoning', 'vision', 'tools', 'caching', 'web'], note: 'Opened the Gemini 3 generation.' },
  { id: 'kimi-k2-thinking', name: 'Kimi K2 Thinking', provider: 'moonshot', released: '2025-11-06', context: 262144, maxOutput: 262144, priceIn: 0.6, priceOut: 2.5, caps: ['reasoning', 'tools', 'web'], note: '200-300 sequential tool calls.' },
  { id: 'claude-haiku-4-5', name: 'Claude Haiku 4.5', provider: 'anthropic', released: '2025-10-15', context: 200000, maxOutput: 64000, priceIn: 1, priceOut: 5, caps: ['reasoning', 'vision', 'tools', 'caching'], note: 'Cheapest Claude, still tool-capable.' },
  { id: 'MiniMax-M2', name: 'MiniMax M2', provider: 'minimax', released: '2025-10', context: 200000, maxOutput: 8192, priceIn: 0.3, priceOut: 1.2, caps: ['reasoning', 'tools', 'caching'], note: 'Open-source agentic model.' },
  { id: 'glm-4.6', name: 'GLM-4.6', provider: 'zai', released: '2025-09-30', context: 200000, maxOutput: 128000, priceIn: 0.6, priceOut: 2.2, caps: ['reasoning', 'tools', 'caching'], note: null },
  { id: 'qwen3-vl-235b-a22b-thinking', name: 'Qwen3-VL 235B Thinking', provider: 'qwen', released: '2025-09-23', context: 131072, maxOutput: 32768, priceIn: 0.4, priceOut: 4, caps: ['reasoning', 'vision', 'tools'], note: null },
  { id: 'qwen3-vl-235b-a22b-instruct', name: 'Qwen3-VL 235B Instruct', provider: 'qwen', released: '2025-09-23', context: 131072, maxOutput: 32768, priceIn: 0.4, priceOut: 1.6, caps: ['vision', 'tools'], note: 'Open multimodal flagship.' },
  { id: 'qwen3-next-80b-a3b-thinking', name: 'Qwen3-Next 80B Thinking', provider: 'qwen', released: '2025-09-11', context: 262144, maxOutput: 65536, priceIn: 0.15, priceOut: 1.2, caps: ['reasoning', 'tools'], note: null },
  { id: 'qwen3-next-80b-a3b-instruct', name: 'Qwen3-Next 80B Instruct', provider: 'qwen', released: '2025-09-11', context: 262144, maxOutput: 65536, priceIn: 0.15, priceOut: 1.2, caps: ['tools'], note: null },
  { id: 'kimi-k2-0905-preview', name: 'Kimi K2 (0905)', provider: 'moonshot', released: '2025-09-05', context: 262144, maxOutput: 262144, priceIn: 0.6, priceOut: 2.5, caps: ['tools', 'web'], note: null },
  { id: 'qwen3-max', name: 'Qwen3-Max', provider: 'qwen', released: '2025-09', context: 258048, maxOutput: 65536, priceIn: 1.2, priceOut: 6, caps: ['reasoning', 'tools'], note: null },
  { id: 'magistral-medium-1-2-2509', name: 'Magistral Medium 1.2', provider: 'mistral', released: '2025-09', context: 40000, maxOutput: 40000, priceIn: 2, priceOut: 5, caps: ['reasoning', 'tools'], note: null },
  { id: 'grok-4-fast-reasoning', name: 'Grok 4 Fast Reasoning', provider: 'xai', released: '2025-09', context: 2000000, maxOutput: 2000000, priceIn: 1.25, priceOut: 2.5, caps: ['tools', 'caching', 'web'], note: null },
  { id: 'grok-code-fast-1', name: 'Grok Code Fast 1', provider: 'xai', released: '2025-08-25', context: 256000, maxOutput: 256000, priceIn: 1, priceOut: 2, caps: ['reasoning', 'vision', 'tools', 'caching'], note: 'Cheap, fast, code-shaped.' },
  { id: 'glm-4.5v', name: 'GLM-4.5V', provider: 'zai', released: '2025-08', context: 128000, maxOutput: 32000, priceIn: 0.6, priceOut: 1.8, caps: ['vision', 'tools'], note: null },
  { id: 'codestral-2508', name: 'Codestral (2508)', provider: 'mistral', released: '2025-08', context: 128000, maxOutput: 128000, priceIn: 0.3, priceOut: 0.9, caps: ['tools'], note: 'Mistral\'s code-completion model.' },
  { id: 'qwen3-coder-plus', name: 'Qwen3-Coder Plus', provider: 'qwen', released: '2025-07-24', context: 997952, maxOutput: 65536, priceIn: 1, priceOut: 5, caps: ['reasoning', 'tools'], note: null },
  { id: 'kimi-k2-0711-preview', name: 'Kimi K2 (0711)', provider: 'moonshot', released: '2025-07-11', context: 131072, maxOutput: 131072, priceIn: 0.6, priceOut: 2.5, caps: ['tools', 'web'], note: '1T MoE open weights.' },
  { id: 'grok-4', name: 'Grok 4', provider: 'xai', released: '2025-07-09', context: 256000, maxOutput: 256000, priceIn: 1.25, priceOut: 2.5, caps: ['tools', 'caching', 'web'], note: null },
  { id: 'glm-4.5-air', name: 'GLM-4.5 Air', provider: 'zai', released: '2025-07', context: 128000, maxOutput: 32000, priceIn: 0.2, priceOut: 1.1, caps: ['tools'], note: 'The cheap open-weights sibling.' },
  { id: 'glm-4.5', name: 'GLM-4.5', provider: 'zai', released: '2025-07', context: 128000, maxOutput: 32000, priceIn: 0.6, priceOut: 2.2, caps: ['tools'], note: null },
  { id: 'devstral-medium-2507', name: 'Devstral Medium', provider: 'mistral', released: '2025-07', context: 128000, maxOutput: 128000, priceIn: 0.4, priceOut: 2, caps: ['tools'], note: null },
  { id: 'mistral-small-3-2-2506', name: 'Mistral Small 3.2', provider: 'mistral', released: '2025-06', context: 131072, maxOutput: 131072, priceIn: 0.06, priceOut: 0.18, caps: ['vision', 'tools'], note: null },
  { id: 'magistral-medium-2506', name: 'Magistral Medium', provider: 'mistral', released: '2025-06', context: 40000, maxOutput: 40000, priceIn: 2, priceOut: 5, caps: ['reasoning', 'tools'], note: 'Mistral\'s first reasoning model.' },
  { id: 'mistral-medium-2505', name: 'Mistral Medium 3', provider: 'mistral', released: '2025-05', context: 131072, maxOutput: 8191, priceIn: 0.4, priceOut: 2, caps: ['tools'], note: null },
  { id: 'glm-4-32b-0414-128k', name: 'GLM-4 32B', provider: 'zai', released: '2025-04-14', context: 128000, maxOutput: 32000, priceIn: 0.1, priceOut: 0.1, caps: ['tools'], note: null },
  { id: 'sonar-reasoning-pro', name: 'Sonar Reasoning Pro', provider: 'perplexity', released: '2025-03-07', context: 128000, maxOutput: null, priceIn: 2, priceOut: 8, caps: [], note: 'Search-grounded reasoning.' },
  { id: 'qwq-plus', name: 'QwQ Plus', provider: 'qwen', released: '2025-03', context: 98304, maxOutput: 8192, priceIn: 0.8, priceOut: 2.4, caps: ['reasoning', 'tools'], note: 'Qwen\'s first reasoning line.' },
  { id: 'command-a-03-2025', name: 'Command A', provider: 'cohere', released: '2025-03', context: 256000, maxOutput: 8000, priceIn: 2.5, priceOut: 10, caps: ['tools'], note: null },
  { id: 'grok-3-mini', name: 'Grok 3 mini', provider: 'xai', released: '2025-02-17', context: 131072, maxOutput: 131072, priceIn: 1.25, priceOut: 2.5, caps: ['reasoning', 'tools', 'caching', 'web'], note: null },
  { id: 'grok-3', name: 'Grok 3', provider: 'xai', released: '2025-02-17', context: 131072, maxOutput: 131072, priceIn: 1.25, priceOut: 2.5, caps: ['tools', 'caching', 'web'], note: null },
  { id: 'sonar-pro', name: 'Sonar Pro', provider: 'perplexity', released: '2025-01', context: 200000, maxOutput: null, priceIn: 3, priceOut: 15, caps: [], note: 'Answers with live web citations.' },
  { id: 'grok-2-1212', name: 'Grok 2 (1212)', provider: 'xai', released: '2024-12-12', context: 131072, maxOutput: 131072, priceIn: 2, priceOut: 10, caps: ['tools', 'web'], note: null },
  { id: 'command-r7b-12-2024', name: 'Command R7B', provider: 'cohere', released: '2024-12', context: 128000, maxOutput: 4096, priceIn: 0.0375, priceOut: 0.15, caps: ['tools'], note: null },
  { id: 'pixtral-large-2411', name: 'Pixtral Large', provider: 'mistral', released: '2024-11', context: 128000, maxOutput: 128000, priceIn: 2, priceOut: 6, caps: ['vision', 'tools'], note: 'Mistral\'s large vision model.' },
  { id: 'command-r-plus-08-2024', name: 'Command R+ (08-2024)', provider: 'cohere', released: '2024-08', context: 128000, maxOutput: 4096, priceIn: 2.5, priceOut: 10, caps: ['tools'], note: null },
  { id: 'command-r-08-2024', name: 'Command R (08-2024)', provider: 'cohere', released: '2024-08', context: 128000, maxOutput: 4096, priceIn: 0.15, priceOut: 0.6, caps: ['tools'], note: null },
  { id: 'mistral-large-2407', name: 'Mistral Large 2', provider: 'mistral', released: '2024-07', context: 128000, maxOutput: 128000, priceIn: 3, priceOut: 9, caps: ['tools'], note: null },
  { id: 'moonshot-v1-128k', name: 'Moonshot v1 128K', provider: 'moonshot', released: '2024-04-30', context: 131072, maxOutput: 131072, priceIn: 2, priceOut: 5, caps: ['tools'], note: null },
  { id: 'open-mixtral-8x22b', name: 'Mixtral 8x22B', provider: 'mistral', released: '2024-04', context: 65336, maxOutput: 8191, priceIn: 2, priceOut: 6, caps: ['tools'], note: 'Open-weights sparse MoE.' },
  { id: 'open-mixtral-8x7b', name: 'Mixtral 8x7B', provider: 'mistral', released: '2023-12-11', context: 32000, maxOutput: 8191, priceIn: 0.7, priceOut: 0.7, caps: ['tools'], note: 'The MoE release that started the wave.' },
];
