package com.apimarketplace.agent.domain;

import com.apimarketplace.common.scope.OrgScopedEntity;
import com.apimarketplace.common.scope.OrgScopedEntityListener;
import jakarta.persistence.*;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.data.domain.Persistable;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * JPA entity for the agent_executions table.
 * One row per agent node execution with pre-computed counters.
 * Implements Persistable so that Spring Data uses persist() (not merge())
 * when the ID is pre-generated by AgentNode.
 */
@Entity
@EntityListeners(OrgScopedEntityListener.class)
@Table(name = "agent_executions")
@DynamicUpdate
public class AgentExecutionEntity implements Persistable<UUID>, OrgScopedEntity {

    @Id
    private UUID id;

    @Transient
    private boolean isNew = true;

    @Column(name = "tenant_id", nullable = false)
    private String tenantId;

    /**
     * Workspace the execution ran in. NULL = personal scope.
     * PR20 strict-isolation: org workspace sees org_id = :orgId only;
     * personal workspace sees org_id IS NULL only. No mixing.
     */
    @Column(name = "organization_id")
    private String organizationId;

    // Link to existing workflow context
    @Column(name = "step_data_id")
    private Long stepDataId;

    @Column(name = "workflow_id")
    private UUID workflowId;

    @Column(name = "workflow_run_id")
    private UUID workflowRunId;

    @Column(name = "run_id")
    private String runId;

    @Column(name = "node_id")
    private String nodeId;

    // Link to agent entity (SET NULL on delete to preserve history)
    @Column(name = "agent_entity_id")
    private UUID agentEntityId;

    // Execution context
    @Column(name = "agent_type", nullable = false, length = 20)
    private String agentType = "agent";

    @Column(name = "epoch", nullable = false)
    private int epoch = 0;

    @Column(name = "spawn", nullable = false)
    private int spawn = 0;

    @Column(name = "item_index", nullable = false)
    private int itemIndex = 0;

    @Column(name = "loop_iteration")
    private Integer loopIteration;

    // Outcome
    @Column(name = "status", nullable = false, length = 20)
    private String status = "RUNNING";

    @Column(name = "stop_reason", length = 30)
    private String stopReason;

    /**
     * Budget guard scope - populated only when {@link #stopReason} is BUDGET_EXHAUSTED.
     * 'tenant' = tenant balance ran out; 'agent' = per-agent quota exhausted.
     * Sourced from the run metrics map (key: budgetScope) set by AgentLoopService.
     */
    @Column(name = "budget_scope", length = 10)
    private String budgetScope;

    @Column(name = "error_message", columnDefinition = "text")
    private String errorMessage;

    // LLM config snapshot
    @Column(name = "provider", length = 50)
    private String provider;

    @Column(name = "model", length = 100)
    private String model;

    @Column(name = "temperature", precision = 3, scale = 2)
    private BigDecimal temperature;

    @Column(name = "max_tokens_config")
    private Integer maxTokensConfig;

    @Column(name = "max_iterations_config")
    private Integer maxIterationsConfig;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "agent_config_snapshot", columnDefinition = "jsonb")
    private Map<String, Object> agentConfigSnapshot;

    // Pre-computed counters
    @Column(name = "iteration_count", nullable = false)
    private int iterationCount = 0;

    @Column(name = "total_tool_calls", nullable = false)
    private int totalToolCalls = 0;

    @Column(name = "successful_tool_calls", nullable = false)
    private int successfulToolCalls = 0;

    @Column(name = "failed_tool_calls", nullable = false)
    private int failedToolCalls = 0;

    @Column(name = "message_count", nullable = false)
    private int messageCount = 0;

    @Column(name = "initial_history_size", nullable = false)
    private int initialHistorySize = 0;

    // Token usage
    @Column(name = "total_prompt_tokens", nullable = false)
    private int totalPromptTokens = 0;

    @Column(name = "total_completion_tokens", nullable = false)
    private int totalCompletionTokens = 0;

    @Column(name = "total_tokens", nullable = false)
    private int totalTokens = 0;

    // Extended token tracking
    @Column(name = "total_cache_creation_tokens", nullable = false)
    private int totalCacheCreationTokens = 0;

    @Column(name = "total_cache_read_tokens", nullable = false)
    private int totalCacheReadTokens = 0;

    @Column(name = "total_cached_tokens", nullable = false)
    private int totalCachedTokens = 0;

    @Column(name = "total_reasoning_tokens", nullable = false)
    private int totalReasoningTokens = 0;

    // Timing
    @Column(name = "started_at", nullable = false)
    private Instant startedAt;

    @Column(name = "ended_at")
    private Instant endedAt;

    @Column(name = "duration_ms")
    private Long durationMs;

    // Tool pattern tracking
    @Column(name = "tool_sequence", columnDefinition = "text")
    private String toolSequence;

    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "distinct_tools", columnDefinition = "text[]")
    private String[] distinctTools;

    @Column(name = "loop_detected", nullable = false)
    private boolean loopDetected = false;

    @Column(name = "loop_type", length = 20)
    private String loopType;

    @Column(name = "loop_tool_name", length = 255)
    private String loopToolName;

    @Column(name = "system_prompt", columnDefinition = "text")
    private String systemPrompt;

    // Credits consumed by this execution
    @Column(name = "credits_consumed", nullable = false, precision = 15, scale = 4)
    private BigDecimal creditsConsumed = BigDecimal.ZERO;

    @Column(name = "source", nullable = false, length = 20)
    private String source = "WORKFLOW";

    // Sub-agent tracking
    @Column(name = "caller_agent_entity_id")
    private UUID callerAgentEntityId;

    @Column(name = "depth", nullable = false)
    private int depth = 0;

    @Column(name = "conversation_id")
    private String conversationId;

    /**
     * Conversation that SPAWNED this sub-agent execution (the parent's conversation),
     * distinct from {@link #conversationId} which is the sub-agent's own dedicated
     * conversation. Nullable - only populated on sub-agent spawns; NULL for root
     * (REST/CLI/chat/workflow) executions. Lets a conversation-scoped observability
     * view surface the executions of sub-agents the parent spawned.
     */
    @Column(name = "parent_conversation_id")
    private String parentConversationId;

    @Column(name = "memory_enabled")
    private Boolean memoryEnabled;

    /** Link to agent task (nullable - only populated when execution is task-driven). */
    @Column(name = "task_id")
    private UUID taskId;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    public AgentExecutionEntity() {
    }

    @PrePersist
    private void onCreate() {
        if (this.id == null) {
            this.id = UUID.randomUUID();
        }
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.startedAt == null) {
            this.startedAt = now;
        }
    }

    // ── Persistable implementation ─────────────────────────────────

    @Override
    public UUID getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostLoad
    @PostPersist
    void markNotNew() {
        this.isNew = false;
    }

    // Getters and Setters

    public void setId(UUID id) {
        this.id = id;
    }

    public String getTenantId() {
        return tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    public Long getStepDataId() {
        return stepDataId;
    }

    public void setStepDataId(Long stepDataId) {
        this.stepDataId = stepDataId;
    }

    public UUID getWorkflowId() {
        return workflowId;
    }

    public void setWorkflowId(UUID workflowId) {
        this.workflowId = workflowId;
    }

    public UUID getWorkflowRunId() {
        return workflowRunId;
    }

    public void setWorkflowRunId(UUID workflowRunId) {
        this.workflowRunId = workflowRunId;
    }

    public String getRunId() {
        return runId;
    }

    public void setRunId(String runId) {
        this.runId = runId;
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public UUID getAgentEntityId() {
        return agentEntityId;
    }

    public void setAgentEntityId(UUID agentEntityId) {
        this.agentEntityId = agentEntityId;
    }

    public String getAgentType() {
        return agentType;
    }

    public void setAgentType(String agentType) {
        this.agentType = agentType;
    }

    public int getEpoch() {
        return epoch;
    }

    public void setEpoch(int epoch) {
        this.epoch = epoch;
    }

    public int getSpawn() {
        return spawn;
    }

    public void setSpawn(int spawn) {
        this.spawn = spawn;
    }

    public int getItemIndex() {
        return itemIndex;
    }

    public void setItemIndex(int itemIndex) {
        this.itemIndex = itemIndex;
    }

    public Integer getLoopIteration() {
        return loopIteration;
    }

    public void setLoopIteration(Integer loopIteration) {
        this.loopIteration = loopIteration;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStopReason() {
        return stopReason;
    }

    public void setStopReason(String stopReason) {
        this.stopReason = stopReason;
    }

    public String getBudgetScope() {
        return budgetScope;
    }

    public void setBudgetScope(String budgetScope) {
        this.budgetScope = budgetScope;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public BigDecimal getTemperature() {
        return temperature;
    }

    public void setTemperature(BigDecimal temperature) {
        this.temperature = temperature;
    }

    public Integer getMaxTokensConfig() {
        return maxTokensConfig;
    }

    public void setMaxTokensConfig(Integer maxTokensConfig) {
        this.maxTokensConfig = maxTokensConfig;
    }

    public Integer getMaxIterationsConfig() {
        return maxIterationsConfig;
    }

    public void setMaxIterationsConfig(Integer maxIterationsConfig) {
        this.maxIterationsConfig = maxIterationsConfig;
    }

    public Map<String, Object> getAgentConfigSnapshot() {
        return agentConfigSnapshot;
    }

    public void setAgentConfigSnapshot(Map<String, Object> agentConfigSnapshot) {
        this.agentConfigSnapshot = agentConfigSnapshot;
    }

    public int getIterationCount() {
        return iterationCount;
    }

    public void setIterationCount(int iterationCount) {
        this.iterationCount = iterationCount;
    }

    public int getTotalToolCalls() {
        return totalToolCalls;
    }

    public void setTotalToolCalls(int totalToolCalls) {
        this.totalToolCalls = totalToolCalls;
    }

    public int getSuccessfulToolCalls() {
        return successfulToolCalls;
    }

    public void setSuccessfulToolCalls(int successfulToolCalls) {
        this.successfulToolCalls = successfulToolCalls;
    }

    public int getFailedToolCalls() {
        return failedToolCalls;
    }

    public void setFailedToolCalls(int failedToolCalls) {
        this.failedToolCalls = failedToolCalls;
    }

    public int getMessageCount() {
        return messageCount;
    }

    public void setMessageCount(int messageCount) {
        this.messageCount = messageCount;
    }

    public int getInitialHistorySize() {
        return initialHistorySize;
    }

    public void setInitialHistorySize(int initialHistorySize) {
        this.initialHistorySize = initialHistorySize;
    }

    public int getTotalPromptTokens() {
        return totalPromptTokens;
    }

    public void setTotalPromptTokens(int totalPromptTokens) {
        this.totalPromptTokens = totalPromptTokens;
    }

    public int getTotalCompletionTokens() {
        return totalCompletionTokens;
    }

    public void setTotalCompletionTokens(int totalCompletionTokens) {
        this.totalCompletionTokens = totalCompletionTokens;
    }

    public int getTotalTokens() {
        return totalTokens;
    }

    public void setTotalTokens(int totalTokens) {
        this.totalTokens = totalTokens;
    }

    public int getTotalCacheCreationTokens() {
        return totalCacheCreationTokens;
    }

    public void setTotalCacheCreationTokens(int totalCacheCreationTokens) {
        this.totalCacheCreationTokens = totalCacheCreationTokens;
    }

    public int getTotalCacheReadTokens() {
        return totalCacheReadTokens;
    }

    public void setTotalCacheReadTokens(int totalCacheReadTokens) {
        this.totalCacheReadTokens = totalCacheReadTokens;
    }

    public int getTotalCachedTokens() {
        return totalCachedTokens;
    }

    public void setTotalCachedTokens(int totalCachedTokens) {
        this.totalCachedTokens = totalCachedTokens;
    }

    public int getTotalReasoningTokens() {
        return totalReasoningTokens;
    }

    public void setTotalReasoningTokens(int totalReasoningTokens) {
        this.totalReasoningTokens = totalReasoningTokens;
    }

    public Instant getStartedAt() {
        return startedAt;
    }

    public void setStartedAt(Instant startedAt) {
        this.startedAt = startedAt;
    }

    public Instant getEndedAt() {
        return endedAt;
    }

    public void setEndedAt(Instant endedAt) {
        this.endedAt = endedAt;
    }

    public Long getDurationMs() {
        return durationMs;
    }

    public void setDurationMs(Long durationMs) {
        this.durationMs = durationMs;
    }

    public String getToolSequence() {
        return toolSequence;
    }

    public void setToolSequence(String toolSequence) {
        this.toolSequence = toolSequence;
    }

    public List<String> getDistinctTools() {
        return distinctTools == null ? null : List.of(distinctTools);
    }

    public void setDistinctTools(List<String> distinctTools) {
        this.distinctTools = distinctTools == null ? null : distinctTools.toArray(String[]::new);
    }

    public boolean isLoopDetected() {
        return loopDetected;
    }

    public void setLoopDetected(boolean loopDetected) {
        this.loopDetected = loopDetected;
    }

    public String getLoopType() {
        return loopType;
    }

    public void setLoopType(String loopType) {
        this.loopType = loopType;
    }

    public String getLoopToolName() {
        return loopToolName;
    }

    public void setLoopToolName(String loopToolName) {
        this.loopToolName = loopToolName;
    }

    public String getSystemPrompt() {
        return systemPrompt;
    }

    public void setSystemPrompt(String systemPrompt) {
        this.systemPrompt = systemPrompt;
    }

    public BigDecimal getCreditsConsumed() {
        return creditsConsumed;
    }

    public void setCreditsConsumed(BigDecimal creditsConsumed) {
        this.creditsConsumed = creditsConsumed;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public UUID getCallerAgentEntityId() {
        return callerAgentEntityId;
    }

    public void setCallerAgentEntityId(UUID callerAgentEntityId) {
        this.callerAgentEntityId = callerAgentEntityId;
    }

    public int getDepth() {
        return depth;
    }

    public void setDepth(int depth) {
        this.depth = depth;
    }

    public String getConversationId() {
        return conversationId;
    }

    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }

    public String getParentConversationId() {
        return parentConversationId;
    }

    public void setParentConversationId(String parentConversationId) {
        this.parentConversationId = parentConversationId;
    }

    public Boolean getMemoryEnabled() {
        return memoryEnabled;
    }

    public void setMemoryEnabled(Boolean memoryEnabled) {
        this.memoryEnabled = memoryEnabled;
    }

    public UUID getTaskId() {
        return taskId;
    }

    public void setTaskId(UUID taskId) {
        this.taskId = taskId;
    }
}
