-- ============================================================================
-- V410: core:media v2 - document the video-suite operations (concat, frame,
--   overlay) added to the media node:
--     - concat: glue 1-8 videos back to back into one mp4 (per-clip trim/speed,
--       cut or crossfade transitions, optional target canvas/fps, global fades,
--       loudness normalisation defaulting OFF).
--     - frame: extract ONE still image (default the MIDDLE of the video,
--       clamped at the end), new output timestamp_seconds.
--     - overlay: burn an image (logo/watermark/badge) onto a video.
--   v1 operations (probe, mux_audio, mix, extract_audio) are unchanged; this
--   refreshes the media row's description, parameters, outputs, concepts,
--   examples and keywords in place.
-- ============================================================================

SET search_path TO orchestrator;

UPDATE orchestrator.node_type_documentation SET
    description = 'Processes audio/video files produced by upstream nodes. Seven operations via the ''operation'' param: probe (read a file''s metadata as flat output fields), mux_audio (put ONE audio track onto ONE video, the common case), mix (mix 1 to 8 audio tracks, optionally onto a video, with per-track volume/offset/speed and automatic ducking of one track under another), extract_audio (pull the audio track out of a video), concat (glue 1 to 8 videos back to back into one mp4, with per-clip trim/speed and cut or crossfade transitions; a SINGLE input is the trim/speed-edit use case), frame (extract ONE still image, by default the MIDDLE of the video), overlay (burn an image such as a logo or watermark onto a video). Every file param takes the WHOLE FileRef output of an upstream node as a whole-value template (e.g. {{core:download.output.file}} or {{interface:card.output.video}}) or a literal FileRef object, never .path or a URL string; all params accept {{...}} templates resolved at run time. Runs on the optional renderer component: when that component is not enabled on the installation the node FAILS at run time (validate warns with MEDIA_RENDERER_UNAVAILABLE). When emitting via set_plan, put the config under ''params''.',
    parameters = '{
      "operation":           {"type": "string", "required": true,  "description": "One of: probe, mux_audio, mix, extract_audio, concat, frame, overlay."},
      "input":               {"type": "string|object", "required": false, "description": "probe/extract_audio/frame: REQUIRED whole FileRef expression (or literal FileRef object from files action=get, field ref) of the file to read (video or audio for probe, video for extract_audio and frame)."},
      "video":               {"type": "string|object", "required": false, "description": "mux_audio: REQUIRED whole FileRef expression (or literal FileRef object) of the video. overlay: REQUIRED whole FileRef of the video the image is burned onto. mix: optional; when present the output is an mp4 with the video stream copied, when absent the mix is audio-only."},
      "audio":               {"type": "string|object", "required": false, "description": "mux_audio: REQUIRED whole FileRef expression (or literal FileRef object) of the audio track to put onto the video."},
      "image":               {"type": "string|object", "required": false, "description": "overlay: REQUIRED whole FileRef expression (or literal FileRef object) of the image to burn onto the video (png alpha respected, jpeg ok; the run fails if the file is not an image)."},
      "tracks":              {"type": "array",  "required": false, "description": "mix: REQUIRED array of 1-8 tracks. Each track: {source: whole FileRef expression (required), id: name for duck_under references (default track_1, track_2, ... in array order), volume: percent 0-400 (default 100), offset_seconds: start time >= 0 (default 0), trim_start_seconds/trim_end_seconds: use only this segment of the track, loop: boolean (default false), fade_in_seconds/fade_out_seconds: >= 0 (defaults 0/0), speed: 0.5-2.0 pitch-preserving (default 1.0), duck_under: id of ANOTHER track that this track automatically lowers under while it is audible, duck_amount_db (default 12), duck_attack_ms (default 20), duck_release_ms (default 300)}."},
      "inputs":              {"type": "array",  "required": false, "description": "concat: REQUIRED array of 1-8 clips glued in order. Each clip: {source: whole FileRef expression or literal FileRef object (required, string|object), trim_start_seconds: use the clip only FROM this second (>= 0, optional), trim_end_seconds: use the clip only UP TO this second (must be GREATER than trim_start_seconds, optional), speed: 0.5-2.0 pitch-preserving (default 1.0)}. A SINGLE clip is allowed: that is the trim/speed-edit use case."},
      "volume":              {"type": "number", "required": false, "default": 100, "description": "mux_audio: audio volume in percent, 0-400."},
      "offset_seconds":      {"type": "number", "required": false, "default": 0, "description": "mux_audio: the audio starts at this time on the video, >= 0."},
      "trim_start_seconds":  {"type": "number", "required": false, "description": "mux_audio/extract_audio: use only from this second of the audio, >= 0."},
      "trim_end_seconds":    {"type": "number", "required": false, "description": "mux_audio/extract_audio: use only up to this second of the audio, >= 0."},
      "loop":                {"type": "boolean", "required": false, "default": false, "description": "mux_audio: loop the audio to the video length (same effect as audio_fit ''loop''). Cannot be combined with trim_start_seconds/trim_end_seconds on the same audio or track."},
      "fade_in_seconds":     {"type": "number", "required": false, "default": 0, "description": "mux_audio/concat: fade-in duration in seconds, >= 0. concat applies it to the final RESULT."},
      "fade_out_seconds":    {"type": "number", "required": false, "description": "mux_audio/concat: fade-out duration in seconds, >= 0. Default 1.0 for mux_audio, 0 for concat (on purpose)."},
      "keep_original_audio": {"type": "boolean", "required": false, "default": false, "description": "mux_audio/mix (with video only): keep the video''s own audio MIXED under the new track(s)."},
      "original_volume":     {"type": "number", "required": false, "default": 100, "description": "Level of the kept original track in percent 0-400 (only with keep_original_audio true)."},
      "audio_fit":           {"type": "string", "required": false, "default": "pad", "description": "What happens when the audio is shorter/longer than the video: pad, shortest, or loop."},
      "normalize":           {"type": "boolean|number", "required": false, "description": "Loudness normalisation: true (target -16 LUFS), false (off), or a LUFS target number between -70 and -5. Default true for mux_audio/mix, FALSE for concat (set true to even out loudness between clips - it forces the re-encode path)."},
      "audio_bitrate":       {"type": "string", "required": false, "default": "192k", "description": "Output audio bitrate (re-encode path only for concat)."},
      "output_format":       {"type": "string", "required": false, "default": "mp3", "description": "extract_audio and audio-only mix: mp3, wav, or aac. Forced to mp4 when a video is present. concat and overlay always produce mp4."},
      "transition":          {"type": "string", "required": false, "default": "cut", "description": "concat: cut or crossfade. crossfade blends both video and audio between consecutive clips and requires at least 2 inputs."},
      "transition_seconds":  {"type": "number", "required": false, "default": 0.5, "description": "concat crossfade only: crossfade length, 0.1-5.0 seconds. Must be strictly shorter than every clip''s EFFECTIVE duration (after trim/speed) - the run fails naming the offending clip otherwise. Output duration = sum of effective durations - (N-1) x transition_seconds."},
      "target_width":        {"type": "number", "required": false, "description": "concat: output canvas width, 16-4096, provided together with target_height (BOTH or NEITHER; odd values are rounded down to even). Default: the FIRST input''s dimensions. Non-matching clips are scaled to FIT and padded with black bars, never stretched."},
      "target_height":       {"type": "number", "required": false, "description": "concat: output canvas height, 16-4096, provided together with target_width (BOTH or NEITHER)."},
      "target_fps":          {"type": "number", "required": false, "description": "concat: output frame rate, 1-60. Default: the FIRST input''s fps."},
      "at_seconds":          {"type": "number", "required": false, "description": "frame: timestamp of the still, >= 0. DEFAULT: the MIDDLE of the video (duration/2). A value past the end is CLAMPED to just before the end - never an error; read output.timestamp_seconds for the timestamp actually used."},
      "image_format":        {"type": "string", "required": false, "default": "jpeg", "description": "frame: jpeg (high quality) or png."},
      "width":               {"type": "number", "required": false, "description": "frame: scale the image to this width, 16-4096, aspect ratio kept (height automatic)."},
      "position":            {"type": "string", "required": false, "default": "bottom_right", "description": "overlay: where the image is anchored: top_left, top_right, bottom_left, bottom_right, or center."},
      "margin_px":           {"type": "number", "required": false, "default": 24, "description": "overlay: distance in pixels from the two nearest edges, >= 0 (ignored for center)."},
      "width_percent":       {"type": "number", "required": false, "default": 15, "description": "overlay: image width as a percent of the VIDEO width, 1-100 (height automatic, aspect ratio kept)."},
      "opacity":             {"type": "number", "required": false, "default": 1.0, "description": "overlay: 0-1; use e.g. 0.5 for a semi-transparent watermark."},
      "start_seconds":       {"type": "number", "required": false, "description": "overlay: the image shows only FROM this timestamp, >= 0. Absent (with end_seconds absent) = the whole video."},
      "end_seconds":         {"type": "number", "required": false, "description": "overlay: the image shows only UP TO this timestamp; must be GREATER than start_seconds."}
    }'::jsonb,
    outputs = '{
      "file":              {"type": "fileRef", "description": "The produced media file (mux_audio/concat/overlay: mp4; mix: mp4 with video, else mp3/wav/aac; extract_audio: mp3/wav/aac; frame: an image, mimeType image/jpeg or image/png). Null for probe. Reference via {{core:<label>.output.file}} and map the WHOLE object into downstream file params."},
      "duration_seconds":  {"type": "number", "description": "Duration in seconds of the produced file (probe: of the probed file). Null for frame (a still image has no duration). Handy for calibrating narration length or interface video budgets."},
      "timestamp_seconds": {"type": "number", "description": "frame only: the ACTUAL timestamp the still was taken at, after the default (the middle of the video) and the end-of-video clamp. Null for every other operation."},
      "size_bytes":        {"type": "number", "description": "probe only: file size in bytes"},
      "format_name":       {"type": "string", "description": "probe only: container format name (e.g. mov,mp4,m4a or mp3)"},
      "bit_rate":          {"type": "number", "description": "probe only: overall bit rate in bits per second, null when unknown"},
      "has_video":         {"type": "boolean", "description": "probe only: true when the file contains a video stream"},
      "has_audio":         {"type": "boolean", "description": "probe only: true when the file contains an audio stream"},
      "video":             {"type": "object", "description": "probe only: {codec, width, height, fps}, null when has_video is false"},
      "audio":             {"type": "object", "description": "probe only: {codec, sample_rate, channels}, null when has_audio is false"}
    }'::jsonb,
    concepts = '["The node FAILS (does not silently continue) when the renderer component is absent, an input file is missing or foreign to the workflow''s tenant, or a param is out of bounds - route the failure or fix the reference.", "probe outputs FLAT fields and no file: use {{core:<label>.output.duration_seconds}} directly.", "loop:true cannot be combined with trim_start_seconds/trim_end_seconds on the same audio or track; an audio-only mix cannot have loop:true on EVERY track (nothing anchors the output length).", "concat is near-instant and LOSSLESS (no re-encode) only when ALL clips share the same video codec, width, height, aspect and fps AND the same audio situation (all aac with identical sample rate and channels, or none has audio), no clip has trims or speed != 1.0, transition is cut, both global fades are 0 and normalize is false - anything else re-encodes (correct but slower).", "concat crossfade needs at least 2 inputs and transition_seconds strictly shorter than every clip''s effective duration (after trim/speed); the failure names the offending clip index. Output duration = sum of effective durations - (N-1) x transition_seconds.", "concat target_width/target_height come TOGETHER or not at all; without them the FIRST clip defines the canvas and other clips are scaled to fit with black padding, never stretched.", "frame without at_seconds grabs the MIDDLE of the video; a timestamp past the end is clamped to just before the end (never an error) - output.timestamp_seconds reports the timestamp actually used, and duration_seconds is null for frame.", "overlay anchors the image to a corner or the center (position, margin_px), sizes it as a percent of the video width (width_percent), and can fade it via opacity or limit it to a start_seconds/end_seconds window; the video re-encodes but the audio is copied untouched.", "Timeout or too-large failures mean the inputs exceed this installation''s render budget: trim or use smaller files. A busy failure means retry when fewer media operations run concurrently.", "Ducking recipe: give the voice track an id, then set duck_under to that id on the music track - the music dips automatically while the voice is audible.", "Calibrated narration recipe: probe the video, compute the word budget from duration_seconds in a code node, generate the speech, then mux_audio it onto the video.", "Like every utility node, media takes exactly ONE incoming edge: file params can reference ANY upstream node by template, so chain nodes or join branches with a merge before it to feed multiple clips."]'::jsonb,
    examples = '["Compile clips with soft transitions: workflow(action=''add_node'', type=''media'', label=''Compile Reel'', params={operation: ''concat'', inputs: [{source: ''{{core:intro.output.file}}''}, {source: ''{{core:demo.output.file}}'', trim_end_seconds: 12}, {source: ''{{core:outro.output.file}}''}], transition: ''crossfade'', transition_seconds: 0.5, fade_out_seconds: 1}, connect_after=''Outro'') - one input + trims/speed is a simple cut-down edit of a single video.", "Cover frame (default = the middle of the video): workflow(action=''add_node'', type=''media'', label=''Cover'', params={operation: ''frame'', input: ''{{core:compile_reel.output.file}}'', width: 1280}, connect_after=''Compile Reel'') - {{core:cover.output.file}} is an image FileRef and {{core:cover.output.timestamp_seconds}} is the second actually used.", "Watermark bottom-right: workflow(action=''add_node'', type=''media'', label=''Brand It'', params={operation: ''overlay'', video: ''{{core:compile_reel.output.file}}'', image: ''{{core:download_logo.output.file}}'', position: ''bottom_right'', margin_px: 24, width_percent: 12, opacity: 0.7}, connect_after=''Compile Reel'')."]'::jsonb,
    keywords = '["media", "audio", "video", "mux", "mix", "duck", "ducking", "soundtrack", "music", "voiceover", "extract", "probe", "duration", "mp3", "mp4", "concat", "stitch", "join", "compile", "trim", "crossfade", "frame", "thumbnail", "cover", "still", "overlay", "watermark", "logo", "badge"]'::jsonb,
    updated_at = NOW()
WHERE type = 'media';
